apiVersion: v2
name: rabbitmq
description: RabbitMQ Cluster deployed via official RabbitMQ Cluster Operator
type: application
version: 1.0.0
appVersion: "4.1.3"
home: https://www.rabbitmq.com/kubernetes/operator/using-operator
sources:
  - https://github.com/rabbitmq/cluster-operator
maintainers:
  - name: RabbitMQ Team
    url: https://github.com/rabbitmq
keywords:
  - rabbitmq
  - kubernetes
  - message-queue
  - amqp
