apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.keycloak.instances }}
  db:
    vendor: {{ .Values.keycloak.db.vendor }}
    host: {{ .Values.keycloak.db.host }}
    usernameSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: password
  http:
    httpEnabled: true  # Allow HTTP traffic (TLS handled by ingress)
    httpsPort: 8443
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
    strict: false
  proxy:
    headers: {{ .Values.keycloak.proxy.headers }}
  unsupported:
    podTemplate:
      spec:
        containers:
        - env:
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"
