apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.keycloak.instances }}
  # Disable operator-managed ingress - use Helm-managed ingress for full TLS control
  ingress:
    enabled: false
  db:
    vendor: {{ .Values.keycloak.db.vendor }}
    host: {{ .Values.keycloak.db.host }}
    database: {{ .Values.keycloak.db.database | default "keycloak" }}
    usernameSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: password
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
    strict: false
    strictBackchannel: false
  proxy:
    headers: {{ .Values.keycloak.proxy.headers }}
  http:
    httpEnabled: true
    httpsPort: 8443
  {{- if .Values.keycloak.resources }}
  # Resource limits for Keycloak pods
  unsupported:
    podTemplate:
      spec:
        containers:
        - name: keycloak
          resources:
            {{- toYaml .Values.keycloak.resources | nindent 12 }}
  {{- end }}
