apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.keycloak.instances }}
  db:
    vendor: {{ .Values.keycloak.db.vendor }}
    host: {{ .Values.keycloak.db.host }}
    usernameSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: password
  http:
    relativePath: /
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
    strict: false
  startOptimized: false
  additionalOptions:
  - name: proxy-headers
    value: {{ .Values.keycloak.proxy.headers | quote }}
  - name: proxy-mode
    value: {{ .Values.keycloak.proxy.mode | quote }}
