apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  instances: {{ .Values.keycloak.instances }}
  # Disable operator-managed ingress - use Helm-managed ingress for full TLS control
  ingress:
    enabled: false
  db:
    vendor: {{ .Values.keycloak.db.vendor }}
    host: {{ .Values.keycloak.db.host }}
    database: {{ .Values.keycloak.db.database | default "keycloak" }}
    usernameSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: username
    passwordSecret:
      name: {{ .Values.keycloak.db.secretName }}
      key: password
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
    strict: false
  proxy:
    headers: {{ .Values.keycloak.proxy.headers }}
  http:
    httpEnabled: true
    httpsPort: 8443
  unsupported:
    podTemplate:
      spec:
        containers:
        - env:
          - name: KC_HTTP_ENABLED
            value: "true"
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: "false"
          - name: KC_PROXY
            value: "edge"
          - name: KC_HOSTNAME_URL
            value: "https://{{ .Values.keycloak.hostname }}"
