# Service for Keycloak
# Supports both LoadBalancer and NodePort types
#
# For LoadBalancer:
#   kubectl get svc keycloak-instance-staging -n keycloak-system
# For NodePort:
#   kubectl get svc keycloak-instance-staging -n keycloak-system (get the node port)
#
{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: keycloak-service
spec:
  type: {{ .Values.service.type | default "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: http
    port: {{ .Values.service.port | default 8080 }}
    targetPort: {{ .Values.service.targetPort | default 8080 }}
    protocol: TCP
  selector:
    app: keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: keycloak-operator
{{- end }}
