apiVersion: v1
kind: ConfigMap
metadata:
  name: do-exporter-script
  namespace: {{ .Release.Namespace }}
data:
  exporter.py: |
{{ include (print $.Template.BasePath "/../files/exporter.py") . | indent 4 }}
