apiVersion: batch/v1
kind: CronJob
metadata:
  name: cost-report
  namespace: {{ .Release.Namespace }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-report.yaml") . | sha256sum }}
spec:
  schedule: {{ .Values.report.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: reporter
            image: {{ .Values.exporter.image }}
            command:
              - /bin/sh
              - -c
              - pip install -q requests jinja2 && python /app/report.py
            env:
            - name: PROMETHEUS_URL
              value: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090"
            - name: DISCORD_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.discord.secretName }}
                  key: {{ .Values.discord.secretKey }}
            - name: DO_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.do.apiTokenSecret }}
                  key: {{ .Values.do.apiTokenKey }}
            volumeMounts:
            - name: script
              mountPath: /app
          volumes:
          - name: script
            configMap:
              name: cost-report-script
          restartPolicy: OnFailure
