apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.do.apiTokenSecret }}
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    token: {{ .Values.do.apiTokenEncrypted }}
  template:
    metadata:
      name: {{ .Values.do.apiTokenSecret }}
      namespace: {{ .Release.Namespace }}
