apiVersion: v1
kind: Service
metadata:
  name: do-cost-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app: do-cost-exporter
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.exporter.port }}
    targetPort: metrics
    name: metrics
  selector:
    app: do-cost-exporter
