---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-app
  namespace: staging
spec:
  encryptedData:
    password: AgCS5MWHEyN1kAl+s3pibUebAG0Z3F4ZLi/5kZxDoan+yXdRgNSG4J7eu/At8s4SuglH6q+3LbzpmwCEdHkfjrJ8GTKT9438HA3wxjO0vZUo9QMOzWqhlLOtRjUgcvHc4lgpUaI02zpCXawNC+4lBILUCtcOagAPiEHnhbNudULJUSPwMsKhMrLAYR0LBqxM2Wxw8IzhKo6nFflrFbCrTyNMHAFGMjdpwNHS1MX/Bdi6tzRjiNbeNZ1wyzg9jtM8SVMIIvURsVy6L8MT0ENfAW5IA6bo4MhoQmlK4K7CkZvEFmfEiq3WDNWkJIjpe25/iRLrUZmPZb7Sv5i56fFOFKIwUSLZ1f4DPM85rbeU430DNaq9v+ezPTuGrtd4wTFxOp8yi/qGeIL4Llmy0P6GYb7PMg2+V3OaxZlj1v4cdXWN0x5GImV8PCtU1rdmuthtFo1z1IgcIsYzOofLNQukI+tAx/yhI4fVsOQnJvVXYtm8QoM/0ydm117VOVIp6V2iVqi6DkXmb20hZvc/ey2FhbQc3Iqj1IZZ0zzj4kIMgAne8vwN/H6xMMRj9g3HvU2o6XtCll5yNR0n2IizwNznTw7+HMSU1SoS4+P1NH8Pj8ZJvmlIyCZUa0NptDRatN9TVWXig894Uz5Ppt6uw5pcpx5AUF1pMm0xGohJnK/yCMSZDUgPye8h/xk2hLBDhPAe3/nMu4S8QH0uYQ==
    username: AgCNlDF4XPOL4u++DDRNbDpwVlRSPTFBYYbbonEcimLFoLY1YUuO9oomScDZmWukL9W8keSJdGx9kncRX54tKVVcCcnnSOshEfdVq/0mFmtbLgsSVjyXx99KhXLxFavaZbs6z2wMsifJUXUx10sFZ6vt5J0Zg9FKu/VNbCOQm4cCNMVRKM8W6tyZA4nF0OQbyDhU6QkC97TkWWNtzVudhuwCbMt3C5+Du10TBcdUGBqZT+ww8OzD9WCQbVVclPNH68lPhvriaVI1G5yYKhygmimqXWvQxJ4bBJ7Wt+Z8WjXs3fKg5tR8fxGp15shueCioctqIRqAzWdCpIaXNQgL82QBDQcdP0JZFVf6x11eOVWIvnOj3xdoikl6Q6bWRyWepv++eHFiKlwDeGFIlKfx5DIRIGB+JjyBRJPXxkYpiBnem56iXNV80FXkjBl68WBEGjB5jRHuFdetB6rWepIxNFvorgzugB53JZb3ZJ8FNB1PDoZx7m6r7zJW0FwaHLWGD/t90apck7+PcJQppcDc8v+UjZwrvqYIkNGI33TnJM5qU1egDabgNgOo47bOVtG+KWW5mq7WEtK+IAaXBXwPd50WM/eljhs7wol6xrqMgoNMVLiOBm9sq69UC2QmC7inHCNgFJDJfMO237gfTgeSpswFbTFLoKU8bcLeMo48t36SqwObRSFXdiLQb8jgXxzO2iJ3VytP2ABM4oY=
  template:
    metadata:
      name: database-app
      namespace: staging
    type: Opaque
