---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: do-api-token
  namespace: monitoring
spec:
  encryptedData:
    token: AgDKZTf+NVZ9yH1efQT58q1WH+DQL7C1wXX/eX3uSER9C6qPg8zItdgW8kGthoacS6sGT4dqcjfV7SWmKRgNw5ypxzhMDzZfiW7AwCfCdnp/PzdUoAbx1z3F0mhCuMHS0Y4Cq5Ng3HxH0/KlLIEPQ11nTX/8hszAsw+hn+vf3k5e0RgHZrEomtIblgowSsGt+H3NsvsUj+IP1vcrniXsG7CcUnk7bBtq5XP1bB2gCyyIMLioxKgyNWaG/B56ELtVc+tmZ2488BQtqPqcUFmVhwrncBagAzSk0/lUzOoEo8NvccvYbDrxDANSyacYS80Q/a1Kr69PAaohAW/fDFBK0SxyoW9Zj8LfvYpAGT8TrvqvA3xBGJQGvlKwwtlV8bSks4FdVr5A83TmDfe7bexrF8TvMKNtfnCeRp1aNdPWZ8nTHQYRiO205JeAo9Ar4Qj6jgri3tmdLDBUDZZb9dbHftJB0FZyFJV728fthhXaNKgJF8xIaORg72cH3NfSTpWcf/esl0N/lh4TybR8fgcengrS3rbxMUqMhA4yxFREsrs8piD2469PbSF3geIwDMYVFocNzpbZ8QGhjoD1hLnIkXXwOKS7qdWsgjcXGxhblIcjJjQkwMyI4BlHOu63JSNgGiULAsPLvhv0bOS/27DILBRS5QVAH/SCUj+z4x3h480YQ/nH1HQ1p0bpMRLDsWoRSbY5hnKDXowFvu2uGY0IHw+fdMLLxa7UmPhgl6ej9t483zQ6vD+9hpBUkmcVz32hTzL6bIO+oZoKvsERBz/Zx6BicZbRwGLL6Q==
  template:
    metadata:
      name: do-api-token
      namespace: monitoring
    type: Opaque
