---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgACvj7K0zUe99VFX7lXJa/K8e91YtWiZ9omjTtfNZybNwCON6vIVAXkeglBAAXEHsGrrCxhfn+n+Qe6ySgt2GfeOLVscNZAG3ionbH6mTryTyduDeydnzuCH5H7DAZJVUo5Bk1ZctwffP1+tKa4GYLKx/me0Uqc6H/Pw+Mwrze0toVLWkA88U1vzxk7GSlBMSfoVUvR4XuQPOeOACg2WD+/BAhHwgdAiiA6TmodkcYI50nswHDyipaQKJhq4LZHsRYUzhgrhjYNrwhgXU87n4i52epYoA2Prs/UKJflO5uiMHCQjrGXrFMIaNdTTHqovSrk4u9U5HLWgavhgqm7zveAdPX2762vKkJQwPjw4dM7uoSK39uGma1B+MLaS68Cpkn3LtqO/wNe3hu6fqnyYxmA1LzM/FEZRt8Re5uy40nyfa7DgOktBgWZx/M8zDSBnt+ponerljdb8efL4xYeqONBpMWx/3zO94Hl5tO/GJGo4fYQ04TRb4VbXUmY/NkivjhVTh2mm7qhtmQF9QYx2Ry2TWVE03gAqoV7wxG4H+Fi58boy2wO80pR35KGQcCBGy3OIKy8cvwnE84GBGZWS8ItunmFwURwqk4Eai97CXrRCN36xqrpj/KXFYqtlGfWpISebjAhDhQ+DQWyHOyHcbFcnhSbKmE1ddYcGRoFfSpviGua59N/tzdby54jNg+ByA0UxdXj/TBr5g==
    admin-user: AgCHTEALaXPVxO7ExXFqokb/GFO8qL9HgePa6rPXczClGGHvUeG3sGC1p7CgeoxUePotrki89YSTiz6UjSZwPkQ0wUU5xgY6q8RDzrhtp+pIiT/Alyv0+pV1hQbQvz9R9wah1QHO7E0vaJRXheyQi5YLj8l3Y75COhmZPuYSlqAAhMNdXFx3t0qDvW7a3nrPKdvFbQYsRCtsNsdv5smtF5pbgybM7AqJaKXd3thnlntzZ1ox9XxPuWgx7r0BCrsIefFCIV6IN/0UKPRwiUhdadz1gByfyUM63E0n5da+OQQ7lcjtguqk+qF2gdG85+TLWwF/l1OEIF5BiErM/yGsG3LxAGbsk7KRnGiSQ4YWk267j7PjIE3mZ68ewCDbkdn3WgCxLEMNVJRTnsk2SiY6ISM+TuYfVJUtH00ZweYoJEwggzoWwumztRXo6+e4VrMsQhY2fgYQWpjUe/N6zBXEM1jj4K+L9USH5aoKJZnjpKtOrLsIvyimc5i/+eFIkS2qA7o77vWh4P7GFyT9stsNINM4URxCCLKg6dWnqrTjjzNtu42KTRSkUTjDCJ5JROoE8Vd4dmXLvqf2pdIzxaEOG2RlvI8iIbGMiNsaGr+2eqp2zsFIEYa5duO2p8cYjc9okeDTU0lFx7xVNe7zRWRNGi0FvLGKyOdpmMyruwbddmmMIMVrMZJ3wTJoWv7cGW8NyJE0cd6cdg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
