---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAdnDjHGUp9sXQe+bCeV0gmO1clLtuzGDQyBJG+mRCw3jS1ymPTvVilZKUtwyq9Ypq7T+0BywAx8cCaFSpDQI9hwPltCTbzFGwXFp1oVhchvnPB+5hj9lntsN46MF+RSx5NsYzvU7KrwCgR80VckgKdpRGvgcDWe5OuVQWQr0E+8KK0KoC8Gk+5kutE1FqSYu3khpo6MKomW8t5TbEfbqEvbkkljAmhIq9/L0lDACF/7bRCI76TgnyuLMfHbDC7TGm08h42DRO+p4edbFCPM0ItQVcZNw0pWUmW+vCWPJv7E5boALiiaNkkYvCNzXH7wg9kGb43yKFXNp/KCk2Gn5lKQyisw62BGn/6TrG31+3dp71hAEDL2eexXDxd4OqqaQhdVw24Q6j6CftT7ZezDZfv/d1O5aRwQcrx5cLbC46Kj9LxswzS+amK2bqGfPMl5THfqBam68nZlGBDrNNVLtaDdeA2pu+IaD3Ns6mXAGUXLBqzPNd4ImoEJFaLet5Mov6wcugnH+S3T260Jn4GVnYvGMyX62DLPiMyHgs2Sou8XX8YYVWeo9FaDzK7TVjYJ3LDOqhr08mb0w4H19teaieif9Ddk1fNyKOwugQFaeLqldPQDI9ZB1+BRrY8nePTUZrl82d5shZAH9g4b6nDk8CAeAOQDO5AdtoYBjMJhaqZ18W4wyWs3IRMOZMcFEsaufO01qWjYnQr3A==
    admin-user: AgBYt0KsrfW3eFlKOpmTVkkRV0Ul5rFQCtiKnOtYIzkWoFbXrlu59uZcjaE423Lsb1vt9aZ3C1Xq0F2XbSZJY2lUGF62kGS4Y/ingx9+rwp8JgbJrWdasITqz67h1pqf8b6F5YnfHKi3i94F8y3zDqBmzMVkT/BEcRfyoYJSu835U+O/9u2KTMf+t4AQ2FRU+aPqaq26Vjju0hZvDwAH/dt2LnOEMzSxxxFzdrGVV5FQeUspbubjQdBDkVSH2hU9TAUUaomRhxr6LAN8z8UaNE6FlErY4U0u7fUYJl+1uTp+9Eu350mEZpTomBa4fMLX3khPiXXNxFG8eA/gFRiEo3ht8O4WTV7O1C1use7E1IdJrR8/x6d8uqONI7MpagZtTyrKON+lE8pHZFOzAusXhWvvvyrcuN+u/VlrayKhOnZx+m0Pvjc8KzimbhryBMIHeyZN2M5BDhCkVuModzPobQkqNVqz1RCjP00v1P8Ml+X/2fVZnRtbkcZmxHjhFjr+QpAsNSyhVY/V5Gy8bGrwCdETYR86BUayCy8nkhjsm2Hm9fCvHshURCE/KL07zKHPz7ylIike2J1YEMgi5hXCBI7LOPXs11KGcdKkEjOXxlQKeYoZr9X61Ggh9ThNfLnXM1Y6qEKLfwhLCexCcoJvr1h4ghr+kEDLwySkfQX/GWw9ZbwXDSBb0IpF6qe9zoDqtGkRr5Xngg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
