---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBh5HOP+LzcGLaEjlG1/xB3atO1pP/XfUQQFf95e85bBSNNJlY6LYZmaN2NCWWOoz4vlrf8zFjwItztsEX1QOVaDf9lFWnEdSjUeJ6BNc/3LomKx6PUckrxL1V4oNBV4qS6XQRd7FtNvT9k67CTgczVuPQdUewybKVTljLA0qmDTkXia+nXL4hb8bzCysvc5AXP8n2HxFB7FfDfnrtM8UHTBuGMqkP9eo6/Wwibp5MOSVvhIBG9fAUUGkt+SgoPg1QVeGWue6XGv8BwORJhECopGDBIqnX4lt1evBFt5xwAdMzN06qmER1Qd/J2zUBsRPJhT2TuJug1G5M/wXE74NnywXzorrl/clZKhDv0fFrNG3GPtBipraAtelERnaXpkIK7To6MZJSrX9chyIzE1FrLvUv0XVc02xsIVdmliamP0d7lMevj1P/ZHNGhBCB41jsXCrYCZRj6Bq9VlyRVrQH7YUJ8oCtbDR9MsCmg6vQ91GWiJaCzEFvf5DEtD0NbaxGxHELbsZR5/VRt7rY4LhQKF5nqzuOK7kooWoWigzd/k2/SkayaTw8gxhhPP5DKIrSk2cIRUuTH4ep6dL3E+RMmMf7fnqJ3AXZ/+7iKQ+2426sn5almqEuZOiA2bazwbXHpwbcSvc9GKauKGR31G5I7TpNDTeD0/bAX4fsbman+LzvJxCllCdvgRpt9SxUoD7/QG8hdxdzPuw==
    admin-user: AgCr36YIom3Nedh6KQE1vRfYP0WRu7L+PBp3UxDNPoqlmFG99Y7cxg88arSqSu9JK4srQ3jSPB7t6sTXMzDDJo5ifXTsECgnAyTLJTjJmxaaJlZMaoWC4+z3urKbjnuudT0mUEQowYP3/l8/bcZxBWdsvevc/W6mF4JEgsy4eU+i8RfHm58hws/4Gixzk1mFZ3rTDDJRawj24TxzbClT+8tmRNMilh3Pj1eTh0zg2Gmkk22Jnox0tlr0MErh64ZQTSahOyqP/UzoYOa4v64mYbjExom9dByiDWn1RPOkrHhQ2pR3id+wQ5abfk8dYpHg44vt12NyDqRtr1R5l6nEZlkz0hIv4xTasN1ZzPBnoM5FbJ3+WWRFXwpahekspaIKGoJ27KAQbFzJkebKGXvMuli6nhuJl6pw7rt5CUtD/FPGyzYhS/30z6aDEtgAsmUnIjMkjyHyZ72u1ZlLlkL94hhQFHeItopFmLRn4dGGYLuw35S3GwSqh1hzm4qx6T5IIbVpqPwTipSlQcZyqhN3KHe683da9XmvSa7NNYOdk3vMQyqC2fgbW59RO8YFrL2LQBYBgn1UPPXBrG1gUHWQl1WG1w2RjeDPDPQVe/5qwtHeIy2MMEJqgAYPUVxqEg8sLM1y7344lhyJ4JdPEkUBfYMGzb+rt4EtpRWuIhJdufFyUuqQcfQzvwIt9CMdYL2K5RizxfzJSg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
