---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBXXlfypfyOiK+oYXbX9byYE/J2txNcpzv9gYozNS/7TSL5WnX6tB9ksMX1PrS8Ss+2tzS0oytR88Y5ua9FvctKqb6+HCgm2M/9qLqUyfyY4LO3VPk+gDCeATUebMEZQ5aqVhnle9/zoFbyZbsmOcDjl/u3At8+BrZSolcossLSsnh4z9mT8ETvCUYFTe7Us9aCg2z7K7uDqiPj/GzKI5lgxazUqM/+l3A+zjG7Q+FOaAMCA0Tav8uLu5A7+LBfVfc7frmzk1aKYIeQjCcw6uwgIZ8M/KgFCHjxxJfy28gMTaZy9A1cewovN4ADpI40azBCZMqwEXa+wSxtAsIjmliKzpHxnmCIl83POA1hMpuX+ewYUsQ0nrYVYer6XsthqCSs4WVu0txn7GSRLfG8cHkIc3VF0/G0GAS7aG9Xq/pXetKJgLHaEZz7OgAXn7Amz6x1ZSnhtclQej2TwPDwUkH2wvImC6ps2u9Vo59LCS2ABksLHEI93FW3GTNsMKlHwce3SXMmFerfPp7lUN7hOw7vx24S6FGtoz1iZxo322uOJavLegQjLcCNsgI6BXMM2Of9SmU0xSHd1fL/baeS2mS89J/EW6bRFG0VwiXwlPgPk7eN1NlUcVo73pRi7mVaePGc2RylNdnyTiGnn57t7yPRFbW5h+kax+Uv2uZ+x7b+HQQ9wOOXRu8NFmxLbevqerrVCItKgsvX5A==
    admin-user: AgBx2uasc4ZEtV1MWNJcflaOzk5mflvfSTdgeRjv66N9La8mcXAyVR9JOaUxJDfvP7Qjks5nm9NxrxkwHFIdykErMHlnpi+T+1y8H2l3OXmub1ivmjHxGEtJy5u54KQK1hC5lnNGugG20INjMxStyEVCV97A5bFXr7UaIsoupmaa9gght0btRht6GbG913fuYWFdJ8BAWubkFFymJwu4lHVqHpucMTqO9719hTzRk8vXiSceX2gii9WD8+M21v/S87rgRLx8mLmJT5qghY+RucOihAeObwUfiQA6TLN6EepEA+//acX8Ba4FwnjUF0CL7lIYMTLQVve6T79PGZZXWj+XNk/6IouGp4zdlSbD+I4ZlhpgJbnNoa7phq6fLMHS0VVuItVesfVz+nRJjAFWVjtR0u52J5hh+IQqdC9cPSQdY1c/mI7PdPFTf00NUbN7nzwdJk7PhOOhDtDDX3ioejyWXw6dkeCS1NlPtJfxTtdV7xAcA3UjKGR89E5H7epXt/Sf+WOSbkHw9t+eiSH8rDA7bZMqz8qgYgzpC+n370fJUkH0Jj5Br5X/Qvzt9w4zdqI8Xt9ORXo00HH1wvXYC/4wJOHYgd3/4fr7Wn1UBfiIlot99OgUbul2PgNZRP8dair/RWm5OkqXrchEzLNZRl1T89MV7xQ7fsP2i3YaL2UnToNm/2zgf/FKp7yr9oNXZW2zHXNC0g==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
