---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBq/vGjuj3PJMMYZtasXiuclw8mbRs2lxCluBwUqFfALzu1YiyUIOwk01WRuIryjDkxMmz13SJDbYWD7SM5sEhSyPoGIsLFJSHrcfc/8vzQtSCRdqCmIvEWuBzWCh71adOl1esvrExqQZk0RsUzYhulufxS3t11tHUtqw/kqfSvP3uWugPQ558qYwTuwC/tEhlPD4usPmUBelX/5AvdVTvVGD8mEApTc+L/I3bS6jySm75n1lRS+qTny3/VxvxGlsSZl8u5b++yxM5zb815p+epo0iVOMFD4lY761Xe5ziCCfq4kRmih7bFDN9ILIogQSRLTpC1IpBOsOx/3a1qc/tbduK3siHAvT6YpJCUrtvOc0GdO45clnsJA9S0vT3eStcTWL3y/z4vAWU3O7sA9fzEktxzje2a7iIulTUSLynfGCab9inso6ThD7UqYSfsa45Z1qqbwqYJUws3enpkVQBoi9z6JVKkyt6h8J+wVtpMgIMa7wrNoqXcyoq9Fi3eUJX/o5dF0XLjGF5kJP2FKHLGJI5CE3D+yd2e4HuSqYU4NnkTIDoyOBkSKVdjX/lrUIIZFsawOJBtRGqX8kQRGShZJYLWrb8j+IqXmhOolMKIEkcDaTLmx8qljLccs6PaCipAE3FPyYQ1SD8NMz2Imvn/oYsfqf7EzOIgipDYxKl6qxCENvFPu6OC3Wbkjo2U3CacnEPovsibyQ==
    admin-user: AgBG4EKQfY716INtWSY/j2fS5uEdFo2wS7O+H1q1jeZ1EucTHV0VfOidHyCILa+AD5Jh2B2GgzBYeCwGLkBd3Sno16xmKVxUcW9exbr6nNwqQy7PxAgiQt77i4CJht0S0vvP8dQaTo/YlCdqHjZXrB+RvLHBa82Q09g9/ClFLVv3znN73UZlT4kfqE9N4C5virqX9dWJu+dFIZ9l0jB4CnyJidNlhmCophuARMH8oJ5ZEyAaDRyNOfEVlH5URLhrOg9/rg5H7BgjsyhHpFuy5PmR0vOTzou0YKM4IiicC5mQ4utxW6qtxTIc2TNtVyeQBiFJ9bniTgpDkrviAp78Ic5zZ8N9I06N+1EKPgEGcWBI+hCTUnnk4QWUaI46hPLCe1lsyecteGB+Bckj3HmmTMa2dcWzgneii0yiE+dxajexO2l6bSPedoiCgbN4ouiglcZ4nFuq9jLxoVIYPBi/BG/kaQvvnDSNdeRTdxkg6OntMtglOkN0dnOOTKeO3Flakdz3h6f+Iea1BcVl4qZ0Pmqch+0zqJbP+an9v9u5Ht5t31IV05pZmDyp1CIZpKan9I9ak6BK0GrJx56n78jqrtqSVoZLsmkT4DyxfOFclEJga377+6rEgG166wpTH18mM0oOfmIJg6eUZRVsR4ZqFHqi/V3TpwY9h9q1TK6Pq19sebi2xZKvJKIhUWomGgOqSFeQsYSCzw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
    type: Opaque
