---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgBjI9eDgkm8o2P0ra7pHZt1M0/M+yhSNi5w5Q0g+LWwc7CCGbdK1fi1okkHNsY4RiR/oM2Samvm4l+MiHTGJLRYIm+1mxlsQ2BApjbahbS9m+H5jb+YlBAkDZYfvzYDgsG/3w/J0V+RQpirzke1++/gwVDRUtgRFDtAAlL8a3vH5pROqiZi/+97YS0GdIHmu/sGVGXqqWq1/2PzR/xWurY6KvDOLkoe0J0vqjymCdDnByquLne6IIX8QKgbanaNnnEAJUuc6LX2D1MDfk2MpV1iJAUxPjfK1juV+obd2hxsiSG7a4jtIIoJtxmZpcYlQjdyPWRNMwLwvKUI9qRlV4xEG85SgnUQfmFsXvvDEiX5SdE6CtwaEsNj++2Z6JWoVE7LITZNlvoRfMQXrd9atc7w+7oOXdOY9yt6Cf0YLLs3TjAOn6PSgaKZYFiNjctwr7e9vZ3Cntr4XlEWFPjzAx9CeZD1vQZMpAdtRczLNQ/7HFdYtTk/PcVFw7cViel8Pnz2q9uF9s/bb4Q9VUC3Dqa+un6R4in3C3oYusizExhPlurLiehpNx6Pa/exqUKAsb9ANl6lzfIkZ5kjHnp/ru3uDCD5Q8hsOkVV8E93rWhnKXBGZm01EVSwjyKM6HtREVRQd8iW+TYyXM+m6nOjZy86KGfA8EWibm3954SWWR9oy8faoNs3VEvgFtfiWB82kLF7K/5b9AXS5s6omYvKPUyHeg3m3DSenVqJBwlS2J1wCJW4CrNmdjAEqGL/Uqsfj6KIAx9AIzNJKCdThYQjA5fywxvulxIONsU=
    google_client_secret: AgBbkEQYei2083Bgy3RBciNbG/vp8sZB0AdRYh88w6Uxn01J8MWNDP+Dvfgh+NNySbFGs00dOYSSLsffYlvSfFw00Y9hLCDm4b32OsYVwHifNk8mJQ5hpfW19avNMDerxcFX2c3LhBX+++N+DYrvSCLzwC1ArRQdtUJ/h/N/rU/YzCtPdt//Tb04Eq9ahOinobDb/ACkbZoMMJd3NS56KVjl0ZuxwsaAHH5s7nNCMZAPKHT23khH8FhemmgczPiNDnvZzqzxjVRpomA925f37Ul3PZUe8rrNkOFvfCsEiN74MGBTUczKgtPq34FgkF1WPsHwwaZi6Cc3lZTyjTwUCaW7tqDpGbZ8kJzOFYDKOOM4gYDjYSK+w/vxXbuW9nD+pJGyxP4vRgAuaow5L3fbmxm4kBjxVGR0wmQyhY2ouvR8FQPns2IXfTiAuhQuNnCZujkYD4TG0wkIpefk3ohxuwelAVime2UsRJOzTeJMHWWzJI3PpI19llrDBG92Ng8uDnpzR6swHzlWSr5zCXarCHZOq8z32XNow8hmQF+ksXTjMDk8w109u85hFbDpC5NW7wkWoI6aPtWEFsWGaOy4ysXyfMVjlQZissnieI+zYg9En0eVOTwBdFVu4LQv9m12zR9tIazTnZn+fpyai8KqrIKrYAR4G17vm0UGqhIrFLrQ/OSxAJarOQqRurGM/EViSKpXgUQxLSFWwYtU4V4EWSuLTOfJeRHwioeYtYlHF+Oa2DiVDQ==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
