---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgDBkZAas3S0R3ME65kFWvqa1lUwNcY/WFCnRcHwcZGJ/hovdMjg30yYvgSptvWr4nE54aiLty/dL7sc+VePJDxaP6b07MK3S4Nhp3EPQ/X3gIqvhvECmtDtUekr+I06P49ssVMoVOtfOsyBwGHDI/s2H52L0TjpmeVJkEMLSPb+K6+I8CiY7Ze1NVzcSKS0Ftkf6Y7o8no9eaIcmCLa73dTjFPj/4sHuAIHTTTIPxz6r65hqNr/Uu1vtco3SNxfWYcxMEN+BcD8o5VMFZJGFCroN0o82aBFmPz0d9ZwD7MJh8hc66jt8uMwJL2pZ2U4eYBq1L0dheBJwPFyU3JLYTBIICGIvrH97iRSXpPL/aq/s6FQvbF7+96iBz2EdIZ/SwdWvwALYhlmqo9dQiy1iubJt1GHxQkHH0EAD8n/NUrDgyiGAqrLSucPAIBJ5onQiriMCZSX5jHG+94QHnnKNJQeJdzWoYj78HQ+RpR/Xu1hVwoNikxnnIdvRL+14lSEm9h3R7ppObgR9EuhI6Hym6+uydhrLFfWypPUgDtemptKISfFwJyiEFc1uF39cgl2YI+JYoCrYB8xMh0tyd5STYoXa+1cIJfgITPmisYEMtqBNGWcLvG3NS+g22TPCAIkp7bkCtZv44SCa84Vah7/Y25Qg2NUJdS/9/8T/9BoO2CV96IfghTohKgLynRBmFPelzr47aKiy/FeBAeI19KgyaP22Q430+Tar4F2u3fmJTm8t3Lv4eXKgSaq6d14SPaIuBKRD3Ul0pJygybEkfg4T5NZSUr5k8zngQA=
    google_client_secret: AgA2g1hOwRqCQ742+mj3DWhAzmYxQeScjNhheBVDukNPte6448yNvkAZMWWGwgxGKK6hHeVtkafywM3SIlaIaKHOG307MKqSS6iIeAVFzPZNnGZfRnRw+b9q7XtCekpVqWuPh64wicY6EL4zOZbeAErL/TkHPOpUb4B1gfWYAQFVNsecQV62lWn3ad+GGNwA/9QOx2KuTzuuCjuayQ86bepmnVe2duuUjQRfSeHgl5yBKYfP847d3QWEbTUPUdGZ6tKQfV84Et9yjtsMraI8x1Pbop8H8oHXDPqsNsw49x7T1z1v2yQRzOWUZ0pduPkF4G9BMehgAb/MTakb3AyMPTjSc6leih2SlFKkXhDgRLkBsyboPsy9SRuXdqGLyRd8tKl9BXTJQEM8+cb8W3Aa/IH60YiLP7ol3TXmdfpJwOFi9gEVtITAAwmX5WwQ0f1a6pp1XKZkCyhRajFFoIPlmVo1BeFTPj2laJR143TEPgBLVqRwlm5BgjRw2NkZD1zesMQ3NliUQM2EBXcDE64vQiAXl6RQe9DdHadBFDwPI3rlPM5eg5bA5RtXI5fLFaRYV7Sz4rZe1LL6edcILbIbc91JGSKFNi8uDL+StUtUZ70Wro4PkzEBZkCPY8FoDf2kiE3WFhoYCSz17gaE9OWcYoSpjwiYj1pOwLNKEQS1HXIlCdnkwUr5g0AOZUx6tkEIUD1vdu1OvnAsDdjH1eAQaxZiFeKL7f0tWRyxxkXsX4QMmUpIzw==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
