---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgBMgufcWJE4Gildwblj8KRMfn47nZbsQufwvL4VUO4TsO6rPo5Uz5tjU9gklDZTOpwaQddAVhaZgYHYFt57HBtGdSrN32QaWt+bTVT7fRUVy+4lGhq9kLxrCSLR4COsxmZI/BNx4GCXyG/hTR0SCDE/57wkwl8GP9PlT42reYRu5e3q4S+hPOtZhTDb1MUhmyyqZLU1ZLisg7aCb9twgk7siA51ZsTstlEtm4CQZ+QGQ92PWmNlIMGNuHXVF8nW9ZCKKsfzR1PDOkU0N821IsogeJzyHv4Dhb4NbS5NvyKC2z88PuGqRz/buM1IUN30Pfa+XupUXwWJT5ewtMCEdp5z5BdtheVYMvLinElx6xHiZ4qVaACRz+vyJmFlILjHzvYgYmCg2hQiZldcFHsz41k86w/lj4RvovRjK1ufA9B3gTqMK2+x+MlezcdcKPkLyQE0JhRRVXz5G6ehhvQ1aGWEOPEPis5IbCCd5TRj2ZvL5nRZNAmguH7cEIMrur/7o0gJ7QycEHDTREwMPZ68TktcBn3V4uPf7oFQo/XxMuVOHp8IOIyf9aexmm8wZtnALYmUT/YSJiVGXnAWoFb+wqU+8mdPZ8Lz5gl+ZKPKDyZ4R4emqMjdUPrZWKwvT/CXV0mmAW3HZD+eZLVCs9AHB1JlgzA/ZBAanoqVidvX6hfvhHzEWj0QhDs2UGLiOAA6jwFpoLFs+oDZ5O9dSJwiTVRwPbAqZFh2tESnZrcMSmi1DvQyv70H3XHJasy4Zg==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
