---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgCDdbFcaEOqKvLrksoSgJsi8+yKd1zuPNBahoTGgYleC3hqdKJ1s0l5VdGvjo7eu1ez66DJkRYdh94SRYGITJFU4GCbdD6/4nOqMSNKnY+394wngGrVs5Tz1G7rTeM6ReMU+opeMgDKKltSjmf5JC3RF9oTb9xSJMg1gMFS8KFFIymzaIcjUL9cvVNyKTm4lFcW3O0a591PyHzuwj0W5q5XBoK3GDIBsoj6pImCfN0Yiry1drJLu86jL1lQWXKMO/axiFGnES2+q1jhGQI5DO4H5qvIsEJQm+wbOyJRkUQyi9uVFRbewZclaGfjS1kby5GEH7/dST9/nBKCBBmO6UX7wWHXMRlzWoxxVpnGodzmsdHOCV97639gIOU9qouUN7W3QFlz610SWRkfedX345JBEId/GnO6wdzcykPTcTKqoN/BtJFEf+zNrslHJIw033cBcIsq8UB7J7PPWMDAlpd0Zb2ZkXhFUXYn/LuisxPTopAbZxHUgBDUBi2xTqGjPde0XX8s9rL6YgtraaoEyH+GBTj3VEoKocbYGEA0EW5f1ViMHWTdWw/Kb1H2GRy1qI2xm5tWTbZzDKC3sw5DTIu3AGqPAhwTifRFxuGgBLKYlVj88NRAjPl6iXVVSRnddz2PY9uiIiWhcLLl/LbGXIBfNaXGOvT+UVMJEQa+Y6upyZB6Kh9xPM+DbX1ZVDiE2XjHwL5F6/dhmYS+Bg6h9+8c7LYR034zGFXNBdBlvGaE7AAP0YR0y+7M1SeE8lDrLcR65m4QifAXNwfXVsG5KHcQ3Acusx8w/rU=
    google_client_secret: AgBvMyBmTyoG5RN1dwLurPYykPatCOQCYrSWCTvfccpj0+ilWqX744/NU/IEZnqrrH0pYyxHeYXqNz04cTye3vR+W0K0regSrvE1WTHVLdTwK+VLOP1csNJlG9z7mGzY5++G/knUcOWujW/JbxR13ZfUZRWCT+GIRIndaZRx1kj++aRZITBunwiVGX3ezRRfGIMc4qQSJIxATV1wp0Tfjys4nzPE7B1VivCLXDk8Ri1EQTcFMFz9DlkzoGBAlEP144R8jlMx6sEECliSRU8SljHknQysYxQrygYQ3YAYXSb7ppeBezPQOwR0HWL6XEsOUb6TtYfLhcELWLbSFePP5PSTWx4XRoeOu1tpFCfdF8tbw1T+0/BirdgxbX7hNSAZxBJyMAAYB8wSwNDpCTrYj7olmdOyNHnevSzLKHOsk/ok2/MRzhM0PTNwfBuTIkdsCbpSkJtVGn5ijJLDfv+lqCqpIiQn6F4ntmCSHqv7sHQxLl+9ns0/W0kD6vy0JgXYs6Pg7TxWETI0+PkdGtfK/neg0JNDCRa8WMhjEa8srBEeZ8999Lrbc/LYITBctcWUQ/TSDtaVAgEq1HLcCACT1YdUejHllzMaY2TdgFKYxoBOoyKFy9z0B9ONYRuQtDnrmhDC0LMUoZDHw15N8YCANs40jzKGxijHjB80zApd03HX8ok7a6VmuiF0oxmd+JZDhc6DFIWtW7I7Qum4GCnENm/UXk6JwMvImHIGgU5kiMZWzOWV0w==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
