---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgBypE4TSMTvEQCMFjPIrlUW4L/zzZLN/zB2XyZa09Vl2qChdPHOmNHAqp0gifftlwPM6C9dq60AUZkTZ8F38bqksVxtBEDdREY0tKTwQzj4Xu1CWdInFD/Tz0r6NUbI250ElWCkdTlKYEmTv/ZUTMoxitbNpP9410IlUG94GTVlHULZRhM07MpP9WtxZ/5ymCvr6pm5xV9+R0bDZ4PZXo/a5NIi1R+h2HQweSSHmQVMU8R2/VmJbAcqg30lyUL9a45V9HsVDj5UGZjqO4rFa4P38CYuQhupq9EOsb4Iqr5Wyh73pogmVXZqn1pycKfp+YwHCD3j6FyfHtSbmv39y5st3Yi++MGmPq0eN+5+cy0BtQVgYwK2h/+bCDD3B2mrLeb7UZY7vhSp9HKWK4YMTgFNn2MALWbaDN0EjTDMPmGcxU8M8AbRSGGZSVOAYqAbWKGCz6BuUa4MpD5IZxO2uhQijeLSwbFfcJMXpvA7yzF4uGbEglNUV/9LoLf76Z4rsnu2890ctrCTScrUFumxEJSroJpEqyoAIrRJEF2qPF7ANaB8/2b7pO1lx375QtDJnSkuZi04ZZj42vnhZtIvWIRKO5kljBKvKLZxuAnklcvUcq6wk6JrVbxWrgEdYXQjsGE3aNJLUVsCjqUJjeUTQmXskmcy0G/wJNjZ40nQV+6WlKFZqmy8YWJRuRx7JDZd8vY3ML2EKzffKw==
    username: AgBGotA0AeyUbnaxQOvDi1FgKMNqZeBO0TqIW7PS+YEInLT/GpKce8HuRaddDKfYAade8sS4BDBgPh2PvSjh118ky6uxyCqP45/93bXWezvicj/CiItmwUAsstjh+RQ417dIcEeOHiSU9vrDF/o3SOTiTIPmy4GTvdziLBYsVEC0uyD2+8+asY6RhvMgAl0gtndl/Tz2dDu+WQL+hX/3LL+laXttJaEt/TDTA6WDDS4hH7g7ts9GH6Rmzlq+KGx4DsFcYAxa1X0Jaw5cfB42lYuOLMQFguLeXYd98Ut2GNBkdfDoTsdnJUbyD80Ggp0Ob9x8LN1R5e5lMapub34imOxVY7R8POtz2uS5+Gt58tSRCwg8sN85Qlnjv/6hMU6qXjzPsiiNvqg+U3m/8BT0OFprDAVC5l15FIpPUrPF/1gBfxTZZteUTItPoYSxy3FVG5JXTGloMcY096wA2yG56YCO30vEVzBJxRFi2y8xRfcvqUOucUOLHjWXoyrgoHCwSdt7eElYZv66IEglbILXW8xJITnj4nQxsIkmw6yCH15y8ANJ+YE0sbg1cc7zYZ01f963FO7OuBGT6yVtjTKFAG7PcAigsLQJ1mNt5gucYOWSMHUKPiDWpD2L2cHIM06DDMxWNzNI0uk/yqbQPavXN1xTuAemyqiE2viFDlctTaFXRKfvKQRZtpAWe2ffnDMAv2Ro60Z6Bt5STA==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
