---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
  annotations:
    # Reflector: Auto-replicate to staging namespace
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "staging"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "staging"
spec:
  encryptedData:
    google_client_id: AgAriY8DMQWgnj1U/RxTo8ixLoencvz8Nmps9uh6Lf1+To255tL6XXhJSMSLvrmgDCaZdgB35op+FWoGphwJ0AapGTiXxRJIN4m+4ldoEjm5mAG+TgZmz6DJEOdq3yiMzANuJL6wCpevN5IRFEj5P6txUBh4/ndeswDtbuoFtMSyjrqZT0TTScQSSAgVbuK8ge38eV+XyIeVmYWFsOLfH/k99zxLGRC0HRum+oQs0COonQ9wjTIop6UErc+AoIEaYZcPrIuBiaJNiNF9SsxD52mki9nHUeglEvYCOMtPl2YmO/ZGujAdIpApHHC3sZcfZosgmjrdxbRI+bIgosI9xaIs0bd97WRmDZdD7hK0oWF+L3UrKUOTWwvgjOR/ed7iSlMOcTJQq2OWz2LKNSwFrG+/faclH+9/tspujLyrI90HtV0vqqSI0qaV4oRWwRRHXMokVQzyqsAiXNlD7F+POX3MYmgJVNubbs94xSORcrCcNuuhSr82FsiUeB6fMjSqIZDD8kv+Cy9nYYzrIkuPmGmzH614Wy2Gr9YPgEhfPXiEwFHGbMEK4xYZEbGwXRDt9xM+IJhCPUzKkSxkfYkX+C0SUKhmv2RWSeMnc8NpuHELPp3jhH+m4WDdPERP81tGnCPG4MQleSVXx3HTvOwTSVTgZeCYz18lW59JE/cQ4g69W6jidRD8/Uk2oTPK5xYqZeBVusnll9SthVqrhQy/LHgRCGZ0TI+ygzNWf3JsJL+llYV5lot79uZWrjxPQI7hNIHM5hDfUTIz5d5mcXI0rAUPegimIslSRgM=
    google_client_secret: AgADsAYP+udJXqkvSlirjukDqRxyVL8x2KwwpG4Dq43ZwBVJvGe8Iv3lvkuS6ynsjMszIP6fbxOojzVcGGlRWkZwVRZnTC1Uzbkisy8C4BqGtxXtX4vRfPdHCUKKqgbLZ5Sc1waHlofL857NV+gbfzjrQMd28AoF3/P05Q1Ixw7QvXHk5nhTDn+k+ieKd1iWu1s2JBwRM5Ktfi/1izViSDhlo+cVhwvS5lhcz8uoZ5SVyTlXVQ/EBDla2UBUo+3P3lH07603bzBARWZXecFRCOC3yCIJxNeWzIktlGh/+emp+CmYNT6waxqJq05bUMopnoCQ9KyVibWtRP4LjAaqIMNqDAQ3Sbf7EkBlmbeJC4WIxSaRyEx+7WyVmejyiFk6Z5c9/98lrzP9OS0/6MSQx4JFinqQeM7SbT42rg9wW0xQxJe0HtmzUsxA4Qkh09fjhA8P0Ap6lgDQZuRgLpJVzy76bPsTpVKXJhtpmTqBLWPKdGOa6zYQ8HS4CKVsdq6QJkxh9eqmIXh64PLTAkgyBxGfRl9Ly0v+8eadL94fVsMSUxJIv0HZxhYtcxpJiTJD/4Xh7ZwDZB9AK0NBrW3WXNakzJkLd/aSJaeXvfRGln4bMR3AxeZ4mCTcPzGdpQYrarM06gtQLTxqwvds45kji7WouUJ8u9QUps4Lm0hJKqIXX2K5+f92Dvx4btMThO2ZpqGYnO8EndU+NcgesZvwu4D2+cxcFsP3RfIW3Wsl+XU/0AgnOQ==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
