---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgBRxvXUKxH5Jy0cltQV/IcjA1HUotL0PodYCZpIj+v+nx6sdsMlEqP/0/z5VtC406YqPXhqexV6BdTZLh6THVUX6XrFPNh6CHKqUm3cE2nnaj7BUPuKTqJJwV75CDWFb+gaNgHDUOAUXItIohWPhe1w0e1kzyTtHxDUMOmUEkHcHe7yIHEjT7wMnWjgn1Umxma6BK7swqDK37PWNp/GuGO24K5vvGWLFnXbBCsSiQPT2t9FRpVy7wY29wl6GmIqFqZ+XadWPvsPPJR2e/IhSfeFFzPD9rqjiqQhSYftMoRsR5x63FvuGtLfbyekRQliqqtqZVbKNHaYG6Gz/TJhfqAVdB663ibs8mK5t8EzgBr8Zf8ex08nqprY8wX2bFmH8yCJMnWXRPyjUXLHG+PoFYRMiXwDXPRl+dI/x8Dcvp5oSjx9VRaCuhjRwMqlTN1pkiKuHKatm3FK/GyCmGraLYwaaYqbGbaJvv4KHyGb/1Io2FoaBlaLHryWAjexk1qeB4MDlL6kiraJYNgc91Z0Hdj3owhh714wZ9bNZzO4UwhdtogWifdelx2rGoHy/D9ciVPGJJzZtQ2IGCNPMeRTgMbJgjsqaKmnnB9We5A/GJcY/pPXWCl//5x0QYVXPMIuLDFfgE3+t5KWd9qYoLgEu0FYV17rJFnfJ375H0g+3YenFe4CZrwu86WpopfeQBI8zxRgpLeszdJsG9apMk3P0Lg16S/e5MRCwvG7GQrUAlyk5xVlYZSaUlSXJnj5wQ==
    username: AgBXyS0DouqKnTY4Blj5zhiFHLMS/yIAkOdKbkblntjMHATR0glrLGXq4a81OTlmBoPfAwVN59pdoJBUwHYj7IVchc9Axk7qvhjWYNGIIg6JKu/c6jmGOSidiBhcRd6tSRcxjLFby8AV9Zi9Gpl7D58JZRh+aylFbgyr6IlIIxIvXUTZT8KJAXVs1Y1dR6c/b5upifBeaRQvvC9E9I4OmCCltua1r3K6qboCjNgX5q8+NCZeJi27BOtB3zMDBIDWdKuPjVjdl7HaPq6mX9/FmMw3hKaZENeMlYuz7h984qSPcL8FhUDxrR0bv2PCdNh95Vl3BXt3HI/OaJA6mGU7AlnC2VeqfdH/BdE4DeKRC+5qOsfyveIhj0R9I/3RfSs3nmvHuTTCQkxlUYqhuF3sLICXokd6IMDVEOvVgHKUjr2AXlcuIaDZ88aEEYkPI+CGA6Cz+H31WOHDl4uBTpnKcpeNjH5ROTVek81ds+XM18MCk1TP9HWFV6ih82tv51FqOO0THCNDDDMIVeIaJYE4Cai4YjRgYOE3b2B1Icghok8XHhsnQjNaCjf3g9bZ/MHyreHjLzSFUdVbUJmp1dmw9Oc6FegrXrHpf1iTSJtAkpXU59Ce89Cs9Y5ho1TmrHjunY57ZzS8xqGwEbsb0ka/66M93shJxdKFZjzpcmqpQQKX+c9UkjRx5JDnqpFjStSkpN/WPeUbrwM1QQ==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
