---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgC5UWImvDOZtn8YQMYlDrXTaUmo+6XHILiWXJmjOxAEVWeWbMN85j0KsQOd15C3+wC/bb+EfoaMJyMOzFUlaDTdfMC0BQjCv0ZHp8kU9BefbOuEd/xnsqkIGDGeDYek7w44A6p88IwIk+D3EYCMvFOay9xynml0TdX64fTBojQQYlAoDaxs8yU8yljW1HMzi7jSh57v0a82uWYvX/rAqQrVv/sF+Qo8OFTNifGj0FjU+xoHjSIc2KseFp79KWjIuMY5wqkuZ5cVkXXT0RxJ5uFw+GLW5U1lZO/nqWslW00mlxsSq7alEjBVpL0n7/7eIirUGYwFQ3yhbXMR2W6Wg4M26ueLZZZ+b1BtUabEXi95UA8eZhmeq9F0OClYjIXIrLBcQblwMoUqGB1Eq53HPlTXpa0JcxjxVDyOLhXAV6/ZAC8lLs1RikxRdFDFr7AXqaVI82rJ3KIspCsJ2DEqlqO6GYAOwdeT4JqYDHA8O3pjrjjYL87/XGDfF4ClqFGgOIB92iPvjq9vXbZy2cd5qVcw37Y7N/4yz0vSeXcI8qdFWPB2OQNvZfOTjUC/fc2LOFk0EVhYKvJjVSN+ClkqclSuDyhdMYFcEZf5LVjvvGs4h/E/RGOns/nBXFhUjaOO0K/HdylaAUiYPpIiSVKvol5OWkgUQCfjlx4qlxllBhjKAwWN9ousvM/p34WcTrZFJymUm9d5P6ZFD7ZmbDBUJqljMUaA4+5JXQEePLr643uBK4RkLc8yZFl+6LweNg==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
