---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgBo+NsnbvGR5E/XC/xiYIhCX+0/hHS4/b40p6nb/2gzwK+HeDltXxDjM6FGHPKXVQKvGImlOngnq0+AOnbYfDXnT/LahksWuVIjgrPSqabwHO6QlY8EDz4/pMDonPfXblmxGD9LCSXC/C/i9maOpBut5LmZdXFkQGnuN9m3C+vIghO+8lviDZtrgTDnPTjRBb3YxNNKso994afafcTvXArCLrsyIEeCKILdMc0mgeC7yoBZbp8SnBMvo/+VfPXc3JL0AksGd/wh1TpEJbCje4FkL5hIJ3kdyNZlvm6thOtp/u1zT3K7xV6ZTNtx9rDaHyNTXvKigeIpieSwy/yf9c3YtZRb89QQnuiWsew/JDvVI/7pxJG8AX8QTNS6l4cOj+rQh5E9Xqbd7biCcuWGS69oTiJd+Cw9GIcrXmD0/omAYVBSqFprLbpEA83wHGj/92jiMNwFfDzcA+3BZnOp4CB++U3GeOxd1T9sGCncTeqJBmao/8/wB3mf1+t6upB9SGlTDBk/lUyfGRSAAHV38AU+S/uARdXgcSYeZa8gAHI3Y6gPi4VMho5HCAmgQzFGF6gVYFnD14ZjLWP5InR6P2vbsUF8ianjf6hcGwgpRS4qHrATTNN2gsOcVCvus+C7wL9h7Sht52/4pjJXEG24KuWOLgqkwg9h20dn82znSRnqGvBjbGsc39WqYslWAPj6RL+TeEjCNjXLa7KihMJIo4F/bgVr9V2lmRebN4Dek9hxsam8mPQfLPgsPbxR5g==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
