---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgA2GGraTZjfH5PqLu+Rmu3Cz2dMbP+y0EzfO4hQ+qohWxPIMttbBBzdhHry5ctMI9rFBZ0ouNklznVqBMGNnyDm+DZ+h5cyeW8BkVwt4X+x71q6I/miNmMejNuGsIMMMjIcdtx8MR5lXJkhm2sFIxBrBGq4B6TAq2FojdSaic7fL4fBXZfPIZrxH7SkiV9yJr8IgcIfBtFGj5vKf0RGWpBMpYTqi4yRiJBAHyIeFF+o6ThKzS4T4qtX99g4oeBrxDRWmRMd0xGtfPZ4DgXNFKu1SmFpnsoIzY4Vh0yeDV/04bDLpQFsNERjLcwvP1z31cLuvISH7jwBF0dgJK+5ZU8vGm1so4kvs5LdUs91njEhDjAqAfqrbzpkqA01fv/njXng8wnBY9yh08fL1JI3nqbz78PYXjGSf+G9aVj+D1EuIjkDP1T+IUMew6KH017QDuUMdNAeYWymc7OxBoGtjxgn8G+yPv08hF/yO86WkTbtgN9wJpmol40n9CuVxQ+Xg/IZeEKR5k/L4P4Gcv7mUfTp00CmBmhDzHj4WwuhBn8AYeGdHkBAaRGmZ5DDuR0L8gTW2HWsugyWE6l5KrxhTdSOVpi4li/hVJav/EMi81w7FfGGe9eGzNNLCtviv9Vthqo/xIkDgMJcwG1rW+S266sbBhIk2vlC56JqL+3E8RHsiXyemObqTma6gXdgpaP1Oh3S/Q0Vg2A4vFaMG5fMSmen/rk4sl/bL7HiOuuL1o9Tfo/qve/fzGUtIXDOrinUSIdHHxmSTyxkij5qccPQzfSOD32JtmZp70I=
    google_client_secret: AgBHWLXKr0CQwOC65iYiakrGIR/bELp8jEaHz99QyeK2VVGLuF1giiMkKg6CPP04wXQ07t8u0VmLvNpgemZNJjTDqtDc+fN8472L8dsMRmsHxdFiWmk30FSfHLuRk7qpq9WgITsIyYyNPT8twKyO0AeUwht9l7HfMxE1wc8BLWabGn/oqXWOUqOYPsfdzRXJUZa+Fhnv3Uyfz6DlescNdWOhc6ms+BeW8L6igoPE2hLiafqWHkAif+XF5zGyWISXiCKK47Jvc8qPLYcrLxJ/jZHJmv8Mtn0y0RFnc6Jjk+/MVTPBhg3TwcNROyKVPF4l5QNpKrjBfudtme1aqQ4E4AH3NhQA+V8IOsR4UYdP3faGWk8+xT8AgdiCBmst5NqgZRnIotP2jUOcx0ASsz8whrMi0AUE3YTm7iozId3X4w+fJviMJb+TwG0hXuKqmOL/Obb1Yo4RmYS7oezLALZX4IX4Nr6FRSnFe8L5dbOrm/84/F1XfeW0S7P6Y/2Cz/Nl9qp008yCVZZwlyYTa/lN7EyRrDCtBKRjbdGVh4YHMMkIWsvfQtbgYTClouiL8L6nAPfpKCWhfzaOJftSQoPRMVY99FYuXeQ8nA2LCJ7OMVgX7XruCEEz45Hybn83nuxUUH9Zsn/b+N3EgXNrMpVt86UnqiLOGRPAU7cdTiaeHOOsOzSXeLvEwFzDWxTKBEAodfLX/V9xs3KZCQBiudA9FnmYjvi22/j+ZGBTQ++jwRng9/DRug==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
