---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgCG+VDoSda5cKT1m44VQPpJ+GzRsRL8+5zvr5XaVrF6lsmeN5Bjg4IcfbN9Sb/COQjek64W/S8b7RvoN7MhTsk4K4WL8myB+sIx3TUcUvFeOjgL/X3nccvobJu57STwa8jduThXG0Yiybl4Pp8l6dy//w2A2nlbkfNmMSRONCFCAYAs1I+rpCVneYoRt5eGesmghHOuR98HTMkj0A3rPRBVY4Hp+06YbzgySXSUQaPd+yK8+Zsp/A/brtbl+oW1ZUKFRR6vfFiR5X5S9FAQrUjz68RrEE4xhHM4JiOmMtJOV/trd04FXeGpUb3qHwi8vFokoJZe+DvNldqFPBjkwOmbcq0zpVWe2t/HEREC6X7EYzplhQSxyCzd8GEcbFmxYtirfG5UP6IBR3Rz7Wa8Xftioawo13cYYwYnvrqu+97bOfwhr8vD3Ai1NYhyRoO+fxztvNGm/KZp193cyUYwACDweqwQxYM+cI7xozrzG/wzLC1WH5agEIoRLvDzXTAnk53zDY/1drsKXtWeq3vn25S8TOgSZHNP9SuEXLOTwKdwFrxwLBj57Bk9T5H8DoqgLInFG4Xy++ob3MeXtnJHFt0GpbfLY727j4caPGA3GBYYS5a8EXPieNtoX8NvqlhbQMTBmIzQVSpmSUyczb5r3IXB+azNzdhUUC0vZbepCRUnFE+e6gu2xpC1YdQA7dISKKhHTAyxYu7eUfYso8JfbSu8ixiI7VmDyPvMnAmFQ2G4O8oOyzBfRhOTsU3KNw==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
