---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgDJHJSVMTzIl68D2l+zUeekoBPXXEEiwTb3nTDguYnyX4o48tkhNrWLBZTgwN4i3Hgq70izYkDZkjV54Hi+WSbuIb6V6lnkmdtieYgMbI3kTHCkS+l8QT+tOn7GoLjHrQ2GacGlpe+3m4qzlt+LxIwb5pvqpx2cV4TzktbBo2fMP9UBXmnp48oDmD1O8sVKj7TODt7US/uKLAj14sISqwgU950qFuqaQcMeGIZpzh0pOR7Ek3rUfH/X8Ch+a7VT0iP9+hbOXVWflxiJkeCymiND1y+0gzmlnrXMNi/OFLa+eK4EPfoqZ9M5Y9ue/OZPamb9eaaWLP7gIIiM/3GLhca/exmaNJ4VwXqld3tX4HpwoG8NLLM4ONqCXMtIlxYmNs5ysp+GabkL0PmYEOXh/lE/N4VVLSG5bOQ2uE7zKnZ1CUSawnyK0cC67E0NMTmbDM6Iu+0yMRYsgLOL1C5Wk9MjGgBql61CR/ZTvNMFxWYQ4hiGbEax9G3QxaY3hKm5PrCTA+oibhB3qtn+52PvVfOQDdLMB1rx2aCLDo6jVzBSy7h+zQopNgcTz3oTj+9yPCxZInce+jp/dpjCysBnNlkoBXM8bF8TYjWpFcjGRf3qI8tcRdNOLQfYAfe/fB157AMPp4zKAla9tzJwBdO/vwBtWBM6yhZT6UNpStnnDjdUtFHMHaidUiLnlhxdfWcjc/1my+O0KSA+96UxCMgoO6zNiEDm0n1AT5tKwTouLG8fH1QMubHwo5A7dBTN7g==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
