---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgAsZkRXeaegJ7WbJQn/XF/fiEmNglAG7wHGsVflQ/6Cij90qIT/bPrfdDgOnGnYnRSogQ6mDINTlESoCb1isK9NdYuccmryPIRVWUdvjgzJ+a4HUS7UkkwfZjqV8ds3Dhjvl+riUqo62iPFnw73KzKq59NPw8euzwDV+A748H22qffgDtSURD+Q7xYxgiUGzMHZyeCWAu3g91+jn5o+tIXFZG/eJeSTFsdxgx5cCBdkwIRTBfbBrkiwLBWzD/n0G/6Eh3/5VTos7ReLOWRXfaRqUizefLfRymJz/ycRpR5sTS7cF6OhjM9C8Ti6ci512qztYslFK9ki3gVmjxbPKxuiHAeNjiebbSiLDH0cYWB7tzvlmV0VOqcjyXAgwDddcqs38+L1ZUwjreX1RagNHsoWbQ163BZLXkuI8h6fF41lo2LdA25fTPoTKBnushgiFNNx66tR5e3+NCozGbek2KN9zCOSoRUQSxoCju2cmvDC+V+0P8T3jwb1MW8Z/3bo1FCOeimaeRL0G0IrEwncXcT6AHBm6Ndkij600NDvwgPu9Ea4LzwjcELegXzWg0X8BXvHousZm8uacsFa1Of0Hd13Sb4xAmlkaw7Fu/TzFAIaVleXqdFebyPCheFxOLRSNh84DpXVMvfisLmVEbwm2uwJbOBe6L/bHKUSLqvWWEtKOG4KfQVOV/1TT70hcPugfOcjctv/LAdhftZnzBDR95IzPbMLGzvRSqmYBXSIc3hrFEekQrhBKXF2lLAzRw==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
