---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgAvR7Jz8TY4kp4RfGVssVRMS1cPFsqBsVJapm6NC5GKVenIHRlcgB+349n0S9kCf9zwz8y4ApKLkKdc1YuGNxEk9Xfoto54VaKxDw/pLK1cbQz6GxuNDV6/00a7y3R32zqN4BWBFyCzzR7Xu5xIqal93sxaSx9JUmeHEM/WCwSAvEk9chY5zIKNnKRfyJkfQM0yS7aBBvgjDKfACMOC/4EwqhgBb5hdweDzjJ56wxcT/zxbTi9SYPRlsU51YiP3uPXLeXuRB8L/gDd6JKLVcHgir3Zs9IlgAh5ho6dk3+OVRnFaENyNyxEo2jNZpyU3MEy4g6sTWkNO2Imi9oaTfsW6WBZlzfVmRM+YPlobhb3BOnhyxbOB9O9EhPw/PohYm0KFWmQZKs4nV8H234jKPFaJVpAiovqB7q0oU0+2DcRH5sFTzJqmiraWvfUQjw7v4BCxGDtsuctNfSV9BTen1TVTjJzul3dFDQtdY3GEX14Bsvc1yTaVV0eeqRpUgMRjuzGBHBpObtB9B8QzxsUy5cQiC/r4N7j3TZNy8N2sxL3w9W7dqFpnbwtUemmCv8SGDUENhgQgJGlCfjOrCdlVKqUcd169uUA/vqMlPUmukEzUq15Vm0rZd51P4wpvifctNsQO20QzObuworxrCeAeXgWsbEUBdhSzpzSXWSxLn5OCBgY5lQUf6vagFdQnmUKm6yvyMPcaZpi6owe5OFj2ijReTpJVWNWxn8kMnPi8y2/2DXxklT9S06FNSPtEQoW2PX1HcZB+0QleYllPBp+/jGStBh24x+Zypu8=
    google_client_secret: AgAF84eQAa+NUmqjAfzORNT3n0WgnrQ9FhUmINAYYsVDC/u1M+ngn+BuLRkyylpXLUbWoYXurB2IjMdyq0Tfz4nRsapXRjW7KZCIGFuAwkXDuvl4irji5IG5iIB1JO/bawBcPEpErsP7jDQSf9EsxYC6aJHZXHfGF+2cTmaygQWd84nJSujvBImS6E1OmOkFPQrB/1tXa/1rBOoMgHsMRK3UvRCdi8qFGZf8hFtYzve6/i3YpY3p+g+CPaHKb9k2f7QDdaldhGhaRbiK3xpQEuj0DAKR/KlZD+hUtpQfVsN/zC2fB8IUZjZ741Bidrtle5/3I/cdCXXTPpiWuMXwlElfYUO0go3Tz4izC7puOt6ZA8gCcB6KFB10+bua4mzcpX9uaqJg7tbTfDdx90jU4vFtR7F6uvbXbC7COEKCUg8B8aCoTJpcM6tPi/BqwxsU6Mh/f1Ge9ytlOcl94WMdTenzDT+Xfnf/hUMNir551C6nZIOEmL4+ynMumSjbfuhgOFxHa1XQbiB5gBqn1knTvN4KwFnTjKZ2qZA4Xs9HQAX2AkjXrzJcs5vQeHOuRIQjs0q0PJpY66JonfXE6qQVvgZZLk1/unpgPPbRbyo1hDVJQW9u+cTJwdeWsUVaIoesVFBeG6cClksXtpECfrcr2mt/gP6W2hvtTHzQOC5/0QTHF5XhYy5zj2G49pRa/FgfuL/stj0f0j2Hb1HWHhCGgWJ569RFTPnR8EB9ZHvJBkwuteMLxA==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
