---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgAb/Tuu3p3UKYoiMUyeX/2qrJT88T2CgB0IazcMxPVoNPxCpPAoMrsBobqQpRPavtZQb/CpWQW+r7NmUqH7Stm5qlUvgIyQ9b10ZXdqA87UNzFNqw+RGR6nYUF3/G2jmQGkUjYSv28bxYg/t1/6eo6m6yCzq6ojsKzNJRcLzzR4qZyZdq0uXdhajtcmn5E3WTsVqW0k19toN9GeHQYbIyqiMzuXcPpXs0rYNt5fsJ1+E0RRrKClmciZHQ3rZdpIRE50Hu+8XjssbYXAoomyeoxDF5u2XCx8dpqv3mE/DHQ4cZVUE/8BzJrXaGDToRG23A4ECBP9ob/a4NHfmMI2griUOth/gvO6/rSWH/OE+DQgD0N1bPHLaIZxII7WDs3A6hPjHxObmJyPOjKQQNql18/68Hz3qcOkCkVqU9OUxKBl9hEk2AJBgzqY1QzFXtdafIVXLx6V1AQT5eUnGWZCNbjlWDFOd7fTswuYf+yeCDvN8QVbbY+3X0O+nB7hoSP9JUt7qT90knAfpq9LyiKlQChawrXzDTzboYE9YzMITNpdROxagXg0q3bguYUcNZXAFKD7nq2RWoa5vNtcNsltQwJXv6ruh3BC7ibQBbRsZbq3xBoKaDr3pzxuh+jXhYWz/NYBUbEtMON+SBQ+rgy1nRDjf+b9b0huc63HEG9RqsBDMyogxgQVEf4EenAu4v2akyJLPe3Y9xroHCdKIviz9/zavhlkbPEECZ6VIs0HIifzZPjNQNk5LagtJDcDbw==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
