---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgBtsbC2yWHDg5lDTwR7N50gTLYAPkPMOEfEpzMeu7zqhuauvo3yhrETl7UlPcZ0LX9/453ihUMnrdQzhmoZksIS2pvyYl2DK3Svi1dJqxDLvVTFCr3Vb135NS2h7NeD7IhuYRVoIwL7hbaxzzWCSD6dcqrmb88xPPnBydz4PpWY+AdOo9YL8XYeTiqwFT0inX34hT6SKa2apWFw80JArI0gJNqqwXrHRQaEc6IAeWRv1ZPm1ULhBR/6DFJ4tGlGrHD4s1gNppRZAWK8UWwmcksWGE/JEGMCp0C+V6779YippCYoB48FNaqwh6UjYVzxCrftabIuPK8Me2qw1yfenx4T5WfIihJ5cSKE5veLRSZvdyaBb9r7mXkzu0yGjzIpFcFVhRrluRgCMRO1gdQosLGfs1gVhfgfNyRtr9z+076X03IYyREDLQYAVCQBf0IE38a3OvFDHPitkDfFhPsW3Z5gUscoORlS1LzOPTARP1/PVTQKxbK7lixdVsPXMp/rLDwy1j055hG1h2LLUhTs7nYjvUMhJ7qJrydT1zjP9RcnAM4hsRPrhe5qRSKabP/6A2aJq9ry8v6o+YWOScv94foRe41RDtKNiRENuWZ064Rw4ZItdImoT2QKmltrQ3Cl1f/uP/Ql3F0qJ0UqD75yX+99ZA+sUZJTOnSlyf7//LxpRcPDgAuG5FwbUawUxbDA749/iDlgExaEnA==
    username: AgDKUgMjs7Lk52IBNnUmP2bjW38tK+cxF6IjzoKmt0Gh2TEBLSIcTB9gMMlwLoVFT8fRoxH/neE+WEkdvYDZ0D9ZumR0l9Q6q1ikWEBbbKdWmyMfcjzWxNEGsjQXgomn+03W1+BGGrhWNwt2YUmMZMLQdmT3sJnVWb/aZ0GhmooAf20nTvPL7+UZYb0Cs8KmC5iKZZo1VF5q7tlMw2/4WdQ1B1rzJdxPveYu7DP0hE/cTGoeEt2sA/gZtP0BkcA0lLOzuM5okJloJBGFOilYNkExGloGYyCNf+lFx20EPBjUPOST764zQ3noVcqBkj35Wn4rTvY3REtxY8nGthmDh5xPMBIzm/0J5ihxN3PhZ9XlluEGa+B2mEOTJbp1J6/eYkBuVxiRVviSg4rO9AfBLfC88LwWfa5nB2XSjQr2CYLrFp7jqA5PDe3yn5FC7cjhLl5ZsPaAKBf1r+mpp/38Dct+dx55AAvNC6YEm5zgrpKiID7isKHYb25W7MeuqkjQKPkH843SoZhiw+3RMFEPrW69EZfLhR5GpeEkjOtvrcujtoaVjW7JjKgX83ehwniBaqpRoA4zY8aPZ+P75G5qaJCDKi1g5mSsGt1LrGf2Q5Wy1s99ZaRJU8DlaJ2+NQ6O5SLCRnj6Jwgy81CJ2onr5mqrdJcn8DrRd2yb0/QN1Yeo6+wbJAsQ3vAqcoPBR0GtL5Mhtl450mX0DQg=
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
