---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgACU3ca74ob7Puq6Iim29gXwoMA5xFuP7b2Mj+yLy7gJ1d3P+jJ5tUifIA5e0fAVfZlic/dxFvI50md6ijF7P/BBb9O1f9/yNerw/04d1sKQUuL20P8e7P0v3H87QTfFrh3Z6snbo7HsMcdhE+xEsQitVpBqYQPnJ4fi95DsP7qa9Hcl4pyYRfNFkcLH1nO07oBKATrxZn/zTyOlJuVmBKBXGhmx8h659Kr1DCdXwm62mHHBHY9mxg74clo9YVehrA84dzRlbZNQ2IeLr27XBsX7LUi8AmKS5WFYIf/4sDciklSlZfkmnEtBNepnxhLAPk+WujbFBilxe9AZMaXHqRHaml6xoFe9nJV+87p6QeB64UnYS4J28xoDrl2H6MT4kWa4yubFMCS1CajddSqvH6QHjCwu1qJwtTkEJyZDyaSsXzyzcIXE7Yr3ycDVCM/v4iDHXMvSkd7V44d0nLxvwqChr4gY5wrXcE7LyUCksmYPCcNKKnQHFO4HeAOh89rL/P/QzXPgKsAl/raieON4NgLsz28FtnbuM/YFqyMWwBfi02kx36lK+rVErvNor+bhF0n53TfpnozqEmI9Lmy8CQsSDb5QpMGzBMMzT3EphQmLblRhKn5RGJi4CaNM02eRNM1zDCKDdZS6rax9ABlzGJGb8njOvkw8Qu4Nm2idtv0Aoq1JCq18yoh1LlKXNhkl9fImF+E/mt+ger9IwfA63xEMat0toT/a4rCyg28bw0sqgIFR4wTHyzxIBf+SIoICnihaPbiAIpWXwZS+S6LpK8n2CONQz1pJw8=
    google_client_secret: AgCizzOy6OyiQwofYDLJcxZ7h1hClvFkMm4F8xWaRj+bJ/ih5X4dYyPOgnX7G6+Ql9LlOfDUgUfMFufINyffbHG18LSqZ3GGqFngjOTYpJdWdmrGpR9B653Zv8TqSo4DZnxA91aqYbrFC6e5O3fMjWC1CUiSla7ptW936M0SEKRycgjy5MKr9Rzy/f1FTjD6zUZ4DpqSqIMRAu+veqDXdmTQiM2R/oEYd5g/QISeEGus4J3zVZ9ZW7xKZQ7xX9QAAqnaiioEGmN15UrXeRogZtOZPEEX0SgWUr8V43lkQnTxtYAEWnohKPz3sS30pZfBrLZQGdg0wEDy/62FNWVk6StHZ0yvm9hd3ELNizSgAu8pKlr81D8qZ7GjX74H5ogsCPiblEZnoTmG+jsjEv6MRHvHJggr9Nep5+tZ1T7+BCPAt7OHcmlhh3TaQdu/sT/TG47p8ntCVxqLUYP2QwAL1seOLtPHFULnS6N/zfA/Mhg9uocrKoIBUQxyqfMZZqFEJ8uCZ7y9PS/J1E1seBi6ikMx+qvsebmBkLGhVmLxbl2Ek67DpwkPgZE9+Xh/Qc9ydguG8qt0BajqBEzjrWTRmlI7zF83fDzLMJ1V/Etu9WQtb0mN8aqObbicaQPdxsKTykhdC2Oz6GzXJBWmbgYg+e632KGEpOXHD8XLqSuk2OZB+ic2q3Z0DK0rvRQrEqioVCpH0y5AzG5Mb5FBGT+D091BdnoyibCv+rMp+fpRclVOEgevSQ==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
