---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgBZWLrA5KioGRp7/ZtvCvpsOXIvGzfTRpCIhgU+QHHPJbnJC5ptkuz9NQ7abO69+IpqSkO2YhBuI7DvrDy+GfmmA4R0PRp+ciWfgem/O1u+V6eL8WUU9TsMh849vKXOrdcKi5n9PpjFHM+fI5mDiFRDqD/QwblVBAA6H6lg3lxqjk8QfleJgmb7rdF+R1KEaOEpr5t15QrpdA+nRviZBYaG2NnPQ6oMrCDcitQAhCb+04qo9rtnSt1+i/K8iizRXCVQfVTs6grFw6tZYC1YtUNItyDbRU+ESEeeZJNstiop11g4iqvIhsWOu4UJkaJVdiHfZ0zKnsppwtBv2+zcU7zyXmCM4ZyZpQcjGCh8SVd7YW+sGYcDeRK4jK/Pgq7jSf1XBvNW4lEZ8x3cDpdKAuJ/k4Jd+iujLNIgXHeXJsdQ2I4kbsw8bowM/3YbNl8uZMZG9IAveND3f5Y0tIU+m7eg6LuWJ9CvqYL7J+CZNjVblMRN2bB35CWbdjin+tmT6FRLI+1Ogq4sM063LCQNPsptOe3KYJxaoJWf5utEWCiH8zrQr0ew/mwQ7VN2cKKkycx9uf987mXr/7peoWPYeiJaGxXq+7Ic1yQHQD9dPo3w4Kc4UwN01vPoLUMZdWz5tZohf70hWMY6fTwTcYQEAr8n40PfkT1esOS0ncncjg7J4UuXahobP1LBsujOfJ2HTUTkQucVq3TOn/e0SdqZ+L5FlYoSE1dc2MjM48J8P9gs2T/05UTe+xSkQoLsHg==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
