---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgB0RHtLlWIZ90FtJHlVErsyoQSgGEyBzwx7tPo51/xp9YksY32/OX+q2tqQJSlYqF3kiyPxwmZfLUUIT5iqeD3KUSE4T1DEd2MHsMj20DAMTdP3dvlsYPV1k4vD3ow8SCQWQ6NcmNgQ7Dg+N/Z8VsDz4TLVfX9YGUaPI3A2ffWQEsXcfsi9c500DeSS2jxDTGxafcQYcR2KmFA4hK8Zu/YwmzVni3NHIZteejcn5RnjYPIZ1uP3KQ6t+CoUiceT4UkJuT1QlNCjHWEu2YbYrbGSMDCAvV+BOPX0q+Rsa8pG34UN0QHEFLJYv7ipbmz3T9L1L9Z3gdhnCJE7Oi/pO5ItG1sMcA5QpL/dEUy8CzJN18DPVd4BLRZsSeiGVf3WTZJMXcMncvOiwcskEypjqmGiBQF+zBqSIYti4G0gs6ZoNugs50RatQ6uzoYRsLefFpdB1H20yCFndQjtK2CzC5nmjLIB1c6LcaWWFtGiNa1gl23G/uHRtCjBBYY2RPSwj7eT0yvpeJkdEiQBcXKPKOogg1JmqcrIyTMJVlDAFeF9CoQHfxsQrhehqTVjnvZmWkVtA7/ykgOUQAuqzoTIMYTRMSfIZFBJ1KGGAeop7UYryJtVOFnmCOrSM6rOqFj7akCIce5l6WbKmjIPWgh1lUqM7ouElmcGiOhfCc4QyTyqc5b3fKRAM4/sjSezm0RIHIxT5qKRelzq6g==
    username: AgCA+PmAfudTCucgsaCl2xGoYKQW5Mto1wTdLg8W4LorWzeqa9tYV7bLgw+8KSq1E2uT7+zKF6vWU6eba1Cx3JAgh+Iuq2gbiUyjzGntjAPMW2FZ5d3UBxC8JiLBxuwfi+n2YMmLCEAOU3IVkGgAedu5aXFesDglGpWEjY8Q5V38TvrmALsHQ4sZrbIh1KJQdJp+/M0AfB+PeB00Z+i1+b8ektPEuIaRiftY+MdLhx63mBa4ZZACC29Yg8f4SfI8dThHJ8qCM2TDSs62LrEhwbCtCVlkaXNrQihjMx9UWvzze2G8QVM4+X4b40OAt84aiqOzufF0/CAYvyaHEvqWdxbtGs4KUS2lCnHmBtwY27+c8htaBs238GaWf3OfrIvm4oTmNeFQwdsiJ7vtdiYJAVt2JgpBke8qNSnJFMaY+iL9hDW+rS84iGdCgTG3owI95V5bT2HYg0/IF0Stcaq8n5a+R73QeXCFwoM8boEhAsJkO4MFkHgLHfAiwX3Omg/qbTnAIsFk9IJ6D1JlC88XU+cH1rhbj0WsHWKggrypTWBUy0JyUVIpdK/AITybIXDciwCmryNJCWRmb2A8y4lX5wXok322Wq6oM1rvYpgt1q8tXD0RD4YVXQgbNcfG2YfEqaqwZOXA1oTacYfYadQ1fhe/Df1exN6W5f9pKQdB7g+kSeTLdqBNAkcCfeAcYAzD4muwWKAhLlUqtA==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
