---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgCXj84rZdDSLyc4Kj7td7SPEMv/U+2b6raTu1V70WmREzk2dTP/mTo20/bdPO1X7DEVUW/LWaQDfvCUlfz+xhFQ212Ky8dC7iAyIWGtmzl8vZC08hmqD2pr1nUTXzkGCT0ngDCK0+5WoTSb+6sCagsJazB4j+lRbmh5CNH0yPq4ojj4alk4k1ATA0s7Z2uEidXHE9kRHsPNwhEtLD3D+wg1KHn+PO7PQQGkMLutkHsea87cBTnVFWprdjpokMc/OKdYHl+qzHOk2c1lAP8gMUnGockvW9KonCuOt4Zt9QlCflrIBph/rD8sdrOE0w6cqpazrtu4UmXGXL1d49hzrEpH4vorgXVR00aG5uaLEL9lPZNXvy4ZW/I1MZRMZW4Hu3Wpc9WOSPV87+LzzSqyj6RWMkytlnOoTioBwAW6NSshcJB88S9LKHNqUtdIs51bANAxzT6yc41SXTFNLfEr45lAN86fUdCyKqLFwC3/BOUolF30W/bdFMqUNIYo0OAIIxP45du/czbpLQwAde2P7SMRV4Pa3uzMegDDRXwqgQWjwSULStRL/dOdJ5JWRuO3p50C94jyDinBZPcUwuK0tIr29GvXYmxnnVZEoQ1d3CSsHgkuOvgReGoLUORm7If2k1Z6YXIRuk48+Ho/6tFhTGow16fjW7rkPiuKzJNfW5PUj+WONtikg4n2EDlsBasPhWt1hXRzMkNqieiDurAdWRRX+9rouWQNOAx1/FTBfStYlafpYSkK8rUtwu1pQQ==
    username: AgBhaPSPXW5cpIwQRXDWgXwpA3MH5GFJx18gqGyGAxhyx6yoAPPdzHvpZGS8HrkItL+fXN2Oqlzq1VaQ4fAjajpbO8cfJa36793dJQkRG/BC8wQXdZBzfd4a6caHmOT3fKixXfzkeGEF0uqLyL7KyQJU8q4LKfHuNXZamsVV16DiSKH3BpIL6z7Wink/QDoyCaQ+opmBl+bFR7ZKlXarxFX/6oE/kyiLisYiYefSZPGgdjAymhJFYXIDt8acpFOyR2/iC/5N28NuhEmYj5wHaCPNM5bF9CF7G2t0roSatKFoAclxbDzVmUWaA/9MO5ydT3ZRt05d9ew9GN7zwgIVAgTSscgLi0/Xm4iTVe9lP2BPldrjqZN+n0r1QrogrWqiRIYv1VOTQGT4xvdCOKGPWqbBWZG2WVul1LxFDa29+84xAE+xACceFzJSbUim40c7glHomMFb8jLfFmcjKSwI/qyX6ZsDCYoMl2kh8ufMHLKqnUOVbRHRTXWMPGmXSfh5hIzNoHHvt+kttIQ+I3ibPRJSGgQF3Ms8d1NX1/ZysaUgs9G82XbzZPPxp9CPfGjjK/o+j0VKYcgELPGOXUquX5prtpqa1GLNUA6i5WfHz/74p750bw7dT8hYnpgJIrigOv0o6nMFWpdMbMEMwFppgvUKO4ONoHMuX4oBC8Vb5v8kmhC+HPCwsk7+Yzty7Fyj77Wzrnuv55xpDA==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
