---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgCwJBluXeE0n3KqFwN24Woon/WEFOPQQoqOvRG/TQNTnH9UIy8BhgSkpMXxLHYv1FSjMz04XLkb2m76qAR6Iq6M6KzgujA6ynnpbqonCOPUh1HjtCe0N8kfe7DNKJ5gWYK8Wyiy58MuRMjg8UwkA5opEicNjPCn9LDkXgue8NPN3bd4HnXhO18iqYsJTvhXBvF1sLMLv/PtXXQG1U8P3uCugIchLbX2ordOcqhpkKEusO5YkVKBLnGocR3qdmoDWirOsF8UE1M9hW3E7BREUqtKDzJaF98BSZ4NhYyrIlTlIVmxlxpDE4aZj1oKYxqjjR0UKpZXPyXjgveSPwJ65/00q2yOuIfa46U+BAM2+siC1X2dewqfsN5AfOvMNF1ArTNeYEhZFjrcdqBHWr8lWMDR2fdIK59fHa2Zk/o43Pgj9+NH3T6qs88Ub7B60lpW3QnxpN2bUSIY0s26pMI/PlkGdSNGRYOqEihEzN/n+hRJgBMIZ5q5blsHICdww4pFJxihjBLNV2nuB8y3icQvfFyYJyKuG4ylF4ldY+2/jlc2LEwSJKtN0pPtMfPXwKL5Vfzd1F5NqstWWPy6H+D6F2rJ2bMGVxTDma6us8sM8u9IbTVlAwPEUTuAfXmR8tiDThMX8s+MWJmll3kIrsW+YyGdea6c7MVz4hAsfif+G7VLmc0UlRIjN85OLUVMltotNqOIM4dq/DXUPrwnTxvK0BV9t6urPb70uDIkrWjObuNKkQobLsVuKTeA5p/QoA==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
