---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgBR6lBjb75miYcdf+Jhx+2zPn8590YypLs3S6xgTAiDx1m7xzXhNhlDIJi1J+pW8Ei74Qv6SKaGcvl2y1tkqK1G48I/W2dldnZmlorKXDz0tDWPws+lSpIMgILuS3aL+kmmBu99X91I3wQPN98CGGZxqi5Tc+tS+Fj7X9PVszbFkQt8ibRAZAlmxYUamcNFgpzlcIGT9q4SYxmzfTSEzuBkkXcC0zVlYVM7o5KAEQrdOuV6Nf5AGAm8xeiCh8rR9teVa1hB09Kv5TttWEg9tRLxJJfUWn/cOVLFuPTDO7wdKlfmryiXTVOrPpLg38IMg+0rQ2qcZrZekhRvyD+KxJjEGKg0CWc5NsYHWvXRX7Zs2IOiUrSOxeeJPX4hWHJW81Ubc7ve+MgeK7HTPnBDv6Qq/lThJsgKyb/z88Oq+AByKSSGNz5gcsNRil6A7i6PL4Qd3765cgSJU3NFIYOOLsRRyWqSOmYHC/lIZeNryvPJNAtW2o2/JrD2nnaPShO+fiIctITEN1T44iCvOhJZtOMdLAVSVNbE3pzMJJyBTHAJubBdei7kHCJDLdQGbNcO2+BHIhfY8BcI/VKeTeuR54/Hzi5r681OQRHM0LErx8QHOcT4JDM93brpSmz1rJDIgudd6we+cc6jNUhqleWBS8a/7rZB3aCH9LpUP3V5Qety4JGDHkn8VHkvzb3tNNcH5mTwiVkMZW0371IUnuf2kU+98uU6w5eZmJjsdpT9rKZ27QeDNbULRTHtrU53Qg==
    username: AgA3DngmwDwkyCkVrryBvUMMt2HhftIzyPDX5aPvt76jPGNVRRBBPvpWf2AcKeapXs1Di+MW+Di2I0VypdXmDA4AkUr4mlC559oIVrbj4RQpC6l5GBMQ/7EhDx7P3c1s+qmc2kOm/pZn3eORdahi7IYFxfFwGVSMjUdcKbTdbyH1kFWQR1nVRB/QIqDSyVdD5XtegxTywV3ycD7uN1d9XdWzB9W9MtilvsztTmtEMfFh3zg6KCTY1p3l3+VaL0qyvczUqTAM4E+s3ACJMUdG9gejkfhnubIYrv/ILR29Yyd71fI3qdLAJl47I53D2HxV5J/8gN3KqFaNjj77HcP6z4C9HaViyeuj527IbbWiJlgbucfleXK1XPEKy8bL4caVOew50VWQWEaTnB7ubPvBaJkTF+e9/JmsdANt/NrxJ/FI4HN5GeNAUj8PRFw2IiANxGijnJ0Ef+FbgbMX29ZYPKxX4OY0yfDiROKoS2xsUGohuRjwhqD69/oA6T8X59Zt1wW8ZS8xN9xjNBKu+06DYz2vUsuxaPzpU4GJAmZRtsSmp2haIF2lbLf3ppJUihEipW8Zn1z0/1Rcd/u/ylb0OiYK4EofGnunFxWgAvEaDI2Z0S/5o9woZP7SucfzSzvLrwN4q1JOBBAmrX86yfBOB6+YRDW4qaFXnddciSn9VC1PoDuplgLPeht/9xhG591N6KdkBxR9LDgayA==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
