---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgBDSUTcrrVSS3n2T0nTHjpbFNtzixrglax768P7dL8jTO8HrEUh3Vzz12Kxxea1yqnynSJ0YX8KdU9VQgYsEMk2sJAxyD8B6EN29+iyRN0rnoWKzroBJObFoghv17GTs5Uvi9K4CoqQD3p4j9NcGDh+dgsSILmRl9BZvpTOd7bwDpsv9Cl8/ZRosLS6jh+JI0hVlUwuaaKJykJHavrZWliwf0/zpXySQq0rNIbSaIGJ1Tp61dJbaNyhEYqBFsZFyHoTjfyleB9sy2PyQKG8aCp2RdHmDv+qTizRiIVDgCpI4bHOfLJMC4PktKRCStAAz5u3erN2gxBMu3wxygWj6Y7TekB1qbvPdB0+AnT0CqbVnmhNXDtCaMfep5DqXED0Sj98tByM/aMf+IGkMgvjDq7mBrgmgidACzil8QxTKSaHsoGo8lNJWC+hQGwWdPtUnxGaQ5rx6wojQSNduYDHEfyM4dmzI+RQNkDMcR/AXgQytwz78T/3IVhIz8cXPMqHMGvipSoMBPzm14lG/DgQbCg1J7pC+TEY3jMP18QlAo09ZkiKXoHtIuPUvjopGFlJVSPAWbsEaY9qTKmP2sGGWDblSj3gKUIBQ1rn7wWBfl6DeQfpkiMxh4Fp7yLNVn2Dz70NQ72qJIRUUFfoQplp4nwQR73LSeYH5FNUtWuOIBb3rdwx6mL3+z2LnVayOzdJJT7UURbWlgdsOLrMNL4KQJmUkPG1HJ8uEWHGruhMSETp61IuHG2AKRSI5j/SvuQRlwzL+lowA2zP7fIgdbVnvUa2gyBwEAIBhG0=
    google_client_secret: AgAGx102w4Y6c1VliZxOBxmo19sNn7J5KG5NOXxy4AFarkGeYQaAI9skqs961OOB2j9DACRFp4L/q9/R6mZ9nd/tO+zJ5VJF3/tz2doP5kGTbClN3rb/2EV/yjcLq5fqmt+q+ACRB0y1EBJ3riet+61yTIvhOWHayEWZ15V3dYtAwAHeXG4aLIWOY+Lv9DiZxtEKa74EBJp0lBzMKuxiF7InTmpt7SGwXsmv1xyMJZ4puMhKmkgZcDsDbQPODIQYGKni8Yh2iPRZARve9tv0yQQ6vfsGWRCYbJs8+0HfrElai85RfJYyBhe8Ttlnnm1uuVAFR7S65BnVM4VrlmxEJaG3SM2d3n4sPGVEC+TmqUiYf5//+RJAOPg+owCI4U0C39vxWlu7+lm5SbP+LLs281zwQcmEUX593qjIqmSsIj7xfJkDiZ+EGrw5DCAJsudHiVQOa0po5xbGjakDJzpAyrVBspDv3vXZNdaSTA5JIUgXrMJYvKQyE2sLXMePw+vGZtOcRPxqn1nGDXw1k+ExpTXGq2YSFmiTF+q4TDpJEzRqY7ZFoDpgllK7YrHRk0D9v6cG29XlQlQQrDOvc83TDSyFfTXXd6RKmdKBBbhwGSdobKmYyb6D8BLaOj8oRj7isDwcH3SHFg8aKdf6nGFKOW22Y451U2KfeL4h5coa6MsVFYbh3ZGOz8DgSN87d3lEH5x71+1o+3M6z7hcgtL2Uj86Hj/i5lb8qOUsZcsbIhOjwh5iPA==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
