---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgBcAv4zx4jbyesrD/ZnwUi1T8QPblDGISYUpGCCXq1lMGtKCU7X8Xg7/qF4Dq7jNbLfRv4fkuYqw2zBThORwa9rgvDGh7e117lvDOcIAuNvGR4MiQTAZMANDJC42i3lNqTJxFqZ+8c7Bj92m4YZKTwfquUBm8HmKSXG01/bx+ARLp46P/XlqcPQWHnYGyFCfiQJlyyXqM5hA2bG9m51ivdwu6rW/NQzij3O8eUdQ031cTgTTcAm65+K6DzOdyxgojIaFPts5ylzcKoLkxjhnQCg5b77mfPh612olNpSI1nrSO+qTLdk22EZygR4Jj3MOJ9Bb+6RvGXciLuP7PCbFiycncstL2RLh5x88GWG7gjM4NeOOa8Yja03cd5rIV83DCAm0/2Ow0YORMnt30gWf+uEw1bpfJskfG5cGUp+tvLyz1wZb7rjfsVG3mPwXzEyWusiEH3wxX5GeRq9NtMJY+MMR5++dcTEDa0ymRhkY0AabCkCmJNMtK2x9S0Ru86qAgf+fx45935vTQ5gdz6NUyrvxbkmP4C93tDkk4iNCw32PbFj9kVw7IO4yTwHbWLmzH3hgTScd6gHZOqyxk24hFzFiKcwQHFyc9HtekJQpdqaB1gvJvNX1CUrmdFnvhWu+qs82nWECOtTBLkRIi5RuSdHUbuj3f3h7xTAbYBDxtFVaAbcceb8v+3vv4tizEg9G1ix+/LXEuZdzw==
    username: AgBXFDnocUkz/tpjvciyWPKn7dEk90vEB7C3xbcuRvHHDkg+sfN/1DsIHsVaxOaGRUj6mw07ExqK35qxZSe29TxSAcPSXIaXoiWJRqbLSrM3IfWU09a1MEcljpJLfVer6zshprjNaXjY5at+KKrfW7riWrVZVu9/QfL8K9cKzdUopWjm1uYKhq6QeMKnCEZ4Z1xeC2HqZqIawvw3GkCKNwfxMAd4wsqX+JK16cIk7vcOOdiBvQQkebNm8UcxqixUI4QsXhhOKB0DtDPO8O5BrC5yNCKdlv64xI9eRFUQ1iVai1qxgEd+p2AKjfxf3GmHeyb1nJH5GA/6GtYvwwhpZP25N0Xqzf4k+rBX89Pkx91bP2rTa/iVrraVs6ZkD+MBXxmrPP7J3JkMoD0dy/PTunnJ2aBUz7VkD9ilLOsz6FLZfwBUxVj6X/KA5ih0ArNYwItJGc0DbLWZzOAG0neUFmdhhQIXjVcqPCJl+w8smTRnD55IZ1uJ+cQUQ1bPdT1HNlrRgsxOhDa9DrDnwkwzUCk1WisFAEGn5mb2Ghd51YsZyKITf2d7SRmpkRgoaDRunL3xcbUlekUVfzo23iTaIumQvz1o2osZ0qBSiRknkK0s52hguSH0/PpqC74KHDnczUPjv02M31iSL9UACK5hKhyx14ONlnVtugeb9hFsv7729LJnlRcP8aCa/vLmzw8jpchfOrpAe6FNMGE=
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
