---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgAIX9eXgJARWmDVYq5Rb8s4jHK/7Ik+TStf+OKRnFUO8/BCXwV8Xlu30gQ/m6bbA4pl/j5z2aUpfGOtgXyInLtaSuEGbFA5Zr/xUzlxeq8oEpiv22Lv9TgDBSnmbC4Phsij9ruuJy67T4ylskjGskyrLGBX/c5pMq84tVNuE20PBcl+hIZrGfKBVk+hSlnxs9wUXdQG16fbzZij55Pbe9+MxTCTKOicpWYNStEWJ52J+lYFVv2kEL+YYBsOnphh/lUB62VonJ+a9H+2BQ7l/ff5e9hu1OLQy5lQ9A/9aYKsDBXc5yVktX09ywjeNm4NijH3Kcm9aVvJom/Dz0UpE7oIJOvTQh1R0NfLGj0SSYBjf/ldfE2uwr8n7of6rdMN8oawJll96Ni8zsWqo1e2asqXI/u8F+YWMwd4N+h73A7GdXmlgwmt5dicbufoK80626vgGiduX5VAvwwQNO6NDjqxy4A+0HQhwfgziVaaT/xU21FdiMH/DgWMjdQi1Z9574SB6JVyOvOdIxa/zwSGRbZHeaMkBG44EVA9KMYT4rU8EKDSxS+7iNa4LsbCoROABjWDB60Ag1V7Q12nUzRkboULLD5WJxpAUNHZ/sgPMPHhSsmbSkkXQksHmwIRfZUAfNvnMomsDlidGmdndz+CgNj3rHFhqUXvEylzdLnl3+J0XTQp2InWSHlB2zj3ktBUAgCgsiqo7hA/mWpnNyLzf6sFOwOWf92SqF+IrUCHcGo3CY6QGg3F7GnGU6hgm3MC2Sypzs3j048ba3NAV52G9AcGcpVrj29nny8=
    google_client_secret: AgCFpBPtzpI4HbpbGuRTOf07zZHkFfEPK5Sku6XFgwaghg8bIKiWUxNdrn4F7nNU9aedwH/gIZgU6J8Vz9O2ojPCp+ZbPx/Ddr53mFwxwD447ypmmsummM2+jHUplegcTIcyngBq61XtQXnGVFfymgJfOD41JuJc9WrarZGRK89cXOgx6i30V4jj+EDiRJ9oHxUH7O1jmbn6U04YpT7t/nTtTx8ZJX28PTsLBenKBRA4/76FNewMhS6VyIRxPNLfL/2Rn00V9qqgS6YSyinOdhm33UF0SuaFUrLIeGx+KdKd7FWyN/MbiSOvMEYQTQjWpjDqK1FYBFsXd1ZLOmiCfVQ9nz5VglbRxSrkU0+JEb8/vzas9uTWXGkF/fvODrU01xLzPdliNKROmiU0YhpldFldb/wOIg+jttUKLJ2momWZEWaip58YnzEcx0M5iBf1ONja2WMMVNZYN6APekAuluq4PAKr3PiDcPJdeuQuUY9NiNW0GirzGF35oW9Tx3edE9SNeNpW8Mc+hhNEyWUSkFxO0PkzZFEIiZccds4utEl2bPIOcCDB0qObrXt3/Qbmn1l4XoLyk0r3qCjLFQp3EskUKjjEmzYOy0ait7M+DF9XO3kuD8FcUJXcg+8TA7Ae/AmJyV7S1XpgTSuguKfRCyUbxiyaoLyTY63+uMIBfvybbeQNGOfpd6gS8EwhqOVPhs7r4JU100Lyk8/0oLQEjQoOY4268ALZkCSTreuVnuIYq0p8Hw==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
