---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-app
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgBWfsUjKmmRuBvKIotkmimQMMeeTg/BgxafcfFburyDZRvTuRSCltGPSDTIhWsOkvr4L9TOUAe5Ef9gfHOngHCbDEKY3lXiggl8f63AIKligm9Z1qWjiQghWUWXFY84VoyFe5EfcOolIcNmIYDd5SFoITFJxPVwWgUZr7xpQdJgBUVXuJyQvGiE6j09colrgKGfFG1Plwa5JLQU8C+5S2GMKPKMYsRDEB6wGLNrehpyqfxQjVKqnkH+Ohra6tfDC3CpD62jBEj3MNW9uQOa1Tke+ihbKDdFIF1s8xFRqLxRJANq67upp0YQRaxgBP74+mLqMNDw0u4tkOfy9psTad2AP2ofvW1cUj1K6TmC/uZSxs2jJy+3Xeu2rumjjGt+92JPyu84Y+zViQsQwdiI0p9TX2v5nF61/boZLqfhm8UNzTxlkp+fDnVmQ3g2gURzGJwmCQZ0JtIZffBjvpJtfBixMLrf83v6K9thpSZl5ZiBU7/yMdETVM0hwN+lDRZk0tDblox9Z9ZPam20o+zR2HemPAJonpM/aokp0r3PP+OBldzSLLA3smXjZc+Jl5c9OOws9q8T+XXIQb9UJ6s2SZUETuSCOrMNcUYu++7If6OnMa3wh2swyhbGL4Y2M28G7jhqcUtdnCvUIRxhXq8kmFrbOy0HbKAc1J6PSOlmz1X/c0lCH4oeOYLsr8yF6nLDGzrtajUWNxqraA==
    username: AgBoSahIphItCeiZEpEQPO0k6WATE+gCtUo+x+FlOpzkbe04Yh+AAYcjwTKhEaGxzasDqkMmUcvDzao7WD0pSA71Qwfrsho+l9anrA6eep7e2jQy83/aDQ3hTMY9WKIsfeGVsuTymS57w3n4UYmhV8OOUURCYb+I1VsOfALsm9neXHOtN95EXwygttJhtw8ofqIeFrkYThxPFPiNDT8cyEG6b2kCXiIjRjHORHwsvOs053PjkeRSKnaUT97kRGayJVtI8FhfdhzFtffxMN7DpYQVwfMZpBaYyuxr7FMMYwqdjM4DhW8M3nZ2NhJNhrT4qex3QVbaekIvEFZdYZDagjteEjFA6q5a7DriYbxKIp1hJ/mQ6Ifz8Mz7fRgiyKTAggHec/u7vja8+RXDyoKUEmfHE22CTMUHC+pEffeCRvpLAxYsrZ48HdlsQtPdNvcAGcP86dfxtdJBQFgEu2HTndI7iWUnIk4JakfZ9RSte05Edhi0NGueE6aOI2Oiuh+yThUAaQmukXduIt+Z9Q/P6HnRFOcEYStj/W3A59k2UpK8k/AssQ7UkR7cwqw42fZ947fxF+x5vbm+jMTJ45GhIj5oIO0fTE1PNiuQyXOygGdroALU+ObAQJLsc4mfpC3siixhIOItrJrPYl8aBS1TBgn5SwdRUB3evdzg/H/UmpzfOO9/mBksk1TWwb9Xef+r5ltVFCSqNX7PRSk=
  template:
    metadata:
      name: database-app
      namespace: keycloak-system
    type: Opaque
