---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-app
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgAtdD4mU+yPgNpUS27sfpvrRel3tBXRydBl/v8mWrYUGe/Kr9i5Z9ncnnk/oeqY3bt9QfXKizzvKn74nBZj9AZ0r4GT+Hig4VhMCYYxjaHhuFQC7E5E+MHJF94IO0+IIiIg38Qu+xxwASXDAJM/TMLgiP9s7hbmM7PqEHdAXUGYlw5fgLA07nvJzV5jFUdmtxeu99n6Mu5uGgeAlFDW+KqR+DV8kvD+r5ivZ720wGR86PBFrR2aDxtqsEwTSz0L8wlGxqcStGOYZwdWRojH5gdGKYgFwz+p9yDOmuV9NwscMYRr6bfryCJQ6t5fIYULiPCeowKkapTiZDA3sLrYQ08DNZF4RwmmLRdanJmBvDsUhREkHeZQnNxuh5yrsuz+aYk3MJzVwcJp0KlKhnpQf7GAbc1LtXD3g9bwynLXwjOKhjiCQL/5o6qJyl7wZEB+0KdGo2dReHy45EsbBoZ5+Zz2PwNk1TwYOXVXRrDZAloUEsx6AjfCRVbg/zBS6qMrISc+WEfoeTiVfa4a1oysvyzP6Xq91IdImSqsFS/NU5650IYzGFgb4wCp0E3WBR+rZrl87EiVWXq2eoRxTDLL528qsdtte/4glKMDoP0cY3XHeM814r9duTAFCOkJEtzeecB6AOMvpO7X+Sx6EspFpbETRTg4jsmV/fnMwAAkY1Q7UQgXYA488kayP/4twSSb4BgXjxzD9jzcEw==
    username: AgCB+hn2IYy1PE8dPvxFxDKcWfhnek/azitL5V8mSBTfqsWEQv57vj68gNEWLqpyeOno+fSm7gczvrjbEy6aGc63Twt+FVbGIOSQNYUkZKtIHSqWd3v1dxbiWNuVn5VPXNmlJkVb18GD5wMUeipvqNvx6Wi3ZfSvQ5oGqI7TkbdK8CmSP6TYgc8G90i+FcyvuZThDKBoD/tDA2D2Y2iT02iFi2luf1tYIGmK4XT47Pf1dRlMyZYgt4d5DoNcyYm1ucQgMDvFQJXzymJmWi0flC8eIbTPMkObB4tPxU1Hoa5lzRqQORtLiisN9NCtSuPQ/LLXn3M4o6BIRjmjIIRtaT5R5uNmpWBO8vMj2PUxI+Ff/Pq5UOk+4VPUbqDIXru58uTU6eFBO4jkC+AZaP1GDGuu1p7amoVGB0rz0D8aH2ovww48ZvPw8az5kVETbs3ju+LQdDT6LGVO3xRG/Qe/RlwONupYrBRBkSjLc88WvLQulrHUOn3j83P4yGYhf9r6rW51MENld20JO+CCKxuYgWG9FS74HqV68TBlkoxXCECwht7QauPd0QtAgJtxQnoQwCJzE3YZanBIXbL+YOoklry46OUSmYkuYpZk/5U9Xqu3VP2rF75GwNrMBchjOX1kyshVH7Y+nQJnMUcGDhRy1sskapUORUjFrZQzFZtLQLrQywtVAhgJnTsC1RlYihOFUAjldiYwbCwsqL4=
  template:
    metadata:
      name: database-app
      namespace: keycloak-system
    type: Opaque
