---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgCK9ksCXTgRwPaQ6k6wLizn54JgD7zZShEmT/Aayk/HKHB1cu3zsiC515FdX8CEHh/qhQvuUaic7tQyTe7nCxxTQ5H1oxamKGuy2JPZi+YKydEM5tgzh23pVufFXhnPABE7EkXhGcRx+U1F4rH6z3KA1ReNxftrhswafzDj6mF2JZSLwU+vIa3w9iWBzYAwcDEcWKC4PsGiDtOG+LKoUtL/qxJHo09N/hM8+ByZzjpsX0yHBx//y5cuG/+5EHxscOx1AvhdT7srS9W5nNyG9TEKe8hE1OAVz5lCUbG3UdEFMsI1v2L+oWoV+FxWB4L39r1MAob2DZCswWG+yvrymCA99Xq59iKtXwLxrAudPECibGkV5+5UQHZ4cfOqTqXy4T00iuRfgZSasemq4qi/CFbJsvObiumaf7WNoOFp0CN3mpkwFYtHLL/41UT258Z7hPe09VExOrYPFoF3H8JLcqBzjeh06oXsQD2mk7SuDTkwFItfTTDo7Uq34sWZKb2AJGbsuXZ7NbddiknzYM7PoN9yHfxjJ+uLq0HM9TYuXKgyBa6RXvNWOsGZwQz/1iEjT3sZj9Ap05DhZAcEw3Czni8dmLBqnKEKjn7NBZzuZAudu4iHvP0CM3YteA7449eyksAQJ1fOOUNT+2Q9dGOq+e3d2czarwtKn20GwosvZj49k6j4JCy0eX6tO5P+y6p2UhzZUp5faIFTyOwBzL4PgyheljmaKDj1gt1/D8vet9Yaw95OzpCb4c/T5fElxA==
    username: AgAGjRgAibZhwKm5sJbEIRhHTPpTtLx04xqKDXn3QS7VomDzEyya5euNfwjigV10Tk2J7fU9WWNwNJQdYTq0X5eBNOTn8LwxLZkp6rMH7wXsPsxApywc5oawVlYpcXPH4d3Bhp2FvWFTrGHsLcHdaiiSD8lMmLb57PMxNQQivHjuh1uQpQPUazOs+mrBArLlUrECkWKJsn4d5k/APi7gWwmXElXbkv7ucGM/35eOL0xAAg+Z4wjytfXIgGQeLXMlS7yAkWPbYrJf982IHedjH1dilhAwfkgG0igdq2TJS+EmU/bum12dYkD4gMNfOl8t42ynUa9+hWKZX8D5YKf3EAWDGBmF1manVt0zlhGnAm0Dgf1Zcr/zEMuIZh+xqQ/Ny9Y9i88H0xBo/oroFRLNbENV7TwCe8thCTJTp/lMpmxR/1HtkMNGkZJZVePdSu/b1IJqbtGDNmQOMISEqdxmh3ECqAbWvgTlnqCpa2++4RbjVVwpz+MX6pvFR97Y4d5bXRvaX1TgdcQQhoaZ5hu/+F8XI4lk8nGcZxOHFzE6GizQ09/o4Cz8qXJI3oRhGOEmtZ9H4W33q0SmzSqx8GBcCh2fBVYRIBA4d6HEjMNSfiOqC2eKsDAp8VvCZbxaYVo1GttXmXhBFWAeHRJ6XlsjH0Fs2TwEYhKmkzIoclWLdsyAC4a9EfYn5IEXuCaS2gTn6nDGNytYGU4Hzw==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
