---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgBw+H2obxXgUoveSu8AuAllXY+HFocovvSuyzpwjg6keHVg6dee69L3rjS0djMjx/7dqPerAhEsOWVFZjRg8pgZEUKwr4lojY7pi3dmXWSkj3drGhbUCKJjSmxMct+l6NtFOplOj/Syviz5KTl9xbsNg2iC0s6so6OgZVMlEoZJD2JBWrtk3/N9WaDsVWvC6z2QSxBehoUDmdCFpN4Ii8OLirUjSSIiNqETz/ltQmjpzeOALw9CxajkqCFknPKVUVRYh09EtnWUG3WcM5kPMzli/IvLIMo7OCCXDeAHd15ig1N5oKB7VuAy2DG0zxozWn40BozXU0f+0q8t5CwxcOAXlq5jgE/dGsrvMUD6dn/rAoW8EVy6DVSQE36/MY+1meLWD0NSuEiYN1NGDvlf65ALvowxFuDgknHAjn2pKzkqLunV13gNBud/rPhCxjG3xY31fRXmTIgcOtTIXhXowM3/qqkSpIbbtJcw8k7w10755iODnFxlXRtdfx6ED0ZfvdNGK5OkCCqeNlkAsYpL0NFrLa2JjM0CMA49QAxBvhdwHXO7FfqA+vegqaSsnlvrUw5Qsdz2tHlhnDlhSQ8mlKLmeDXNAEoxFf6Vu14ewuC7QV9HSaR8BeINqUtX95sEMdR4k0uAC5lLxhNv5qa+U92JUcR/ksZzrvvWEflCgaW+SwkylPevyz7Rg1IeU4XphsT+3znNKjStUYInFjw3b+WXKJ5hpax0G8NC72EgKxHLkseX+SaUO7wxg/HQbQ==
    username: AgAsr5Tgz77vcgxHcqBf84jakcJf0BkDIIBETB9htpLhDRP0OLdyFxVEqJIOdnthcKT4MIdeSF26u86OpG7YiV9AM7zwUyZ9q9Q8EPepEwM1TqJYTrhUpN/rKveRrGq2hH3FTG1qJZqzYt/xQzzIItyEIN/S35LL2sm9odPssQf7Wu7S6RC/0labUc1d36MYmPfMBP2N10i3HAciXO5zK+gdad6IXeciS+nPezh0Nlybf/YCH6KImQHa0i78YJYgFZsAi6CWnVz06+HpsROuvgDItIE8M0GDYox+dlBhVHKSnNLOqD/pg50LiGijVmUsuSdJ3+knKaNb/rCTu0PHk2lTwYCeyh5lwmvRP6SuuLk8lCBJ/JePy1ZenG13IS3jjJZflbx2/36RYsQeTZ0k73LFSFGfV3naZt5xDZ3MF56gV23IFh/NHb3w7AKI7SUi5cdzm5ELP/1Y6VOmfSBeyFsCP89TQrCUFpgNcfhf7zM+WtcnR67Taloc/2PxDgfAk0OqFW5Lkl87IIg7Gyga2WWkBNORelc/73oSHlB1LA+2w6fIl8B8zy5mkhhKf/x/LxR7pS07CX82Muennso7tVr499lwixCSHaTcRYRvSW6OnnJ5Z9PnM1IKqiTSlvmcvZ6iZt0t4NvMEIPVovmLWtZjMu8A6YI4/d7qEi42qvrg2rahs1/BaYKiY/I2bTL/r3hZtNNH/iSm/Q==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
