---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgCtO1vGfVF+1LLxkMmksASrpgbeBrrEHXoavbQ+Czmi3NXg3YBzyIn6IBIfW7aFD9lbZF7MjoDEfDeecL5oEjzo8+dnFlIn/E6Hy0HSVzcT+l9Rdv6CYlsftmxCAoZdvbuyzs90H+WVQLhl+P0m7RmenZ746dTmK5Np4rWY0lGlBUnz0vzFThejC7lRj6IzInERxZDwM1xlfuZuoBCzst7xSL9w2pko+JlZ9oZgwD3ZGX98w4BBSbiCUaRt8Yylo6eHfVv1nft0MR4D0mYCfxe380R7R5nyEhEWt5qP++89SVwEKEJVtWFJR929xm3Biulh/DXPdSaOk133G40JlIUbLikUUwVCIxY1Uri6sjDLilOH+pfft0vibLKUL5xe64fv2gt+bICwFvFVAut81KcEeP758eimkGKJxz6B2PTR1Rgq5ccpwYb2xLR12jVY0f7UzHfg1yWnkPBF/QofLlnXkvvFtL+jkZ1JhCnjdZzwY3DZQdJ59wKrmo8F2xXtV6+0OlC1xOKwhwPTr8vJo0x2kEQP7ZdvYkg5ZBNp60ZJ3FZQ3fk2PKBGpF2wIGNgbKfm0lYcY6x1egA5orgowVDoWgz8nm8bXGZKWJgk8moR7pfItxg1YzN8rzgFv6eo4vsI1jrHkT/Yaok72yvnyg/Kz04LXQdHWKzhA/E5x3k31vDq0pQzV3PqogcgRcPVmxm8dlvbMYNCeO1I7efL+Qw7gn2V6pUyRXTZrfQ/lJa/SD2CLw61DmkFlh0PBg==
    username: AgC5RAWyZmkie1ObCaut6EKYvp9RK61tnUnkdlR/So2B2II8WwnMhYqf7l5aZXw22UdA/Mu99MOjlcDXtMMh52Y14kWpbBwUIyGdP18OgC4ZXcmQ3Gb4m+AFyel++Y7P+bYTGAWSzndjGrErhYMAbq85UaP8EEf7YZMSX8y1VHZnT/yz4RbvSlGAkQ2z1r5vdeTKD6BE1AKap0jc+VjAWj6l5Qs09RUUnVQLVqDwlAmyXpSAchjiMN2c6D5t9J++5+B972WLAK9hwfhPFXpxLtC2RXlSqYIdiux2+WoEIyEQaak7bUnIubidupXUwrXHl+uS1bHr/io+O/VR9vYfbnbrB6oZtr+TSB+v4k1o5wP5B8k55mm0xCh8I+QhvDOER5CMnHLbf8pftQUPDwzyGT+pD0ELttFM+4q3dWPnigPAJmTICZtTeOeaqziEgz0s2eIC1/JSC3yeJ3alDMNjH/UlZBglvJ3OVfz5bhRdLYaJTvA7ooIKhEH+Xq5dyuLVdmUFvmjtgkMtiQWOHDHVwI6jhj/71fi+bNR5kx7N1Kpno2EIRo6pdsKmpoEyxkgi2TbxTqAs4v7obEDmEdr0+LCKM12X71e33ZOZBGKPFT4xCdY1ReZfmxAqwFKcIWggtsm3ihF695Pig5YzYi9bII1MIBbVtEt9MEa8Fcbgsx5xldtjp67z185iuhDhQV50rlrzf4MjjFCIbQ==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
