---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgCp+KZGD5H37iqUVf4nNc/qD486UBa2tyOoGvP4734IXanhU2YayF/rJIx0n6Rad1M+lV4rcR2nlI3P6DxEhkLaofMS1NwW24VsAi2XmZms7ZCl6D/HQy8XbZLRVj10Sre0lx8lfURRDvUxrtewyWn1Jf/gifXgHN/gWo3gEqI0xw7V5mPGmBiqNM8EvV+Fm3AInnZYwZtVdWrCHeyWnTB3WI3efTjQkSurSTZDswVk4mYUv1qUiSNll4IAlH0FKrGSOCov5ieKZYHC2EMgSmzRYWwSV2VJrM5szF/raJnhzirbx5nKuRb3P31Mh3tsB1cwnOz8fSHZCErG//R+LwGpPABJ78i6x8xYCg2vtmITkF5VXCTQF4ScEcmQdABjgPo5qM8kG2Rn6bkjfx+kySNiygfNv2srNW5fAzZ+XIXvLq+3qixbaLZvxb9UelYOgq0naMYIh6Gk4xQGcD3NP1xIoaVxuBINtwILniMq7cxo4TvNmm0i/UK91CHcx7mba4DmwYYkO99Qq0g+a8FslAzjUWTiieHDADsuBQqcZqxyaJ4ShciYRVstIaUYACUQA2X+RgYpSPHjFQmb5DseJKrC5uQbP1egf5safW5amPZ6s2d39ggMsZHTcNXBhAjXFplPu+D9dw1sj9pufQ4a8VWZUyrkKYn5SOPVZRo8qStgElm8wETwtHkdl8BAYjnNuBYJRVf8bThbd7yrMldJJ4zyYLmYrh6xzJnrAzDPtdHBXfgFDiiCt4PLO5EOZA==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
