---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgC4bzsmAtCXi/s8Ia1f2CjAzLRuQUfLSh/CsE8u4O4kjN+9ZeT78pWr3q8cNdpp/v2007DzOKCsrPXVM6NN9HSV76qx5B5SPtPAJKkdX45wxr1350rKQmoawooSkYuXPV80E4LSwQ5UMwsedhtUDpnEdwCVorA86RhDTZBrJO0FkFDpHNb4P9wvI0ytQPotnYjqGfZKaQ8ZQ/QRubzfWgY3GIvh05F7VBPc/KFRI4AbfVLMhyN+/qTGBM1He6Bco6FiZqz8Z9+uMV2MLNl7/Iy3Xy7ENkJrpLY+1QvWYjaxXZ9X+YXjih137oQECa8XNEWMMpaJ5FkclnD1f5ZPStQuu7DxxJtfh5DUJEfhBe2/agkmkqX5rJ579ePFM8YkjNp6Mfct4+aIHel9DQnWT+XSsFLHG8nVbEPwe784pTYULySEF2In2P7QcmMgydvW5UtiT3jaRrwzH9pvquo0TOsWYWwZ55+UokU1NYKR06rusPBGe6g0T6tw+kVxpwm0rQF89GSfqc2KCAR6fcGiJn9I5GVFMUf00EMcfr3zJgFSbXO87tIOM9g3x2RYq0b6JKPjRNCs+l5yUtxTHoA6mvEuuMK2dIX4w/TrWFxBMUVCY+ey/RIL7eNfOIULt4+a4Zjo+HjCLts0WsQ1Lw8+pa94GFOztL4arXpc0h3EyJ63puKFeUcGIg5AUXzYGYpqcCLxTbjxIQ237aTInuAXaGv1mk7dG0LSdEa1LOECKzkC0OT+u4vHLjbCNy/j6G3Pm1HO0I4Gwe7/ooRV2dL0izmH
    username: AgBlyDYR5Uc+lVoeTqp3IRLrTSxxbuyyGnYKzf5Kv6jYrNsJk2jEAfY83IxJHPhV8VUV2idXcqDqQRhT6oiOQW3siG9iPHwFsBQpyGAUPKCZ3a2DR0NW16CJLH+TC3q9kpnjNVEfDFiMR3edY1ZC+Pcl1D1ABqCE99yRYYdLMhmdF4tSMrFyESUzajdsJA9gbemZdFkAlkASp/djqgFhbs0N/c6qQ2IUTaFgr7hO0A764TbdYZtPP1pfDcT4Umd88cYMNGc0GhxvCq4dIOIv7k9033T3ODgFJjxqJ3337+SkG5AOagp8qgFtVTYOvf/CcwgJTT4WYigK3lAnU/Nriqtuz6LHNYRtSzNK01oe4r/nqT2b5gqE57lTgPRGiH3sSu2sopUK5i0UP6iW2q2uzWV8yu5oBklaZJlxy+n+GSXT0dDDPH6nbISoitwZjEQtxRYrKYd84fifxVv1Uvri6jd/Wd1AH+yb5YXVCIbukguKAWjxriPKTISOMGqMfjgoWKK5mHb15bFmUXPlwXAwUNsn299KO7emTeMS5ZteVKTe/QUNnu5sXkVW3+YERwOC+laUfAYXA1JFYphdYGc1nzQsG/ZPp+RHHjnkiaSSPFMcuJax/ygzpgJclNGq8KmqrLBQ2+Bc/Mkrdz54zvou1KM1k6IgaRSBLNpXdo4PkvozDdXUhV1KiIUdSiiVjskzXeOEKnsEcmx+NAc=
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
