---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgB5xHkqt88BVgOdawKRawfQTgQ4yFH5x520NtOG5UlwiAmrhSrXBn8YHTsmiTX/rb6u9a1ZSj/ky7uw8nkp56YKRCQDI08tStpni18E8ecrr23SodFeTFt75SUBzW6cgA3ruY7EWvoN7IY2O58sERwHC/CN7yMDGhyUhGEpxgDv35/A/Rvn8yMSeFux9bK5iBjgZk+tPXzaQUAWgr3rOvdmoKrgIJvuUoNEVbXUXQ07AHParuOpaH7U5Hhe65wWioEQSxk5ji8EOJcK7S9fLLLuVq4Y6MzO4lQb/vdU+dI494m1hFNfX47QTCRuzOSKqpmSg9Xn8NyFgGRmRgKmPPZLhfWC+oVr5L+CNswMQoXhFF1D2PdS5shJ2WcYL0yNCDsDOpIqUPmfWaMxJa75esqCZhvn97Uj22yN21bp1de4BMzpkGQxNhKIlXLd2CGA2cvc0GBWfbVZfN5buaxJqVqf8BZoE6BSKmJ/6XkviRdpX3FfrWOJykxO3SjPssinOS24WNJeXMjp6+i8hBqGl+0zyN9PiMAkJv22VVYtR86TsngFF86RDfk3TCPyPuLTvyyUn6wFDWpj7lhW2HZlVxtN2e4c9ZKegabRNPjCPCE+w4aYGrnplcuUdPKoEbULvC1ocEp0vkTj0kz6IR0ELNgI7ROeM6tPk2QUBNZ7Xk86KNjwtPxs6wH2/jH69zt9sr+PlWeeo/msDbAOFfo7NK0LgoTlolX1lhTyFbm0wLKl5hKqjoJoqijN+LyKZA==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
