---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgB2hHT7SccmXCniwNr5gjVRPjJy8H1WgsoxtkccE6uN8dIYeJOTpbvSlPaqUaN1Dy2ahGjxjGiwSQZnTTSNBcGkly4AwouhNwB1+FQugVVhFV7QQ0aHXmMciXoADAmmcllYL1WaGLwauxgOp/uuDqf5HoZoAMPLEdU8d5k0x/7MnKllpKhyWlUZOvixTlJhiliYrHfbujg82LurWA9fTjbM+iFY546zYjuatfQDky9vJRVCmp9inCqYrTlP5urGFVjxQxHoEeFSdAERE9x1ihujcPzJxLPjXy5okmzlQxAx6KhRrUuSMVbyy6jyHOclCFNFs9PVonwgEdnqHlpIqKWNbZcDUJywcWZTtjzMt50xPaoOPWaNZh5wtdjjK+anQjGQihLx3jA2sQDXcO2S5yz9COlqDLSGkQm8QWtoPhJTMeUrc7ouCw/2OP+QQs9/Gd+jgt6Rb/fVb2t9nNrv79+S3EeFNfLZwfVqjTNzB+ap6N6xAT2Uh1818QAz65UQJmC/VqeHKsTbXriT64hlbYjeWQg5hA65IAxElLamvq2MISa9UrAH2CYrOhcy8gZaXAsN36UcDIhqbtrMSGKP99qNyxaQlWYMIelLR9NHDDtLzqOR6eCAKqSmHT+dY5SqrsgTGLzddrvAtnLOJ/IunXQm1ikh6UPXBtMlZIsYnnO6YvqPf49RwuDVYOYNJj2hAnMhxvpKQGEIMW1Z6ZYxiYOkWg==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
