---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgCM7Qc1VKxI0YggQxaFwAUFs3nH0oAKCSt5ubJaeVJCNt3Urc42PU9M7ASkDAevqh2+t9nYYZdcSPib0oEHOw8neRRowubqGg2CtUTLp/XNx/0802vlwfsMXyKNP3IwVItYdh3l3DmEes8tye2Y5+znvDdMnBa/+yWFLAwKJaPHytK/QMzALZcLEvxBsEBWBRHcoyE8IGyoAHnr6o+bo5rELz3c8Jrwr6witrxh48K62mk9WIaTjpfv2b/CvLbpqbsrJzTatRRjrrOhJHovQeQR0RnSfXmXKS/bgjWUj3eLmf/rlUy9DC0VpiX0seTKgZMNi2SilosiD62JCZ1rNV8asm12X48WsAjnJgSLTw5zK0arcUWKM3MjZlW6M8zwouvH2BS8Q7tbLd9VlNwLugVxonpD2GkH2Vc+216ytJlhT+c9U1Aj+IgVl4PA37SPLOXnSpAtDMZ1BVJWM3LgTE97TnwIZt0Ohmlyn00JMjOD2efZfXEw5GxFU9XkYKzHi62lt2Azy9L2W1BvqQvL/OnOvDr/I0G4uutnS6wjFhVr2Eo/bZ5GIdW4KmUAyuf6dxSZ7sgZlDO5eBL0pVa1xv5fkkNo1TYm1e3vXLuU8SJbSFbmOQGnhtEclU0Sx5xGqrt+Tzqpunu+jTO0BbjEV6PDEc/53U8vosZMYcs/dDeIjPqTbhfO/mQHxW31qT2W8bVfjHwMsf76V2svoWBoqL5xHp2jUO1uv7aOwyzLuGVS5khiTllOEDufnG/Smg==
    username: AgCHSONCAJEyuHzECiC2KsN0WorcFKbrBZt+TkiZN6cWxjt1Hkc0fxNgpdSXeJio+C1e/KAwB754goLfGIolVd7T0ymnbK5CG0PLtAOdKzW7m1UPXTY2PO7CcmJ2NfAfzrrUWwFRpaU0pGOtFqWmGdTTn6rA45/ywyq8Xiww/Kl1sjXPzz1yt1VokPIFG8hxeDQK0sStg8YJec8w5onsGQkx6AwUocES2qHynN2ZB0Kmy54OIFuGrrHc3DX17h9egm/DxkxXk+mJ1sjifTtBF0tpjfnJMBVE7tGjePuPTcs//7zWr6DPrQqWbmrUgwZbtwvyC/GyuGnbAeOUvFnJeyKySo7KV3hgSwek02LSut9Xkuq+DGfHMpBYIga9VeU0z4VsRBHHOMzt/ph5lVObtPDn59D3LwvckLnpgWo9/qtRwgSmsPwd+K2Kamtxs7fD3NXth4q4at2pXn78iFdR0bStrErgXLNmcTVlAxWw3/gjEKMqqdoksMNxYA59dJv0LdaEms6eVLeQ1W+XicOTUEzFEEY6+rXJkBU+oodtz6b1fz0P7OBUjy6Rz2R9MqCuqqCAEk7ZUHqgsW8BgTBvFqJtK9hkku2YQWMAB3YTBTjFNMLD4UiRF31EfRrTLIdXeIzew2SidoC8LcxRdum4Y7Y33OrUzqV/kRH5iVWdFjJ1XK4giAb14NHCrk2ilblV23TRPuhMeZkrzg==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
