---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgAbLl89fS/P5jfpFAcN4cYQt5u2O9QRN9MF4bAazsYNYSbxtiB+v5tnJPDyPQEImTvhizT/hnZjBh+SSc2UrKG49CnpNVNvdkAj8kSDUKsAbiM04xd1zzv0RC48jv0sNsQAF8Z93sUcMSAnOiqqwj0seVTZSXLQLTmkgPPkCDPtOhIYDfcwPy3hxlEbmx7TjEMWSASBaoK1bM+oeyjHlfiYT4EG42ytE1z3y8Ti9MpjRdMshJE8Cw/rDsE4iVfqCMmVtpTy27+yOdC3N2RE95XgznY3uK/bS8r1aQtq2+n0goy8Kr+x+JJZzugzM3c/mCSlzs9fY//Qbqjdjv6EsCIbAvPBjSKJflLloFSAYBPIvMkFh3Do58S2/lGYHlwPEMU9BMkh39l9WjPNPFOnex2dE+FyfORB9lvn6xGjTyzpfIPNelg0Z5vXhJ5s/XGEEwkXC8BtC4sIUQ8NRcYdo5y8qaCoZj8Ehq4E1EhYTsAncaCR+8sZIHDXjF5jx4k2wz7Ewu3M4003KEyQ3T+JBpVXgxWB4SSxq10WZEZQOc5we3nFcuTqlZ5LgJXtsnOefBXvH7tdDoJ5xX3zihxR9vI/h2XVAhrDpoymrc8oRBF6HZmR+raeIdkwLF8/oO8VDRnMNfrBwJZQe6pL+K9Uypk/ZAhS1giDb1Q8jh+KaEViIVtDwNF9NaaOPlvs9APpjMHmG2rP3m/HMrLGBKqo3M+76lmTiLhCgN1oDcqfpO41nsw4O6CbxvkEQynSnrDTZ10W9Cg9Fb45Q20LbvJw/zbnNqtyboiFP4o=
    google_client_secret: AgAFUYZmPZr7gfNDmy7sgzTWvFE6pRu4srqFAxKALrKj0vZz2Hbr1H2LMDPumrnDND1ylR1PMqhq8jCV9WPXpa8QfApZ/HQhmgggHBzDNKicryBAYGhv3rT0N6+nWVGceE6NZOkeZ89kcU1lmqPws2PH4rHUWK5HBObzQP3G4nfptmaobxtdnVEkHHrDebwN3DfO6Uf1rvGBfajrNMGetDrjVIf+gb3P2jhgwipXVzMm3qK35G4WVwxGdvRN/Yf6srunlECqlvvtj7dtZP/YQKWXMfauMP2CGOqfXM9HjMCs4K0GyBiY0eCzGU8nq0xN36NRxBIYh6O+RtzU9JKGrjkxjnLV3lkbVvcz8lH9EeEt/kLUFHjmqLOAug70FkgQpyPcmT/36kMLlVZ/HokFE2PKwsWlcuXzOoz4cod+2EUuEEHsCtNpk1kKzo13CYF6jttLISKaFufV0/u4uRi4sN/T5hOUeqBGUtupIZUpsrHeqIciMMFq0mMNfUeQMWq/q0z5Jl44COBiEqZb3EuoHCwcodAPiJNMD9naG9zRjGleo/MU4OL4gvH+zslwb0c8BZqb38HAF07MttGzuAWC6n7jNxlOCQ2hIoymhVp5s9tPkOhLPngVHzS7rCW6RXlQKstDv+MH3ab0rmu+Yq57AMfktVq/tE5pkKoTg5DMeq0rIxtOcYQumgVGnHbb9vrH872A4EV9iTdaFIWfKm8Wyeg4K+Zg0wLsaJIh8mUeNNa4DADkTg==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
