---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgCWM6sps+WUlCklRxrm813EasjJ8ENF+zzsqzDWkDc0o5mTi6qgkpiWT96snjZ2lKHHpOH1yVJ2j7XQK+t7lElw6RSPJ+mNcaiJsCAStAqQ21lxnDxQdj6nqVIK08hYj5IP6jpETwUoFXXyaXNQL6vGvgBfCJFbG7/Yve83gaY8o9I0pLJvFY0CKr2CGbZgeoCHczkF8bKuVpfL4UoeAPU1LBA3k/I++Ld61rV+g12nX256iz3Aw919WsLA3x2ap7NNxsZsi4yqhLsHKeU13fYbukGtxsjrxbLCesVSsx5dl2i7VZO67GA67DPZhuaE4zO5vuFGPwcApjjAnPGyudTe8A3/HaL8B68Qj57B41doo+s1XlK3q6pRg8MIdJGGcjyQWrHcdt6d1Sb1TJhQqsMd9tSr6/Gxem6/LkhdXoQjJyKcXJU8EsjH7NjUEzCYucG9dsF7PYa75RwmpJj6uEoZ/w0C3XBvuCvhSZ70Ark8z1b6Rtq0Cc3zTRN46gNH4rr94aEHkkyi2Oy7pmwvkCyZ/do53u+vnwUmQJ1pdiVRB7RqqZs6BzA+QmpR2UFravV/YvoKLKp7o2gVrjt9+Q9cUfZsY+7mh1wW7dn4lZHSoHPs0uZySfhOEFCcsIFh7ANxQCyBucOoqHsaLnp56u5tJRelcC1Ja3fYfSdwQt8rszchildUNdbd6QyR+TobotpUW0j9nh9sDL8ozj2lsQfVEcoVU284vJBLEsbFPXLaIbI34g1Pd9pD3hEAqGZjfm1WQanM1SuX6gyskFSOutXm2cw1CzJYrvQ=
    google_client_secret: AgBn8mRMDFIHNljb8V82aBEaRjSkqYMhTiYWGKk0ZRvk5dHqNprl3JINAyK8YPkQkXgYonG225glu6DpIFx53SoDEn4fzFVgBoeoKoM5KyP6Kl3plcWaYnuHrQFj5Pn5Z8S8CVEzsurBEOAKsq7Nsrm6dQ86QZB3Ywwgn8y6UATYA059ykJ4nEgvjL2Rzk80kLUL+Bbi/EF1Z0Ve5glJndpMTK+KUhSAOf2jsRNsaA1HvXD0MoaB6VcnbN8LJy1JrVhIjBRFSgH5FCDrBigvhEE+w3hTY0dGp1MVSxHF9uByEY6XVE4UlJxb/xyUPVqCmgyH6YkZhwSFDFB2BIZyfpTldmtsGvELZ967kn164E33pUhMyzDQ2eI9NQDyueMTE3iXDdCemaLc5VSxen+aLSgF2P8V+ZALlVht9rHQH9Uc/JOJ1VNI1AMBPqZLUtn9ruW9mh/oP36vO4zpb+BzU2s/C5z3uYFxJDQE9CgA4t4Gxfc+c1N9SZoYWpA/VxoG264uqv0xYR53JWnHI/JqnsdDU/5o6bqe0KPG81c157Gnt5QJFXQRZe7iQueAdkJ3bYNvQyetXDA25ZdrNbkji+iJZRAJHzOM8rxPtBTzCE7UurDKDwRh8XVx9wAHoxU+957A8lPeIeAjNdG7ILvQoiFbUdZnTY9GXWprM0BUScoUwBkafd1AQmIbZXz3a7tny1wbG5zhqTV9b3LaR2jSHLaYkvjwe1hbsqCE8MSUl0MZTVHv2A==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
