---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-backend-service
  namespace: keycloak-system
spec:
  encryptedData:
    client_secret: AgBcCyI0giyqv3xkY4iB63k+4UCu0hjizwwecfK0LdNH3e7HswzbPiX+mdBz8RgZ20xbs8HEcn+iltKiCMRqmzDruq2wtkNHc6e+0lvHLFV0aEpp/wYq+CqiFxe5aYrJXHm6YKFppYpowWRK1XvlfuXKzIaabXvP34qvJXwBddmn5272WzmmLzjnSyxLtdD/h4NYyLIqxued4l9v7k7os0AiA5V/Npfl1Id5fhSpA5YZeWur44OU4Gvk8f1eRpZxHjJho5tpnYpwFJv6ozf6BxpCOne433vhpQh3TSRsKmLrsjtW1bLUQhm6R6UsKUnjf+NaZ9I8LbEoGpOvheba1zap1m2TpG26+8xp6T7trISjgYO7imuqAtip+rCSMUsm0QCFJfXHhVO26c2xi2rwNIYZK6WVWtJaUxFfcGVrvZp5FHnznVqyWXobtgBxIP/JWLsq5q4YQOY1or9gYZncxWyXmks6Q0fqK+Oa4r6xnobe46MninR4+7HrrMGS4fHvsnbHJrnyjajKeVMPswwITyphgx8M2/qmn3YSVaVuNpucXyGSjtaSkWMzXS8aecG1n9cReyOMjAuy6M4pwW6hkNRKrKmQWCAS5OsYjENJW9XNq7i1J2Bj1hwZnVCLoW5kmR8HIzkZUye2eJa08GlqzU7MfsZYeoBJfdRWJ/JHSBMpfRk+eU3ITEpCeUBAuI//QhZVWx6+qOCueimHPplHUCVUdqI3OV5468QByowDSNWPoGJ0E2fBJ8VwPY7e6Q==
  template:
    metadata:
      name: keycloak-backend-service
      namespace: keycloak-system
    type: Opaque
