---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    password: AgA2ikOohkZMVjpOt8rLhcsfLyttEpR9gc49J3dRs0mxuGudXckeoTxKXa1hYklNdTtbbfXvWUQ+hSHLnO0+tO3a5iH9t1fdDU38CBcjgR9duVbmZDsmVZPSJmFdJgLcekta0ACnJqotjftN/njpSqejGR0Br/KSttlPyk5sdVNmELdRkI4wE4BATdzgUCto8BRkk9ZDVgQXt6sAtbcA3BUTkzmrYi0FX3IJoc2VIFLlyMF/5Wu5VROHKrznp9jpIwFlrG0j11iaDtyGFVIeAhUIQtcrnZarsvqXha+3lT8LmtpJStJ9lloNiVyj4iLwZRi29OZmLzP2XoE86dBfYPAjU3zLRCmmoxloQNfEJR06ahwer5Tq0EV0Zmbvl1dGIRGEHOqtrj+cd49W/s0FktZ2Z1Md2mwBcGZTfU32H+FaDBzDKXXdiZCo6pAnLUkN6ZGzC/mcZWpmL7msI9zYp4jDnuGNPt9hnc3Hrdb+pzEhp+LRMQjsPHa0cmttUlAtXCGW8xZUpmj3ykztno0MVlN5q2CaBpVWM/MzwE5Njv40wbTjkaikrQVNjGd8nGtWB9nbLgqoCVKxuqBfqVVItRsFOTZudyJkXjV0Ur0ORGpHZ1OOslEYPWGMqgs4tqvoI0+Ma5YI2bnnmA6Q9vca4pRFKBWDDKVJjEd9UU14Mcs5jb8AE0Z3CqJ4XgpkacglwWw9Jto7/1orUoO9F1k7DpJKyWkzTNd2JYVFRHszzkI72gla8F3a0kjSEuPXKg==
    username: AgANwr2TnwoJ/gq4bckRhH+UWUGS/9zKLxlTTDUQkM9if5+bk8JUg7jeFuenFJf98VfWjYFjA1t5zmdYNO7rXhdinWTrZE7FDnh96dLDcG2DHVI4eUQyfa9HxOn8Dwc2tzqoIY1S4PmoAhivERxD+LV1z9O+kbEuswif0NaxLnvmKBr6G1mRt/r+gqvorz2WpmyVq6z8TgyudAzAnc+7Q3ILR03sJUZnIbhDOUd2I+tZJox/1cpJj18fVjo70Lv+wu6Bnv8HijMob2Lg6y+Hga18eyrcosPs0AZNeTBzPolbkQ7XBIdBEmHf6ag3sOTAqAeDfkwatrCVkAhL/v+T1Wpnssp4yJGE5+RnaKFxuZE4H5KhWP8qQOWvlSULMQHZV4PZLlNa+mYWII23pZe5rxnrHbREM0Rj84d22V1WzIJLLLU+TJfUdWlmwNKkOqZ3gr1hD6La0MKeX07saaLJoCaE8T7A2YxdudcmeZxkis5SiYP+N4U9XgHdMHvDnc4tahDBSGG8s67fKXyigPs+Rb+Z6/xldUTV6F/3/i8BRP8VvDCRttGJVGH9aKoil1gHck+bxeCQAJHNOAVn26cYCKqexsJnDtl65CS4dk51NB1bSeHGDPn6+enecM8Ebiej4NuvY0HDczQpeEfsbZlmb0nn/Kpc7IuNrUYA6O5yOkQjlberX4n5nE0bvcKRopnmtbl0LWqdENZdiQ==
  template:
    metadata:
      name: keycloak-db-credentials
      namespace: keycloak-system
    type: Opaque
