---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: keycloak-oauth-credentials
  namespace: keycloak-system
spec:
  encryptedData:
    google_client_id: AgBUmmxfmUAD9n31EobQAcNlXrDSQsiN1faco0hsg85hZiFJY8WatzSHN5wkkF/sSvpnKk4KzaKj59rn8YoRqOMBO54Uid1+PyVBRhUpxQ8+UgeAFi0IFLeCtwO74ufoLODB5042znBhWWsOs5faBA4gttwYyHMwDATD/tm7juos6+orSy1Ea5Er43oLx0Gg8NOVMJXP0B8bjrJd7ip5qdki/MTh9SVIrSLK/WOUBojlWOh3IHJR35aGD+QKaq/laVkXXATF/St8od2vBW/DKaWz8IRW8A6GV4tjKWdK9xnnQnsRbO+NmkDXkxUkKfU50+ZRVyaEXpldvdqFsb2n8gC8bXOgTN5yJ8bSbJLgkZ3/lWCeTihnHK0dK9rIo1waSe2xl94Sx8yw+dhQDrvijVpoudn8VQKP13crn/GWryxqCmmf8NvUWm4v1xbFUBvlzGZgN62R/psQl1G3muTkrlm0oDNU3tdRVJksww1Kg3LsmjthOS5ybk2nBgzTjbBOjX5kBsaCDeCiKOfCgZ+Qt59WDQImwRd0hIYVDSVaDK42EZmmRagmkjCHrd1Vj7R03xt577xmz4lBIEaqm8UGpSNt86JPd5Xq/+WoEPdxCmDqNvAEqqjSMrQjoMyJmN1asvlviHIyLd3UhYrYvt/ysTnPydUyvWoVBKW1JyxgrIBhtW//RRnahh2CtPKUNIlZVriW1KRpvSM5xtvZ7M8iXYcplC1Y11O7HAl6bDScW+G4oZAgL/iaiJwputYSCG8teX6uZrYkCB7e6GC6y5UdC0fPz23JCQSmbAs=
    google_client_secret: AgB+SvVnOQ0DufSm4eGLCQhoP3XPt0Z7FznNb57h+Bq+aK09gAJlGthoyH7gyBwO4iGq8IdJMEVNLt01gq6Dub5HtYDRR5vVxCERo6FAKZ5zhW0BdhopWLtczJuOVRqSoqI2y3VK4xSjXsqYEgzCqeoZn2lBx6E7KByufdjFggzLMoC4/eM/VD6VJDkzHEHAJLf4cxZfV5Cy5DgJNIqA1gfmvlT8zfdDaTxOqTQz8pF6lN0pSB17W6CsWlPTOs2xtDy9x8cAunq1OuFJOuClIxDfBOylrvM861Mip+46RlCOUkry/dFKVTzBmha7+f4y17JIVivdMbjWONWFCrMce/++ylMV98D+g+iGyVmoxrBdcLddv/N7ggKswykLR7Dr2T/CW+m020oYmtA5ddmhcRB5lLn1Xeg+4NksNiBU/mQXpufXjKG3KXVRgU/TlmD3AXWA+XqguArg0M406EsLgcLckBAoujY12OiWlICcXAlDeKHPNP2hOV6gtFtRuYftPZ3ZUXleuheacRYODKkC7EDWydF6kaj7iRvph/1evGWtXovRL1v7nkwjd4axTR5+VfWsHLbkW4WbZ/0/B51XuVNE05DvQpl+ajs4FrtOpi5YF9sb5hlE6MjudwdBckT0sgTwrlsKyb47Lzg5gYQoWZ7oh7cYCtZkLTR/oGkPOziriPQkM5yvowPMU1AIR9d1Z76OLloEqMu49tpLIq+UvHurnX8+YtHmKu81ykIPqlmYDbnGXQ==
  template:
    metadata:
      name: keycloak-oauth-credentials
      namespace: keycloak-system
    type: Opaque
