---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgAxcRweiFPq6S8Vqe9bhwUKL+1CYEueSQkedQh/eWkhAc+lqhi6fiwYDT99Gky3Lnu9COG7gVhrsDONf/IJKYrXN0fi3Wr3beIpaUGe1kLGLLAj+3DM9n/2p3UM8jWg9t3G+pDJqyIjp8Edtqfu+8ErAHUfsHHHr2KizkkXUCTUzPnOUJcqT85sK57OGkTt5f2FwoE2g6/H6nICsnhOOin2K8jvbFHGICKNKfD4tLPLK0EeCQ2mksDsjygV3vAVerQXVbXGkjN/1DNg9tfRrenGJYQ9l6zVXNWa4LdvBoAuw4Whwcf1yl5ebKEabHUFxpDLVK/T5BosY3n6LSLBaDibYah2tAr6OdF/Y1ROy6ux1rO7qKeMuJawb2nTekBvrgXDSDa+rkydBD9srcYgLNCW9e6fsKp5Ory2cYF8QzXvgf7eMeBjxUIJZVF8o1bxgcjuaqBApc1xP11HutPcKd1qEO6bWOV6LWt26sFJ86b4Qy12MFSMNNvGDeMStRsE3Mnl1OtUwJAsX4/bZ4I7KfS7lkpHvRHrjoac+UiOdnLFeG2iLNEaK+WI1oWd/oNqg5mNvEB9/6sQfaLNGU4U2NNKiCAP4eX0Y4Cpkp1cAlc1FvlS+HiOMURlIzLMH1Q6px3zckqfMQOmTQFze0DuL9+i6/UAZnTd/60xnTN+JKoGstgZQfYaKQqIWaz7os9BeEGaJ+p1aM+New==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
