---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgAyZg3dxK0E7sUuwkwnA1bl+eH/umbyEfqt6dnrdxL3vL1SbxUqh2CFQqF2RCxgqNPfXWRWHHGm/v2gEJTYHN02EySsI4cpas34+CVQUe0OzXXJSAXrhlOc5wdBDBkELGjwzJpj4ZC29nkzf/MB7+D0fPRc9IN23rTYyAq2sU7KN6GmacmzqyQ0xLZHh4azosVBTuOV5wFD/qSpbcmwUwMYZoQ64idywHS5l0OE62uL0K1k9DlQFpBzYMiGjzH+tGzutgHQgWLGd31MT2qUhuBjzosY9meo/BrI4cuQzjZw3h3kma0Byzuv4PEaAohiyPHhYyLYcnHTkXBcpdCfK16spOcIkFatGUrYKHG8FZZz3moNznxMjeEkjLYpalFMzH+XiddH6SJtRvsZH9JLHTA2IjJpr9Cy9pRrJrG79zGjzFQrfHA3DXMGy9HElfolExmaQXJryCDTGWifVmDZIXBdTQY8z2QMdDxfnU1rLqucIYqIFwU9xIUsdfllE7n5k67GF9ZljL4ZmBcUJMiAH9TAO5y7hWcxjV/YyZDUcmxdtfd8ZBlevSoQeOelkSGtt/4mM6njQZUmDQhTXp+y7IXpuXxnHpJQ6yXDKdJvXLkO4ZJQCtd64tMpQYD6LYgBOja8iVIsVYK3BG8tGgKUyyG6lwlVqovY+thIU/uyrE/VzAIux2DYA/xfWu91gfedrKrWBaJgefYMAKPbPgxK9Z2LtQjKylV5ghBthbgC1SE5/G2nWJlPhOtR8s/i0A==
    username: AgB7DxXIknnx5UY6vAOecVqIeDZ3vWCEH/zPXayFFTRIzdWov9Z35BgRNHlcrxWFJISVxvq1I0iXZE71Bt5zJ474h9sJadhjf2bAtgs1jAMtiHskVXO1aF6uQyZ7uwZF1S9lRokDop+dZohtiu7z3hh6zDOrnDpRTwIN+TjKKkn2OssOT+fMEHTjpsUIcuGPn5NWvR0OOHTskKysgXE/jNJR3ghXFArVL7nyeky35qaU7KZfvxAgbgamjp8GKiw+kD6UIKh1pxjQ3s+4PMT6CrBVkYQFs6xWjJyyHhQDZ2lbqxIe12gofiwJvH11CnL/FWzlAsrpAKMtQkryRiKWq2V4SkTsKnXe2QqcuGp6t1jxKMvWjZ8trMD3xBRGxPZtzGNN03cdxeiS2EV/qWhAdQqcor2DDG3ioOtuQxx6+U+hblSDy+C8qi18LeW1N/be6KR9Yl+VUbmZFoXeWMGsMFu3ZSM7eRvrrKFgOPrvyRRfpFxooFXz5HVw2RKBEdghUUXHYE61Ik7Lq1rB4Txw/VzYZTAoF/8fIzwsJRVJlntKJ7PtaFN9hXPmfUi6Xsu0zv/CPKaZ2NKOFXvEEWP6pmWbPWZTxNEC5wzpUP0uwgU0MOPOL/q8poOrJKKUEtJmWi4qteBWfzHEBjXLQb3iLP5uDBST7rTqOngJ1Hhu26CRDIECmq8PadEcZLAtrlQ+X4RdWplGx7IFdQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
