---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgDOqkK6aCOCwr7ljDJ/EoQyvX7bGsPticHwJptaMLfOgGEErRmdxuhLKKbtG82cvAcCHDaEMrtsZ75P8sc48CC4gZ4uc4DUBAd9U4iFyCbq/2NgiHl07+Wmha/Lp9Bpdcp94q8sh/fFiHIQlFTnC7VTitKaQptaRXH8cgdmzU6C4yIAn//uUPyB9j11uSUokHUJhu6psjRTTEYu1oJ/9luyOWJRZ92UMwvrk11PQSIx3yjgDho5Zuo5kSx9PYKcRmNoppjpz/XbeuIFPmwqjqT34nhHOJY7gJvAP5apAXyhNZA0rPRO7TD/2gTHEnVUvm+ziVcMxfRed11Tio6pECbngPQGyBZFo0QoeTqEzoBrJSdyr4sPEREvxSjRla/Ce6F5oXZeWOzLzhU2Yz5lJZwgtFYj5fDQOnbu5YOQVAOUMAAFPElBH97nsqpY3kGC1v3gy0DbW7e3SOV9NJUu+bLoJ+axwS7eroBTNG5tH6Kep97TOEegw2BV4TiLPFjB1Fdcu3EWkYiyACPuZJnRem8VMCF1sayg7PfKQmpi+Hc1/T0kQbt+S0tnlRRNn0a8FHd2VinXii3k5/X46daFYr2OWMk++0LNuHkyfj3bVYkN+yvzcEiiYRtb9bmP1fpaeT3udi2qRfqcqs/DKhyPw42ztkIc5FMSOPGQy4E2eBPwUm6M4TNZ0k5I7VCGeRF6aQ4VPBWrq7PesHhroTGejeW6fjvi3V4rpH6pCll81o93EsgA9JeR/LP1ApK1Ew==
    username: AgC7B/ea1wMLPXPjG9QRMCWBdyDK8bzgkCRNXABst5zv9hQZFMgNmYqQnGOBYhn3x8dXUoiKMIyLjl+ylOgd6Iw0vFupHRuZWuSQhcxDaMmAuqT1Kgz7EMx5r9SLDR8kC7j/ErdT2GVbfVozZ9Rkdt9Mo286IuRBAf6mp3UfYLX5MUF0tqLo2CD1sIZDFsaodWYjh6ZcRNMoNKGWWsL4JcWezXETD3QywL6W3Fd0gKwC1mcQ9iEyB5Yd5MR0F93yE2begcPwssyrQnfsECGvD23t0jbT7iW388dji24UHl5vZ3C4GNheYyry9DTi6ydJDJKpx/n7teNu2w108FXu8y1g0fhTyQ1SlBoqj+/C0sMRzHc+XYbXSwiIB8HNx72dkuQ3c6EBLEujosj/8VDkKaomRS7XUe0wdM+g11kfG52XuEqMCNXlkUfxsUpvQlrL0abdPkTgJLWgdwRW0pD39g2m0sJ5TsvVkiLSqrZ2D7Bfc+Ei3oav6zVm4ApqGmUCGUCntAPX+0XGFbR1YlN0+WeOINXFKRT4IJZU+p9jpatCOYQEOZ96Mi8cIUXbod0hgyycUsucoAjC7C6Wj8JSaSGTK5D0J6Tu5sveE/OiitLHyz0Jd3LTQtJKJ+IuXVGYuVNhiw8TrxdfRHTcQGsLOMn6hfP6qRjUN4ZlRCJmxHNlUO/IGriRfj0/USrkHqUnu6DAHknE5MwaWMkX
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
