---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgDgi9swtI/N7WQmrWRhWGo+UNw6my+SHEo7A/uX/6k2fCDI8mvW4jecMxrXJaHS00qaIuRf2zT2JoRKcIFLgyoRbER4XhfQnDJuZDXIu5rH25GyPKAcpyefKwjg9eleU+vVdMTPW4UednRYlqa1UHEAosVjLawfQLSn6QCfOxEKGeX2e0SRWSZInbkSxSFmt7CcSXx9W6dTMXi+NHiYwTcMTvqRQ3bE3ZebzotkFo3ZJtK/nWk4SortfFqs7EDcPOZjwUt9abu8IUM5HoThEpBDpMdHzzXqKLp7CyIMKzGDJxA/4tG448CwgqequFf4DB66gKIhWg6p8iuVzqRscAKsCxDCDVj0O/E1AwP2RsuvpF8FWAl8kBOnqia+CdfgZWxPdMfdvpGNQE/8ZhJWifV8JD7+t3sIlAyDNQizeoEVT3Cp0Qz9G1OILD1KRCFLDh3sOFQRb+VfUOvBcRCQMh26nnG+SedjDheePWCnaUrjcigsGyFe8l0hSRt86+uoiBBLQlxXBWnHZsaVjmYvNAwvZk5b0cGW+pP03lGYH5S022p29ld5rTD9pMR2vxk5sqsbZmjRQMT1jIq8zSOPznlK61eXrbU0UxqMEORIJzQ9mxiA6zsYDyXtIT/dANFD8qMnY6J2alBF+lBElujS2T3ueGkaQdDyk3V+yHqAwDb1dK0KqN7dFAzjdeYbdVk/rVcuuakhda2qa6Q7s2nKgqHvgE5P+stdrQ9Lnsw4iX/m9yeLuH4xdg/9QkI5pg==
    username: AgBQxbpgNLSIBcTUy+MHjxxlkadNS+TJF0tu4jeu88oQFnUlzNNvMm6Bpuyh4hFg4agX2uW88j2WZSktAxUhBg8VMozTZdzhB7ZPJ91jlZccX56wY12SwVc4/cFsbXnp8NHrCVF5WvpvECBqMP17UxUBqYHNSd/uSdtxhhskfYqv7Xn6LYk099Lsi8Q0JInxiDp/cVjDdiEFg/tCACovo+FccpX5LFzaVpWsbzp8fgfl4eQy/iKEnAZoA1xATvg4ccAXOUVCdU4Y12iMo0N+Pm606fhvbHvFurphjT7cI8siNZUf5baPIkbLQ0lrS3Fq6ZAe+lvC1ZB/O4DCDXhvMdxRBxRdY9THTZKAlOoFFxjXY5/BqMK/CQEIm9InD3kniXVv/Cxv9y7A60ixNhT+mkAdliES6/5OLOrhjG1tINk6u/kc/sdzBj7PDxX+z4Ilo3dZ/gK6qIn846Li5tiK9GeR/GnPUJcZ3YLtEzIPIqofkyp6PYXjxCp4SPNpfmHYrJWdNX7kgFIqYXfGsfaMkubrAusj+P4SfAtgpaOdCxcbhiz0/a58/DGebbeLhxwCu6AMwnTVhKiYd6wNid6v5MouWLLdmO6Vu/QBFa2KBJsAussrvXlYzyJS4vhcni+PXOHXtggKOcSc4y4k2u4DqoAoVa0Ws+9GNdax4oQjQYMuJ/mw6MMJmw9a33L4E/oPu1dHYbeNGlyqIg==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
