---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCfqwUdE2TYAQ+BZSYvQZuBx/J4lml3p6zuK0WQrgonBBwQSTgIwgNiaOh22PNw7mUUrk/n+wKObmlDIn354A2C9LtId4rg95wZ/fDwVCpJ1myHitCJEdesFcKr7eV/MukacG4RI3nvwKQC/NSGuWFSiRWRNa6iiwYM2noaRW9T3aBr5Ow4ig2LmAaw6qLkHT6S7hRmbHBzm52bAtehGeK52NxWYNQzT+nJWxtOjeB+jXV26G+i4fJuCDgI5aACZRsRZMrnDUg2LhCEqMod7VwmPgvB7sfSOTHbv2YqGNJbSrvusOtcJsl81xp7n+C6sYmg6Gm29JwOT3bm527qixJ9sq6BGxW6j3FyqedAf986ES6VgmfmIunW/NoqdO/X8vhUcU00U/ja2S855gWd6ybzBtG/GPAi71kIk5DaDgDxj3RTBOZEtS7FjhWp8z4bpbWB1Y97NCjd6LM+vJyaIrM7lG9usfmsnGOtOnhhXPdtOkG2F9iTYZi2UKk8QJRJePwxSme8g9p+JYSJ0yKUVMNfQb2NXw9R8jvTLOzQSEYosk4USa4R34gnjaFTgVh9Fq0sW64IwDcCxTJMAGiX/GfVghx8MLY3zN1gFiFmYOtdI6M/6vaZgWGrqMb2ImDYoC0Ec485nVo7ZEcfjDWimMOrETq4OfzHuAY8bDovlZ64in+IcYI9N91lZs5dsEqPEVP1UioUSrMyPw==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
