---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgCDUxa4BgblLKg7AUkriFxWWHCeQvFKV30dQCkvMOy/85rJ2ITlFSL7IjaOe+5/kHLbbGBKDVwdMrJecd2XgxVKjKmWvsBRRu2JkoFullEZQeNCCJQCCF+IsK+5LeZXqGBTWwiRU69utwr3dp8Op5Fu3pHtBi2apoZYDPEdUPrNj81GiVrl/uXU9pPOPWojtskySWoEsTeS5FQRhaZG/gtre0eyolqRyjFVwxEAYRUrSFdSK8EAvYPGGxGYSjhkK+qUNTpauRClkUgc0lPKTpBD5pkZI5eLmMGEN4BY604NwvAa84ZtiRzqK6yJIRE7eavFznNcjM5HCTXhGWErrfKB1v/IKkXwuwj0xPkzTY+jI44lJHomh1vmJQ3isPGPQX6MfRCfmhWjEHfgfQANeb+I7KR5PW+ui0MEdYZtZHGbKIKOg5XehagSqXURhT2TeS41Et3W5ek9yw5nIFqV4lofdXOyvwbpMzp5gvMacWxIEv/hSQ85IURDQ4ouV5robtgWOruY2mLO7iIkH9VAa6SQeF8Zp8xCL6/ItY7qUKbnnM6rIzRj98+DRg+C24HNyw63yU/f+YrhxnSldu1BBKiqEP3YJqfb+3G4OB98Ln4jfMH91f0w6OzYSWjEzgMFQBm00g7X8sUZpKG/I7DJ81UUlOJONcC6nd7gWs/DQwkKOSYF6eXTRy7acT2JlV7xF0PY8X/OBy6xsk8+EuYGMC/SXLkPdHQKCvbluxJUklMn6NrQteIXXqABPzXtew==
    username: AgCG90orwY5LHxv9G3uo4DYK2v3sutUCdw8iVvQSA5D4FTb6yQaJ6jk5e8tiLqSDQj3ScbRcj14pVItj9AGNwyBlq18grgDtMw9TgZpwlIqfjXmKpZ7XMdHeBE6BaDbp910jTg0ZQYeQi9h7pwXXSEo1JtatNypuHGagNKXfjYUGxlp0Dj5QVeyfl3uBGFruHiV9L9dkp0fJkC/qMrZgQzmBBhnNiGACTK3dElHKwiNYeq59/rEBQBkZpBaAxOJcGpO9hpN/0kjZ55z3BfhV5oq2fyNT9BfDWUa+MJYLKNmPxkxRsPqCxyfUn46opOq5xQyl9DUvFONBx6eg0YjLe4k9Db4G9crkqZ8g7D7w4AuyYRMMYBVGIl6xnVoAW82MhPvh6FCJBpdItv0ao3G6xtSd7Pp4ZFTaZT0ZG+mcpC2PwwerjqFNzM/PbR0r957R9SxoITDkwETlwidsr5wYqdO/bxY1O9ECWglttGYSx6MNy2XIM+OsO+bCudZQYnvrN/dUwyjiNynjLbNSRZfT81ldfwb0BQTy9wNdlrUzh9pJblGn7V5FKfn8KFmaKPuyBZdPmXgO2AkWQv4HHsBXLwF4+klwiVJxSqYLcklQM5/RQLKZBIo5kQv89a/w5eanTbHouGMWMBFT6Eq7GKtbHjfxr4pyYdv5/6T7MDUlvFkJsSmmbIjX1m7IpH05thri7i9xoUtY6IYsWQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: prod
    type: Opaque
