---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgBarC1cKPnXjenFb7OALg7/i1HeCHW/vuNcZ72bH7Mvfpey9Gn7hFsjmyyXCUF3VsAaf3who9fN6ved2OXi7XxHrhf6UzvijoPvdwBDGjQmoxScz9saOoIF20aFsmjxhLEPUemsGVVJh6aGTBQtlG9ZMaojscNfGxecyALIaiQ88qqkv4furraW/R9lcspaL3xP9DC7kVyBXAaXSm/fO+hMkhnVzWWqJiWYo/mVEsB8zJdPvuxnHRrrjNkTwAF5ee6hup/r5soaBs4BKo8kXdUUqXSjJnhTGjDovVrc2CI6MvKLduVVEXSOpp5S2ozFdrB8B0Gw3iRZtn/5Is1hDU4oKAkM1DcXlUqv798tdTacVOFIN2mCuj/4be5GrZqtqcutDactopbgIjJ+r+1rkE90r9sZEID2Jtfy4ah1klDo4rdkdrBJSIZidN0/vCTuL+iT1HMCmWU5sWSUYEneGLYfEh63/O5hmihMnLpmdMCuIteIV6Gn0OiM3jUQ1y3QQTHRzTZevTyQEH2PUPWFMGZMeqSdh5kaYKOp6h8WLWwEZ1LWd50crPZZiwRJZq24LPpu0pTsitKT38ybyPw7rddxjVQzWBZtGsoMVcZ/i3Wj7nWQ9lJGaISlqvqijhcnnK2HRxwo/G/JYtHzT61ygZRD62s2C+Odn6XtJZvvoyKBgA+STHuXjeI4OF9WW5DHe910itc63+1CmQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
