---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgCC01AoPEP6i4IdH2qr7ExYAda3JkxJCMchVcC3llynYFvyIK1Z/aizIMPA0Me1vY/tF1Opw3cIXeYDbBrBha1qusqnPJsxpFsF08BVOZy/T0J2e3SJdSeWnFfOc1vvOCFL0X40l23HK/2CASGiunYjmXeypYV/J3LIG6AGXTSG6eRIHm9iuG0PHyxW3HXsDz7w3hDUp+Au2sO0qNge1gaEUrbCQnB74/+b49mQwoBEPO1IB6gPP9hq6qO8LBs8xQluHwGHfFm9b+QZ6HcBBbVoLNEQyCR2MdGk5G9BoUSiHfOrA6x78lOLM2HJVu5l57+8FVlOPfO+eRK/5hprdG/Ou/d3tc3wzP1Vub4iQcQUasbSLaZQdva90MbSdhGiGqHVfbUH3hQfhSDM+gZ3r1lk4zyiPAtEwq6+DLD97CAJsMCbnMD7ysCLPbqroFfraR7anRU8TwLCvu4hmPHnglUOyAypFBSQz9JvwwZiXwxb+3jiFA0LvFk9OcSZIbcj+Qhe3qRRtPCIUu9oJGRxBfu9OJ0vCQT8pkPyRKr3q0SDiU7KyUXs8zyfR3dWso2GkWCmS0L3dMALl4Vcnzxc4sYOiZq8SjJ8Q2HBBbfpZ6Wvy2rCy0M9anjAUcghtNvEa+VieRAvpb6ICP2embF3hkbNaHUeLN9HqegZz6xrUxVjyzi5D24njT4j2JIJ52RhQlp2t6jnhOM0Woh1jkxj68B0i4et2NcghoNbLAJbqxfe7CqA2wpDyLzxTQO4Gw==
    username: AgDY9mqiA4th/IraMUmHqNo23u/b4CXGSRJ2aV9b4Yvx/jczj4i8WkcHtDA8OPGuM1WYRyBWz4Nb2LDHz4OafW0W3Dx44vHZSnRdPTqskbFNMEBPRheXSoOYJeFqrOaLzoVNfyA56A/mjOdTdtJbgndKuHAlkh+UPGSRbiyUT2NysrkLX0DXPL06kt8dmY6AATBhQSKO0O4J62PI/EKsNyzbKGYpAakM8ZKm8l/17BPrOPHFASCiNEXS68n2NLd0KJ4IdPDqRghbnLun+pEbrnfDQ4TR2eO95oNB+IhRLiE69z3oRJEfYACPG6Nd6+NrcZLKdVzN+IguE9en67Vqju/i/ScnT8ZyAN8u+DYw0RuM3erXBUdo2y0WcEf695MfAMUZ2Ft3iIrp6lIb4DFO9ygQuZnCMEV+AgvQJTdYOQKl8EEtOLI00BP6dV5N0JbubUe5sdZZjfRmZWXh/E/4YevuP97rm6oAaBfMzJ7C2M2fn8M30uYr86D48rxQvclwkBQFwNHnbumXX7e9wyjGJJvDnnUlb3Buw3rNrz13z4FEpe1gJR/MEFiGE74uRbqVQZdQ47QNQYVW0Lr7KO3zGweQWQp0wTOKKgnM3M1jVdT1cqFK2mTFde6uUBtvG9SB+mVXBRcIQILProgozddtS51b46u+NmVFpNzMZsDR8ZAQu14cJqGhBZm5NoYwFZ8HopoTZM8lcXfPuQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: prod
    type: Opaque
