---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgAlnmADOFd+ndwcHp/Y/BmoEyf1U+ma0R24slyu4suDkZjV8MmYPwVhQ9VfQ1hPBDs3dURyBxpff/kv3YDcytchARbRy3+ZSA9tHOQmoD7rFGz5LUBrsBy4+BlWxUZbANwQkwKkazNlDnJxXPftqg0V+nNJE5RprkNxab9F/MB1o4J9kPWlqTiCJvRnWlX67mGDaOgNR1DaSpEai9GuW0TtG2yd3bLax7OjYUx7lyry5NEM6Qu45YoRctmvwVbGcQi7Uti/Ad33+OK91sAZjtS5ykOVNLL+kORV5qaVT+lK/Dy7cMeQJLChKTcI7Z8QCqQE9MPFHKBQcvuG+EZ/Ld8E+tE5nlg6T1NA7P/QB4H1E7uVMqgbVeYH2dV2EQG9k0GQYm9Y2Qo6QOBM2oJert1jgaq0PITDk8IXJpwD5tYClu50Y1NLC+Ik4xaH3aWdGkBE2x8aITvpZQCu+06IQux+fCJ8X2gHqvfN9kuDnsL9IvwAV/rbMPgjjjF/dJoJW84sJLEu+zlbvgBFS8tRaiJzIftLnQY73g36Aak46zTlVReGTeP2Q18WqDn0T7Iqvp3s7DkfTqJROfeV8jieHBoBubgKYoUkvDrnaOtWVY1NWNEdwUIKoA4c3ETld0yZ7CAlp6dqvE6rWYCQvB33tPDFE3TEsDbQ5ZLsZj9U1pKKUKvhO4t0ZVmj2OlGP4xi6Wn5SgJH5IvwLA==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
