---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCpvnh/D4/knXiLzPuXi8MkLt2lXqKZg4GzCQX+HwhzE8HU62fr+cTnBr0OCvpAb/ah8LsnXdgR+jPbDKAmNi6AJgYiKralrRcVThG+DO6qiqCBwCi8eiQ0tK8A/7lB4b6T5z4fWMQXnot37wMI9RtIOuDugwEf3fZ44KRnkQ8yPn9O7NzvAqpsXEi3IJKvC8hTXlzPu+IG7vLxpCwPaxfDmLSwQz5iHtwWPcgLZSJ+iOgsAl0WIl74SQam9+y/b/YNZkG/dKULvmG3u5QrMQCl8XrdTlpU28yp0FToAfi3AQVYRFMHD8XFKi6jirqML0QY4ijzS6kIPoyBzahwRuAYDWhf2qNbQtUvTei0LsRQiX4nmbYnm+QH2XfPbBwhV/8xhTYLNDLd3D8YKF7TQLuDaFF6+INaKRfKZ90MFF1jP5jqk/8QnFJiHJeAGxMbtU4LJeBCKM5m34lnvDMJiXQvSFNvnDe9btqItagZ2SrJfxSkSf6micQ81NRpQU7kn4cLa0xOmtXjc0o1dT0/+WatYtw8/VztJrSsmaV1TgukYBIjufdzCQNh7h+2R0dRSl6MvnnP+oAF7AIyU31sagYeYvUX9T58TaTCF26ryjHFnBUdah92AxwahI+nUulkKnw012+DZWuMBvWCcm3XAIb+kR04Rkq3KeZdaHwK4QFonR7lCuTJASJ5V06voLqLXxAVUGHWwooUew==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
