---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgAtAfZryuN8Rh+xxjXWOZzYhF/x+Kvo9F1AGQTOkn9JDaHHPsLPjm9Ginld7Bj5+7wQ4aD/AeKWWp3jd0WLBmaKwN3Aah4m2eZNIRigtrIxA4gfuoMrK16KGxBizPqZmx9Yocz3V2TmVwckNnxaewpA89FVECBmCKgFRs2wSPq8IrFIY1SFW/I+dC1gQvAuf9sCPzdzXxY1wYjS9w13pRH1Jr6v6EzITTvhUq0IELHu6UsiE09K7iA//p8UpXLZbFfypkUMYAi1xewTPhtuPUvXE9cqBXs0PuxWs4dx4xuV9QtZxFWoZfTsYXgHyopci2zJzUgQiwNg3ylaYxOS/eJYB+Sn3yJMDYFgKMuQv9g+9/kHUWJWte67Mi8rqd6Q9gR9Xv/dmZxcrqaeyd0zE0BCRFovxWzWCz44yRlgwrNgyXmWDbgoJefe9KbbONeCjuT0eqMqp2azZmT9ESJ1iGRu9PzZQ0pVNWlhK8ZYht/f6D3R45h8W6Mw6IQxp1WlFxlBbxlIp4G5PjGyLOAifMPh0Z+a4zO3+MAovlhfNLDL9vmjtVuYB9Dl42WAxkKVtjCSgSszMZDldf5kQbZ/OR/j+wugDCWpBXQrJQcfT1YcvvhQy5TPaOWTCPaHJNM9VR2rySSbejaVfHHCQuj/PW4hoqxCYm8tf1WouINgFxznZE8eiNXPwNpZNClf8PtXgUWhtwIoCBfjyg==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
