---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCwkDBL5YAoO2upXFksdVrx/VZI7y0N5PRTdkWqgFHIp0s+LWTPTkqXBlA7CiHg4uxyDh0IzllMNSb2oF6x9jK1QtiPbbAe2LqEfekDaymWd+i/eujoj9G2x6gAcRqNf9AgUxmeqDSMAN1V3FuNsuWyLAfF7NXh3nUFCpUwwSw2/64wUaL8TBpHo6hqutOLtVmVctt3KSeG0cqSVdfAXjLZRBGI0es4msb4MqmJ3t+6hreYdf85jX/ShfB2oYeqProNHUIgR1UKql8WmneWxsb5WC8yyXMkzC1mNg/0S9NU3o5oHLv3C3KZjC/eh/yprFFcsTHP+ZXkSMAZ6mvsL/Y3rikfFITHtTdyjNinq3du3m9Lxuw5l9hDuHwfopZyB815vTeuO2h72om/ciMqMpVn9wT5jQ1eFNAo8T5KF4mp3u1yAczWUBKUpdlpO2SYona+/YjKUMgAJNumneIRAW/LhX+2fMkZllQ298kn/mwEpKp6UToUqGy++8BYn2Bbh7MrPIAK+UVq909dyZqLSmrcHMcrISNxXGapGrZWfOmjGmgpaKV7p87ofkO69KUuuEK5kd0idgPFANKiXHJRBBR2tUu4Tv/NGUVKewKHhnbza2RHd0cCD2ws5GsPrMFvSIu2KaYLDdoqEGGh3KtbXPxxJnlf2CH2DxD4kWz3er2BK7zqmkFjwXjaxhILnMbl6C94ZYoamBNuE6yVcL3S1wzhcy17P8147Jnj/QDTDr1oIPw59Q0W/C/X7/VrjA==
    username: AgBY5KovvAJw2YOfNDhPf/t9X59x8V3XRkQedQfMwE6sz1Qa6X6VjQjLxKuM/4E+LwNsXzMrHecUrfDMye3S4hg8TjhuJ+pwvhhvYeYvVjHkm0gnUPiix0AJkPpbn04LzdbQ8dLdRqFCgmEOlw9AofVSRGqKtpEfV36423txo1L7K9SBaZpioiM41/jJngabv5cp1muMnqwXtv5XM1ThxJu5eBN2S8XUI1PnUaYMWg1r4VKK0n5Lb0paW/3elOu4S31QBJwi6Ng/W0kVmJOEDjJPEj4Ar8gxBIFp/0Bkiml4RtW8n9qg+g+Wnu5fhP4t8DayVckLu73T6+v84j5QpbW6+ZlnrickHAs0z1Br2aq56l6uRUpqtBL26S+ytR69s8aw6G4i2bYrer6GsnuJjvgQCk+Rw+I9vmVjilyzx+Th8Q3HJR8U3cpqZsyA7Zk4Z/3bWCpscrZyPi5t5D6iDEy7T/oDc2mAE+SWr0DAdGDXlWM0A1Vgx15IBFBbeaNPxKM/jExMp4WHL7g9bPSbYRiLygOWqCA8mWV9FfnKMj3FIiXBKtmoDjE42lKzOAvsOiayCgkSM1g5PeJIlWkD914EZzbGVMtGJF7tNyg76BBRQIdOkOr7sEEm602CidY/36WvYoUz5PoIWMgvDe9aGWdgM0jEGAVylSswowS+4sRMKVAxjeUvQQG94BG7tUPdmLeqouNwC1qurg==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
