---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgAMm9ZLsWkCD5SePwq9WFMIolW+Nk7W4jSkaeJpiqHxwnJpjHVuIagFAAHvHVZ13Kdx6NdNzsEGSFgyACVbsd1weUgWrMX7NN5IPf8WEvw8FqB3pCEShH6ZEGgPsT1iuy9dP3wiL951wrV/wpg0+ylea5C6ll9393qU1isTpdUmirEHPlz8Y2Jn1AQVEtN9XmPxgNsp4pZABFQmi0BFI89RU1v4W6HbwmjY4tu7gNbLve6/G3rttFZHpB3KVVr+NHX1e1rKdIfhq+wGDxVzoezdyyltgcCVSeYPYH+uqI1Hp1ZBAwkINRBHOFegpFhgc11zJZEBGgscxmv4XE9dlJKyA9+39UfcmnUTlyTRYjlmFIgD7GKId7m5BPRkb4VM8spUAiCgvNsUsEM1sHtCZDb360TRtOd7B5SURTrnY5NLbT/dwvZ9FSRZjDK2CXVfXdQx5Z2JfSUraQZHEKi/I2R8dOKqZckm025BLyHQLM8vSqsX8/qVi+f/z047LzXf5DmkbkV8fToKEyVbWQqsVw25pMDqMSJm984lQK81uLKyh0jYKNS9WFetLIx7iTVvls2IJZpWVh7Mddw+leyc4Qr6iN5M5taUIdCOFRs9ggcoema4bxQ7eR8UXWVVvOnCAmKZmvsCCaBEQBA6u0vdCOmZXo8pwh4jeO9WQ5GBlkEXNqEnHEApHt0sux2rAU+Rn//pD4BOtGn1kLG169FK2lwkCr26BueGLzCB1SLKiCOmsD1Vqu529U4RV91Zjg==
    username: AgCKc+wETGKYBVHWORbDBeuwW7rUroO0WInM8wxSyqmatDubxmWIkvNe4XfhU98SLp96sjy1x4nXarXTomB6TUAWW4Z17O85z7b1pDyJbkwFtLuU+ib6PTXQX9pNc5PfeeapfLGAMlJD2hrxDEMBsvTTWnBFcmUGk5ntejlQ7EJ+8t3VZc1VwzLcDr1syBLqKcUxjZnq8gqgt6vRsijLHbVmG/nZEhccAjnFBRL+ksgy+CNbs6kz4VZAwntadhVAidEntaSUcdH+zEf1wVwGxs+Fs1ovmjofCoveZXga/ShN3A2QMsuu3gNH8YqBWAIQow2uTS6d9zBrvFU6twRwrQDx+t9jxlyDsAxelly2Y8CZEA2kfC+6BV05aUXk7Eq0jWKDPs95rXdsV38q2za/ihjahWVV7BBkgVIG5b725OOfhuJRyoeMd4ZWnl/HALJRRGxRtwqg4lW6JEv+SpGXmxsAKKpaWZH7DYR2OSgA6ZctF/LLEzqCgKLgSo5geUxxDCBuHvR3KHu3bvGO7tBExLQCRR6xL3FI7iRFqdugtnqj44AbQTNIu6nYrxHXIuTJ7nNfxyZJ3pKB37LIr8Sk4pZfkN733YdMvYwMZfFYwHDb3oVP2Ujm31j6+5N54cud76IRWBJPHS16qOZegcANLnAxAi0ilRYMf7BW8jdcrkdWGpOWX9ftnUUVoT0G7nc1twxzGxAZFeujpQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
