---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgDB2oh1k4GGRDo0DDomsV/015eiNYISME0ivatviq2eJBjTMj2Qap9WcWfW+ozM1Cqrirbf5+IpjbHGdTjEj3mSYxEZ/WzZaJzs+nskF/DtxkkovQqFI5p+ARSgJC1wHiQB0rb4Tuyv2w0fZivc4wSzGyTmnblgMNNRqefIs7L03iO3wpJgzr1nIVk4mwRqbAo0XQy9qKIMAZUQIbl56lfGTQoOPOgBKavL8MD/+wh+/hMmgBi4okciXKH1Ca5Lx2gv56RLOPGWMos1sv9VxKfv0vH2i9QDXW1HdbygAdkpGP1Iza8QvG/QQvTWfzXjgEv7ShJ9abJlieZ2yCBiNbyxwLXOcqBrpyuLUDjHHwuIBJSgQPfMWC3bJVj+Mo/4IgDRjtTj2XaK+68uzGRZ3NOjCAbMZX4iZgfDPCXaCWGlIZQEztgDLCaFtYZPNqxN9Tw/hJM/8PtpOSAQPV1ivmgij1F5F6FAxAy8UJlRkcBEb0N5l1zoh0mtfGIXVUR1GzcQ2lrZJd3YdKY94bGxP3I4Xk3KXYf2GtCOoWRKETzRTRMxG2p1gHdLvaarwWXwNdPUyj/bVR46JTWlMXztorAgwD6taU3BZiDwhx5boUWZu2WPveTTSLRwzEwp2m5LHjrz6Ke070GnT7CJU9+vLvnFvYbFcsdWks+GI1PnYHuixWc3oyVIh+1rfB7V0gXwD1+WDpXRZbnfSF4IecrKH7+oiiBldjr0kPk1HbpnqV4jcR8V7fg0wrWXvOJEyQ==
    username: AgBKdR9dhJFb99Zwh2wzpECmREdiFifCtHiP3QJSFb1xV5852EWsgEJEGL+pzLXZjvU0eNXbB7nOybcCGK3FopP471tJ1QKWfLC5+fAaa213JYEDaL0Z5/igZpcOsMWFHRfaWcm+e+euLz8qQLLF2QR9nDB1tyqEty61BBEwgkUA3sH/V363YqoilfrJftbIiqFsftiT8/MeT70icnoBskOyP19Sb4sjYaDFmShIMEziz6XxJoL36C8eITdqCKF64ZiFVYILN2V515+NMH7p2Xk811IHAg+Wafx+Y+y3sRo0EJcPbjt7jxyFWX9enGajZUvgHLqlH+6dsQV50SEjPVG/4oe7x/M/ShlfnqrGg237s2GKbJ5ZoBKm2Gtt/SXsVxY3YnPDadM530PreJMYlkBuO1MkjkxQYwxi7xetleHTOwuuRjUocwvkuQU1VMRWeGe1EB3bBJJZEwgbqAyo0WIXhhXW4r/hLghXOxXiku3pgWedIIlf8fwvidonAnTGRd786T1WOu4vPqzV1LqSqel/m1gFTK16eRF6gBVz4NTe55W0GOo3T3XFt0OPr5JyF73HPDEqdTVJB3uuRe2WdfsBYfUvzc+8P8JJ/vY0wuVz4d2EmlFw0suvEn9p7DxLkQktH1HNYDnwIQegjQSahAs0LqEwolHpQhTekoEWSrzkOt/75hg/5n9JB+lvNECTIpEl7OkYVWDeSA==
  template:
    metadata:
      name: postgres-credentials
      namespace: prod
    type: Opaque
