---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCnlH5mF5W2rko0YdzA/mXm2lcVUoBl25+JK+wXeRcUdDDd1cRTCa0HttCy3zrFAbFUImzRClTwSanLofRMlbWG82fYvzOLBqplPvjpyGCJ8KyQ9SsntHzqPMYBJ3Tef6AE4j0er0S6mPeRC1dTsNCPWxWrQiOuE1y2Cf8mxBkhX/9G3Kl/VUJNvR28gWk5a5qyILcZP4LIGnlPcx897U9EnrXDqRyIeR6OYKlrdcmnOIzn1Q7P99wNaRUAuKOdEqeUnUo5RFJNH5zvZPpPlqWP5Yh7FDfSEvJflfGsxc2aa5awcEiTeTh2Naz6GJOCNmmTqkTZ1I/2lP5hzCy26SS9qF+wA6fekN0Pw/BI99t94xFfMftitmgBYkpS3fdKxpz2znDeqo7uyE96LklwOA8EPuP93yauiVkvgHxOOYCt4tDwghIqxF4I2fKXfbIxqBJHM9ZUTBdZEnn1pVpN123YjCj14Bv6skM4jQFH6fxLGHzeBcxXxGnRQWucEJJ2p8YauYaAT2O/Qh9K9A4gIWaEEvfSnalQf7H4gJ1WpRfI7Ro0pFFUDqSv/S3ZmC14oI2i6eWIp9ERTq+ixa3lmhO4LyBUez+sWMjUbeyiZIqJQZSk/dDH5dFaCx9gkmLaIxAOIIsXK8QacMuq0KXBF6mp4BhOEr1xiM92CMTKfe7NC9ceTDiA4eyv1WwQbOw5Ja4m6U9JGmWy1Q==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
