---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCqeOsxpyKY989AR/Y3TN+DRwPL+zmkOWog7e9fVRumeCnZWxTWpTHQpFDRPmuyhMiDgVUwGhbcDD79KyswfL1zxef7MX2IbbTVbT4R4fj2aHHM61NapBXJlz1S63xKEjGVAaelIS0r+2U1eXzTm+WtqjrXZW5G1WSlVHl3GbeWK1vKVVkViuhSdTX1Qbr8/9vASc0Bv3FyAlv87SKDrbtVXwdhKcTFA9RQbvy4tg9URy99EPFGm6fT239XbmQGCEi90B/eeVd3wCHo742QtnJSFfnETeUmaL9Lbc7/QwEdaThIu5M7+KsWItYpjH/URVfnlb7WXkNENVfrfU72ts4apEuLugZ5T4TCX6HJ4c8fRd1TXcOgGg23ZmKRAgHS2I2pEB002kBZqnj/DUxEHUzvlOcuLkiOF7KoFHj6LuzhFxOGCQbUzf8QeAvOJq4M7QHQ57me3lRyKwoUscbKShwUv3hZa16vm6c5B7QjjcVnKYBLOq9ehvMh4rwXI5MP9AokOAt8f/BeOhts07nr15UQImKkV4acFKHmnM4U/YgvzN32eW0oUdBsi4U7zqW45JEWzX7EEUJ5PGd14ACbB1Z9F9uo9IAw3eBLXK3a4Yk9uBY8cM+44lTcouphJLzcrLYuI5di1FNSrvnUp/7rZX/TScEpNtTI30n78QQtpA8bbnYnZv/OUJsBXVUJHZZt4cNZvMO880X2hw==
  template:
    metadata:
      name: postgres-credentials
      namespace: staging
    type: Opaque
