---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgBsJ+od3ESR+YTlP5PujvDct4FOZbCFubM7oWsfLwidD0k7cgBdYyJmKP0b+6D/FtnCRjGXvy4HzmRu2v/G73yrQiGwrQbkHbrsS59iGr0bbe16wpkEK+VqbfRO4Ve3f0R/w5b4wYRBL5KHS+QNOqGQggr1mxVqECjgrbBgDIbkS+NV4xYkKlC4lP2LMRTG++SscPBjnJMx4aF1bDqAvCj2F/iJP8HaHjarIGs885vSj2+gMJsgQpwkrRQykgrdwa/V6meA6YO6JqtKRFCBTeCQSAMDRzsC/MrDpe3K1DHteV+VGuecElPVBItdZg+IIe77ypNtzHbGNoBBzB3Ni/l6NglEAMj7nWikmcjOnmF/Sue21m5HU1aVwRwV6HfEDGqoCpOYVMEkb+TgcUQWyIIJoAxduNBq7e9VrD4/9YK67+6gzCTjKLLqwWItd1uCH7qVszG6U+3qs6xv/7kI5TxiSusZ4DT0MGHOvgC0KdRDo/LmROxY9pVyV1Af3XAv4TeAOTdNlldzXi0zzhuWwVaLy0a8WmT8XNSoPkeQqXH0OA5CRWiu1gPcSWqaqKGuOQsEM2yHkNCAqPD6sdahFf018PoFc4eXzu8dCx97NL8d8etBC402d0ePaFybY9hLibD+lzQM2nDLrXGQezgBoV4Lnv6LpXYy395K/Ntu6P4wPd0ivLbATyN7pRvU3ud9vq09UBhxCuCl8hDjYR0WaBAyE3x6zVkMoJ9y6OWpZ2yYpVJUiFFcqRFYD3U6yA==
    username: AgCycjimdMF9GBLq8SSsfisYQv0bvs7hG7PKRb7t01eEhvRwwjRsSwCeR727kMo0squvq/HJB10WZpCfhjRPwJEDf7XQfBcOe2w+hvg1kqGDxL7dVALnfm4VdCMf9aqSWunM6Gkr8e5qBT048kn4XWECHF3m/xyylZlirmo8DsnGv4vf5jwi9KW+Cyyiya+rezuO2EJVy9gOP6+TuVEaysOdQSRnExVDqBTItjS/IPnBpCN1JBukqCutCROE3/Ih3SNQoz9b6FTom+t6/DIiTjhwL7uCg6kJmW0FeXRIY25uFARRiXEmHLzqZRRVqlzdDTyd8eGO2wPVnri8v1tBa/IpNL+NpCPEFi7QA81YR/Q0rJIudxMTsb2rovmmgSlCh02mVJCcIIYEXFHwLm7DIoXrPj+FrJO/aNFkZPT6zMZsCJcp2RuK5d0ZouChmhYiGHvi8wtA31K/r5gfYYPIz/f1YfWk0rKgZQbdbujUi7eDoNunBB+dd9b7tG5aHTb4ozSKFNH8zP47lRNqEfHc94efisjo+eLwOSZt82ls6Jnnn60EdBnx98X0Jk2QFwxSpOeqz2i4jFTL/mGOt2tcIvx1qK6CIBuxhjw5lRmJ1lwmvXlr/EqnKe5MRAjzMd6OCilM4GaDZLVzpokl9esSKtDixvLQRsJ9dpau6kWikWqntdPY8CPhjo4kv/2q/vKY66vJMxZrvlK8gQ==
  template:
    metadata:
      name: postgres-credentials
      namespace: prod
    type: Opaque
