---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgA0DZXb1Q51+VD4nTErU1m4xyVdBxndUxN42DUfCMINIKFkwQ3qYkb/3ZiY9UfokCDX9pbrgIc+27XsDXglqAPZM9yJmxS4IXVQ9h/Dou66eWLCVaV0nQ4/OzQrS02BGszlQBlsAX4MpwMa4SY08UYTInO3E0uzV8lJAyuWJg5xGOJy/h2ranxGD29JL6liH0kBHx8nTSU/dZvUfQvNHTCekE6B0O/xCFYS6uMGmm2lLOnIVelUF3tMlr2MtuvB9iVZY9Cak88tjcLI8KyPQ9wY/Q63/JSmsi0Xf+yHSzF7xdEo5rYJvl2X7vFMbCs0n5Nq+xWRpMnUukzOCiU1TsUiDa6rOmL5d2IrllJ4VHjf/fvG5at7ocdydZA85I1d5Q9rHTjJlrIcXEaczWwpFOnnU1uDxOhSeXGFQpxaEqbffYcAY6BEZx5pcw5ZqDbi1lSr2Wcuhn/qhP8hQk3flwlVBhF5VOD3trYn5o/Nc+iPj9mMTZ3a6zF31McmN2MEFqIF9N6Njzf4XY8GI3oiaMfmjZZcbsgSVyQ+ziHH45meFS3gVzLxSzD14QMWgyC/4nPo3WxaC6/nxSNyyh4bH9OS1tCxO/pWPse1OUJEpxHEtPLNy9CFRU/Cah2MKHPnRuMcT6QTvK5ypyZaAIxd2SVAAyfYXypRkCRBzYIdZypZeFwWhGV/Z5O9LVu1mCI+1MUFF+Rzh5lBQg==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: staging
    type: Opaque
