---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgAiT5HwIcdmf4sL3ZAEf6vdLq6nR4Q3dmWUWOXp70HN/EB7bX1BM1mCwat1t3G+2rvmZg/8RgTY7xACWw0LsWaHQJqrox5O+QNYl7uAqNqKuzxVGBImBgGPeu53d/RgbxlDYsY442VQ6XTQexbJ6TTKgjs4q08tXh51P3oN6SqJwK1m1QQCXE/Dj7+CR4zOoKfTKBO7VqrW7LGNPYArtjNc0vbBMKLNGGv9o0FGHYkwgeYWiSuKfhIBvOeuMVD0gVlQ3YOdJkNI9T+ejGFp0M8TTuqXwKtEPkQErdZJ2lAvxd9ikyA6z+9Tqbyf7yiFxXz2yKG60Od8ctpx7hXtKn8SNWKjw+AB9JRuMEPSvwi495xZu3TsZbgp561fg9CqJ6K/HmFwqFUvJqL8x+/XCRreI4JE/JnYiQRVhcq63x/VGqfS6jD/1zR9CJoCFFfunHxw5lB+iY4wG8hh2BatkTSWiD3rjhl3KvqL71h8ORO2ykbT2rNnlEX9Z+zFzjkIl3Dcf1mBFXqB8yGlDYHh5DAG5NFeuXHRW31P3kZ1XGjXHsuo7zBsg+SDngIUlAiCP/wEMbnGx2wNhhhYXJFmOjxbLbV+ud6DtDAYQVwOCRjAUMFU+oBIGQlKIHKj8JwLpg14RpZVtMKyiOywgRWPMuThrrvZTfihqRJQqGS6Gkqqb7XKDdJOoHFWUSl4EoVBk4qAUMgedz2C9w==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: staging
    type: Opaque
