---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCQjxgteLTwK8B0L+nJ1FNKDJz0AScmHrTYlBnXzTXUC7AFTDiClwpSVcWVUGq9xTl0uVxF4ooxAeIv0l/ef7AqH30WV3ROwNSYkXoiUQBAL/PwzNHCfR+IE07cQm49Cxmkb5uM8sGN34YR2bim0ODTQ4uwrTHrTjhRXs6f9Uyr1N0JgGW35p0+/DKPDRWmKZzcRHc7HmcyjYy5QH7wwqALQZflo7hkmaoJ2n3KA4+c1jtMu2kd9S5XxdbLl6nFgaB3w4ZY/Jg3sHtRA52BPwOXkBe4XCgZVA4SpGbvLlNEDtWzSlDTS2d5isR8/YcvItW4eIo7ZLNdgsdDx/BszSW6vSkJp/s+oOU7xUMR7r+ZdfpMNIBoLzqF7ui/i2SQwyeb06BBqSy3bGqUB257XMA2Ll3o3CsBceLRjbqMDg8sg0kzYq+3utYr3eLwk8/TMikOryPSMbzOXcqUwy1aJbnEX5yGzCT5CoV9uL5yOpnVBJ1K8Wo3gzD86yIpwAfUbBLwTkzlcRvFAXoYOdm7Y3eOCkzj65P/PZa5zM66GyCrqICbJoK/li7XarQwudsqdMvej/VID4XCN8VJnvBhLK5BcnuAKnvFb06et/CPICbjeFPQbi0eVwVXi9E13aZvhcqqmaX1htx5jtq5HcU9Gd2P7qXIIyQhiVtUamBoqaUve+eVwlDq2eZmgcozVIwPwvnVhXGLM9Hfcw==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: staging
    type: Opaque
