---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgB7JUE2z3y1q6CBmv0E5IqQKsFveZCZlqdT+yw0d3wRwtFQHdl09z+GYxYiGGy0j8ul33Wi+EimPyxOsG/R8T8JGMRz8E9aYHonL0Yd7WuVFz4lYwVNYFA26mux2UjcaFYBdFl3OjNiLyAWZfkfbCeGcrvmYi5OXZOmXm1ur+PkMwIMWRf8q7viIAO46lsqCnxKcRvqJdURLsKH3jPnR/uhKcve/unRCgXjPNL8q+zUkEItLXA6Un9aTY9xLXZfzydY2liJe/hsf3yDGjJ2yjIHsueYrBSt4NihnXkuVx5NqEfnt5u62ygjJh+utNtAhxlRbU5vhWkbjJbCqrnR/M/fkzW0X3yhXDh9HeISltn9isnsYg5AsECN5dOmN5GEdljFubXM/9CW4xbxP6ZqVmrqW+6SLYXrzQglUMsCSncDhi4ZpVVNhEBPEWN55OZGCH12cX00MVLTfy4QfK/lDks10yaP5+laIMHAMYBWe0//u2IVz3H/YQTT0YKurw3cL2Hvh3ixyPYU7mQP7AFrjK9rbeb1+xwzVglhimA2XYFOCCMFx5HnyGmFZxH90L03hDP/l/2PMnX8BukCFFjN7/PzZjmwJVlwVb8mt/M5/MgLZDibnnAJK+4TjgI+1YM87Nou+kfpnaeWdQKQd1PkSWM5CVZ5mqlSsb16V/RvZy2xVdW/30rpk5ORRjlxzSPeAtnMQUrHJo0DQQ==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: staging
    type: Opaque
