---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCHR429XLytYAhr4VDuGBuLh2O5q6hd3ATOcpXsWGwuna2j5nAjL2PKX3xotp17+NC/Z2k3YbFLhoUqZZ12JY5LVHgtMT+ZK+Unmrt3HT/LdELHbXylOpGoJukMoMcPrzg0zGKrA7qhx0KUoYfDNVRM5MPbu8wZYa3HC5OrBP/2PLwSEhoaktpsfrl8e6PzKwKD20+xFLrtOr1knj/opnouL/Wf2b+/sXRQcNpMLVgXLXKQ++YxHVZRSxRAIKvgaERZITKhARC0dc7z3LS0yCkGpgT3pSbml2pVcEtZuos9kRlEsbUBSvtT6ZCm1Dy7WHUwAhmHFtejRqDrPK/WaBTlqsZPMpGDILOj11tW7LQNEB3L3PximAWYMUG5azF2WVxnE1zKBxpn8g68oWKl/cmNa8s5zUrZoIrb+qW7QeTj4E29D7TwfEl0lBYVbWJElkr+sWMmL1XROULZUjK9BsoudSpCh0k+qX5kUrnpxMUIHDc2KKrnsFj1JyQ2nuj/eGUSPU0lOWWy0GTvzQ2Mm7z2WKr7TesWFtLmoRkEhICJd/RhaFtKmg2x0QkRpbkA4pGg4KATnj17DlCmFBOnAq5HXK1q1bWMnLPBm4ps8AafdYXjZF2JbrJ9hj4JA/SK9Qpzo/sw2VctB9SmoQV4pp2COXGDeJPv+natbzfVMm54QjiS0HqinOlpTU7U4QEkDS91v/nvVxuCWg==
  template:
    metadata:
      name: rabbitmq-credentials
      namespace: staging
    type: Opaque
