---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgBpLD9sRBVyJHAGheXt5PubBzuV8N9b8Tw6YPQGaslU+WMDx64Mbqkxjz2QOZAQam6bHpoK5za7m3IR3/6E0mNSj5jhuhxIBw8di6YYDRGV+efq2Ny15YPU1xlylNooYVjVFbv9/aKMpvimCgaCDEQPlqPJ1k+MEcA53kYfnwu2cYjDxtGPo06iEVCHUs14pNdmmgVCHpql5jLW9QJ/VZmnGgh2jc0QGbS20oYYUTIZuqo5yw4upYWmVAh1jLv/DTydE0SA/J5DsL9d60Rc8Ump5XOi0tGgeHmEMoaLQf96V1tCyJ9/hYcai1vrn5vpP0DvxyjcOLCD8uO0dwMMP6QNdxh4yOxBqlZuZNU0EDgR6NPrfaEoWREJgO1GNfz2fU5Mr5/4iAQt5QH6nbAN+XYZfpEY6NlYYso/Kl7mnMai6rECzzWETME4lYZOXWvnHcZLGBifTLnmHp8CqvBYiMlELAnJAcD8CTVbRE4xhrkFe7MwLzIc3WL8Xd5pWQpT8mcvq7s6p1F3KFrTPwul1Hdamkj0TwpC7cT2sKoSxbSm76/SXfB7TIrZQOc3sHn2NLW2KTgqut2j06W92UsC+vek9C8+7jaZg25JoDjiSa+WZj260bmey6h71JEJRs6D38w0V6PSaDqJIxt/Dp+5q43sPf8p1xaDi0B9fox8WJ1/hmL9fzzlMJ1uTCZnnX2oLFMPYeU0QiKiiw==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
