---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgBB6f8J5kbz2f9SQuTMdhT33dEn+mkpxMpcoYC9VGqjLy3po0Q10V9Cri2uCrwzYkVI8DHj4frxxtXfonIdmamQKcKI7i6yJKiBTLx/XyEPJpjzQPO0szCvPX49FONLQ2DYO82J/rwd+Yt6O5UKz5wrgw6eTGzorbAIZCvMn+g7UNc/mUDjF/rMHBv61GGIWinLjI4Q0S/lbuQ55/B+fFAUeJQUzIMf5OoGgOHr/UBgmsvAvNTtcz85vszy6TW1VXv4p4LvmHXaWw5OF1lFABEe19LP2dBDDd6Eu4ipIzlyZfPMZzGaZVymJRwq8vLoE0fd8Xjb0BLhy8aQe0w4AT/wqEkGp66WIe1XUb+Ci0THlguF2GxKAfou4cLPjAUWKnDUxn67JjmhPaamVbZzlFM5tLDHsB9m0zHuP3Mqh7scDvvfyeuL28axnzzbhPok9MyC9FhCJDS/07oBdqLJd9apnVaWZzNhx9NJHskAe4YDmbG39VimpfV0wDUaHkbyd1RaqvwK8Ih3bmmmeoyd9WLHHZ1Ku88FV4Po8rHO9IKHUWS5axFAOJqkt2gNDFZtex5E8Jlrrc+tgjUV+Hor2W/WcKxANg5Z/XP+sEz5lJwj0iNTYaeWtKBae/ZnhrJCsW8FypoO73u9NfmWC7EM8wxor5WI1CLidwPxG6WZHIq/CUHrL8MFxWd9Ii6H7/Fd3wKVyMc5lhvZ4g==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
