---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCdwHWxUi1B+t141ia2vYs0DKKHQTawSfjrcTyZB2s518edXJnsLOuK1VOfgZ/kdbJSI/C0auc/8/notMO/E1B/o+QCEYDM2UsWC82XRpShw5Ekkk+vAcSzYkHM000SsHJHkauCOXEZj0ajcgxtFVdnexgJXimUK/WXROHMxfGNUeswP+AQDCyfEgzzIzFMSIIhSG4Yu0qHtjDpk8zfh2O3XY5W2KowkQoAx3JfJyWEZiF5697Z+OuAt8TXMwnodpttV/A/ESaLcZM4WkrIlz5Jc8j4gpYwaUmn7dE2d0np8kasnfmKRjb0+83blg9AbCCo3vjyW7xInp4VZAi5ZMrNYAZYFkgo1+z0LgUiTKtyV59egaJDGQRABJoSeteVbm+RUAL0NEWkYkDoIXy+eftSIOYnvaYyW3ICIAv91DuIXIJZhQ5whcs1M/GjEmdqPJNb0qBlmRyRbeNg7p14oxPNkUdMT0ZIi9i1hsiybrZOYLcQ3eBXxIpS2alviYlst6MIcxnTNBCK01iJrvvZgUdZGcH5UTEo/7OhwWo+nvrnjMjuTirBWfJcTDt1/RedIdphQerINxUgQoGWhveI+ED95ENHT/qplIdn86sBKtYHtfOIEVhB8C8TttMpl57MsqZto8bsGCNXpjumzqUIo4YYKBaI2/kcwmedDaCLNNs59+MQS33QFR7GlRE3sOa+Tlr8ZxattVbSag==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
