---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgBfGqvpKBrPcQrBwfCU+0RYY0QvL7RxHEoLkYap5b6iIqQvXndHC1+ds+8WVgIblNd9a1KowNXGatZU1i0tLuoRhitXx31GmkVhIsWjsnk+W665lkPsy6uDuVpDZuvelMrLEwwG7W66HE12oNcjOs+zvTKmg4XSj6O2AlqObyldc8rZso4gmkb5ZkAfuJTFWWdkZn4eqxyuIy+rQMurbij8TpQdfdjcDxl8EzihLyGGLgN0mtjzTKVnc+HzLGn9ilVOcjnpnRE3/ckMfT1zhih8raCOIhoKfeqTkVd1HXPsUn7AkLiZyHgkPkXKuKQ3QZ+FI9XBML4tDtFvUocyK9TMEFbpu7EFbeAuMIXRTet4wdVS89Yn7OQlkfvlg5WfmKtSlOVht1H/K7YPDenuyr5YlNaXDKD2f6o/LRwVxFImZeG2gHMNUeqNbYeCuk7Zmtuf9H+7DP1ST46of0FgkDu1lK9Cu5mIrtHGODe44/ymW2/3vwNjxspMNHJsfRG82oB9N1yPetXqSLHbAoTdGW/E7V//iFS4ASImIdWKMaM8MMGkfl5xu7Sqk3+Bv7JyxB4/TTk5+BAeN4X+giygexH993gdxmiwWqZKPjKpkxVSs+KxtwdpqCL+x1zzfXjPRZwokidROj3QxSzznFxomPE/rqEf9xUyOktNwY3eDyjOQlf4EPSMPudFa6kCeTQMsWpsURg5f2Zoig==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
