---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgAhACzXT9H8+KlQEcx0t4s1jVEvHm2bKIy52DVsNfe72cv8lm8znvs1Aq0dkEVBqkJHSJzP+eA/jRQN9kvIDYdb/Em5B77Zx1xjKDFJ/resPT28bBCDIvDvMTyRhGnK2Wla1RNRaC+HdMG3n5fPBVkBbqin5dnMpovAT3MexFAbEyTRUfSWeFKP60bY4i1eXR+M0RoSWkNuBBNNMsijPra8pZRSQg/3xFHSAMfaGvU06iB9wUflhZKOB8zT6kxRraVcNEHvxNxUUnGz1roVmgVhwgPhGR7acykblpQLOArccJvlW1pHybdywcoPXOEF5GBC/cTWMRt3aYveSok85g+/r1SWvQzYrIBKj3NKpU87fpzwQRz4xYtS5Z/944mlzfBKIqnyBqc10jMhQB7yw/NZpjpsgjBUiz7CiBlgg/H/VMZvELoNXmHQLbsPNALLz74DRdDfUyEgMVY73BklB5e1bHFqoq7AJIREu5d/I1mSJgsz3p+3Zy6W3YmVwc+yQUvtPlPWuf5nAfWtszD50J+eD5hsOMoe9gbGV+ffPCP1cNVfwEyap4BDucNLsMXgdYd+4FxrnmcSKegwJm9eZvvNzX+d6+TIVsZ4z9yzDsCeiA23TF8u47OUlHvJrUhrIEYeBW73WYKIQIgtAL+h7qilGfH6Pk5uK/QmMKbX+/19gClkaOtUSOYHpRKwNi/vlgDOxRwpeGvRYXwWNpiCwHe1PmXLP9S5Km3hnW5vy+6rA6dweRdXOPy+tILoxg==
  template:
    metadata:
      name: redis-credentials
      namespace: prod
    type: Opaque
