---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgBdG9cvs+MUVBgqAWxa4veJh/NVZ9ccbcVa/XVLpOO6Wp6QKLZA4blxAngpbbXiwjqSR+54sU/CE8l0IXPU+dgxwH7L28B7FeBQcNrpbFeB7Tr+us8PamblT/93WVsXXVAx8Gz1leqlK/a+0UlDE/Jefzq4OPVLrjweJ5ku6s3q10eme+ytbYiPT/K1AE6nrzEpsL5DFOs9CbO8dvytzya5RUt1kilwpJ2i0ZCoLDANnCGCgZSbFhTcOVKx6dCG5tPqKUvpMrsrIygdeY6C8B1on97xlEqb7cq5hn6Kg6VUu6Zb4u+0CELD04NHA/bsojHF2kYwrYU/UHaSmQL58iaGIt5jpojzPfG1QWdwXS94UPbu7oS77nzknk6sQYKZlA/wx0YiZXqWhL27awcROKngHugnH+IWxdv4/RNzYb9kSfOxJzWxu6j0ME4rLdCUgiNvP9qnv1GHVZcARxqkcHEJcbWDqXW+bqFdrGcyTcdEfexk5o5iR02Fni/wmAOxrsXHK6Pc+QM4rp/g70EwOyhmLAD+B3Cve773C5SVK8ma6V6fr6pl6aeQekRZuPAQm8uVXIL5XCSDC03dAYjUjXpISnP0D3F9lDipgT2zrPBozAV7An96QDe984aNJxnZNTdEy/NU+IQRXpdO5T5yyIPacRwqUfmViJYq9CUSkzSZ8+dAGpLeQHHCZyRfS3dvPFaG2J5gypAEeQ==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
