---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgApmH249fYZbjXeX7ElzS2gL0mqFXeFGf7+5BR251poKt+INjWi7ySJQfOnNyFDMQqsFYpSTTPTTfvJ4X/Hi9auzb0gNkv/0ZJ334E3m264FnkZgdb6gK+LpbRzOJInfdyajBrAUdJcCbsDyj1iDeuiPJBG5fXEKbDanR+7r3rR4p/3UXxmEirWB+Low0KkTtNKzM85PYh2TXGZysh0PBN6twviTsqSYffe6syLcqWrJ/IadjKA5jgr8c2GB+2se6klmRtjb4idfiPFztrwzyJmievffClOyYMXrWWN5xBWlpgsqYQkQ59qfRDwaFCJrlT8TbTPxU1uNCh1RRmCqvBDzHhDNwZ6zLozvSpitLUwIwgk3dHdiLCkhS+RxtyUHSKZjF+Lxbgk51s1OQJTXQrqhYdTUzkfa4wNNFR9Me0jFUkCy7q9pYQsCA2THc0mKJioQEhGcy3Pm2mA95LW6DskIs5EXUSLVAw0QgBgUuClUeTxU7OgdGyGzEprYZAnhaw1vovJuaqsa85gPJKjU7vPGr7HkUL7Kw1f7AWCTDVC+x+PgKUCvTV0qgL2YqeotdoYrRcTDgJGNSMDyvXGeKWgkIP1juz2GaxlmLSbt/LGlDjJ0duMXpM7Zoa4cP6gObwU23xFhWS5MDZGmVJBjGNWF7COmLaHx35jbv9FEObD3XB4PvDGmx3bqAji3mlfhF31HNHJFPnplA==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
