---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgB9oge3KUIAuVSbywgq1R3SgRxde3/aqRTCjWbjL12Hi9ZpWebknfTV762hjUTomNQkNhoFHBmLpmP0+/NjlY+cXeLZTTEfFhBgb9jsjLmPJZzdeGe6qvjP5HuOSvyAF8rlRSWuXHZB+c1If8HkqS3Pt0CnQYp+/Inr6wKHOXKIDWstJqUSnuH1ITr8+DFKMWQG7+Pt0jFHu1+SgkHp66bhZAnAM1W8X/RWjkHF7oQ7anDD+g9umNrX5Km8SXTl9BdxCDwQzyneNZUFvKd208M/E/zv59UUVKJ6XUGloE77zIHOsdh1RgkTub2e3j9odDnGWK8zUt3rxQnzgGI9+RPfQyCpDu8RH+F+vz8xyomP/ZB4ziJc0zmzO6uiYT1OO6LZol7AdqQGK1pwDaYss85PhlMvaLCl67UtQVD2r8w5F2zqHRXRT4nDuaOxF0/GV95fFLOrAXoqHBQAmtoDY42bFbAYX8rFQmEGDSutBTnHma8UenJfAUUR9Mcyh2+rCn0qI9yc45Lja/eLeBai+5gcgt4YiSQ+2ECR3MabuSxeW/Pd6deqOUQOlK0RWBAv9im3hcvqRZ09eWwVrKSi/PhEzRb+BwYmuQevGFsDeDWFjjWTI/5p8D8DlVmm/vOdJgmGVD93nwuWmifc30qxAAxEwpVDkIU5DRG3cQgIywda2woPPlZmwvJdH0ZRuh6EUmMbbDkcCMxciw==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
