---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgB39Tuw4Rl24eJrrtHH+fiAIp1Kx+8YpTjBBAoyGoBJLmWiGQJuSDnJ0/gP31tWJf8uvyEN83mTRIl6Oy8nI/cPNZ9VX/UdsrpRZvbPQmgwxW7rCBow/YPS/H+K7gXk00hbhqxfNfXif02MZwC3z306Q7frscfDuFFsr4n2ERHqAuWv4rCHEX20vaIhSR9IiQApgo4b1gWjNXoUInZC3F8vSJ302dQ92zL/1CyWlYTy4AqR4qlU91F8rINuwbrjHhPxI0gPIaQJwGhdnRCSyyH4dkgiketulyQ2B7+f0R6g45+jlhCLFN+2IfDDeu5bZtTGKC+zCzzguvKw7WysJQ5k7hlQ8HMJVpi14TiQx24PPdSULVrjFUXj9hMZE1AM2RcMwv++k+D3wCgIaB2/aoVi9bkbruYgR29CNgfNCaqRB28gXnbFQNlU3YB3ckFu+au/JOZb0PQ6draJ8IXZzosKa/YLWJ4hwkTSN9qdnXURi02yhLrY8jzpfGMbYkIBsfVSdvRQz28CID7h+ivmuzLgXgO4FK+DQaUIlEqWOUHEtBd67n3gmR1aW5WsgUd5RjfBNX3emgwu9SAipNunb9Rld+JqCsefXhTCMehYN7FGHYfrZ9q2oPMrJMU9Pg6cpkei19nmzX6g9yYQF0Sg65BhduBl7LBgt3TSrbLvJGj8KC3Aec+Biv02FUry3LvBJGt7gtqpx0lM0hzWD+wjBoQ47gG4RQYBIInsiAqnX8EB2Xad1k6BmgDc6r4rqg==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
