---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgDVySnuECRhqIMO7A2KxcBc+Xke2dwCWNJ3XvXlLiS8bvJLIyCzilidZF0oxsKWVCp7tGZBlbtuso+4Ah2CWMYllT4L/KhZzrO6amJhkmvcwSHKeCCvNCRTYaLpzl6ZYzCnjNQQkygojvks3Eu4dgyehDPxMjC+FWLbSLR15ihLNHi3qRKH/knCdJ+MrJNwES/7D1pF7MUIjF6WVWNaGWy91IJ0C2wcszyln3chFaIwKlSZhk2Ce5HG6CtV2grzZLOng9nBcRqHNQp/heBRJHPKLQo3WlXl4Enl5VL+k/4CmK5UrZtvE7J3DKYF4Cf1djvu1UwIfWGKb0rlOFHoqAjLG/YU4rhoPfVOsfPtv/EZjZbQbs0MdRFkjBlYOIXSzVqf3/RSIWaEvOWzrKa1Teqt8+puBlGSGx0SEEZX25mNHyrGwe9cUZwWKDbs0CZgRHNIlfbTx/93mGT0fqvQbtd9lQ2JiIvd9Nqve3WrTfRK8Fu6JZEfP5+wr0XOO5Xkbrt8gjVlkAnNzhw8w+h9P/e2GPs3lNKClXVAHNaKCjcCwqK9f5Ui8Q4qUV6fHmnY1O4ZxSjyhJrdVGh1g0xc/mS0q+Lfg9blIvYK2VS90JiUCo/1+id6g3tDQMFfInPN/BWCsGUk7Jm2XXUcMVTjEC9paX0AkCb4LkDnQnPte+4ev/EXsIEILg+V0LmEFUPGw5kQNv/9R6Is8uPC9ka/rHCEyt+7y/+owZ5qTFN8HHi9A1LFqOPvOGirXCBX6g==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
