---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgDAVRqzzpSrwdAsIglPxFkyehdWJ8qAHh3Cwb447tqUakHG/LDzx2wvnHYnEnob2WKoH1yyjoZioE77ybIvhIiP+fADuWq2SO3LE+hJKB88/pWdKlBqRLRLhjeVkE2I/IgNO3EjFlrEFauItz8AcPNR6r/Rhyufm0iNtT+lokWxRmTeINEZlvtElF0YV+O3L2Ut2fFwcmzgRsiFzB9Vh4bRzC67v9loiLUGIjye1t75KuHU0gQwEuSLa5cfEQhCOmvzzMZPrWmWTxrKpYrLvWfaya9r35ZtBpRaVZwgNyE9PRjmiyhudAouec81gvwTX+MwnzU68sUTqlnhTJLWMh3Ax8dwvghk4DbkYBHYhf7Hrw4NeibdXb3N7Mvvw2dqeCbp2sE9mFhIv/ZMel0RUGJI+uhNnN1MIAiMpfNeC0NC5L0lpf0m6+ggglWzkKo06Fcv6nbduDVEDw0MyU1choNkhovkbrsOjNg0Xr8mlDsKjq+mDyMXSyp9wyozYM17XDIk7vHVGP0hmn2ocEdJXUvOoJfeCYWCyI7egdey3yvOQNrIfnx6WBJY5u7EAzy+oKaEkh6BiEuyPvuz3/KNDID8W3iN1YAAJ2U+ofxun0bopnC7IXtTCQjT1+hdpE3HZ404CWxchFdExsH2hSXb5tz8G6SzgvJhkSnGIwG40K8xot4WpnYq91iJ5d/Ukdr+9bSUh3KQnzXmzzIH2jJ/nBXx0eLfJoy8QumvhUX0p4zECyfuKvzFtv32cwEaKA==
  template:
    metadata:
      name: redis-credentials
      namespace: prod
    type: Opaque
