---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgABmS/VN+CnLMKy0pnXD6Fd1/QKknihiAQzKx5Q6aQ6ufBiyOgwqxctdVb1G4RIWf1zVEw6owwSHVvgjqnRTYEmkxhFDpHwpKU4addqpLDL7Di6GBZvfPN2TZtOJE+xhIjvAblcs358bYwMDcY0pOpMJd3Mqvl5QIl2cYLSVgw2VctamlEhV1I2Q8ssstYy3rqHZev9iHUYMmVgiGXqx1Ec+JLfE0Wa6WkGmW+mZX8ybRLZHmYQllnQHGVhJl6w4+SoPg9J9rrX2iasGQRoM2k7vgSENam1bq4nCn4aC5uoFKkvBU9W/q62bAxhzxHVwvHgTTTvvaZq8aQ3P3DqJgILbOR1fkTX4a1s4wAQuSvxWcZ89mbHe7q34mUG3vTYRnqUAeXQgtRI8KkIV0XVQ2v/p9baobHZJ2yRz3EEvfRNHv1gXlV5lVZ5bIcV3nYXFWYFaIhhebv/xHJcVZ3PfTUbEeQ/iMbJL2Z9MkdVSySCe/OpActPQwzr2gCZZSBfBB6taTSH/DzciYI+MT08nnLZBvfM1vghcqoKVbZ2O4ChFlMyqGLRTaTUvTuGe6lAvWoBZHopQXmEm2/m+rR8QhZtZEWb9CPmFHbtAztfniyIwt9Tb7VbEBDSzw770v03XJhz8wbKsyxNKj7piS585JH1/ADkz5A7NsHy1Tug7pDmLIPpamdT3WhMtq60CQdbzQN/GA1jTBehfdIEduT6+nMpeftbrFSK3NVmnE1MzSvHsniLO8/FsNcLB1NvQQ==
  template:
    metadata:
      name: redis-credentials
      namespace: prod
    type: Opaque
