{{- if .Values.redis.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    password: {{ .Values.redis.password }}
  template:
    metadata:
      name: redis-credentials
      namespace: {{ .Values.namespace }}
    type: Opaque
{{- end }}
