---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgBpYcHn9zOx6wlBgZ8M3jzO25tzHJfi5QcSVyteMpkDh4V6LJWXaY5KEL3x2wCTjhOTxc0jyqJiwhwfKTHlMfVUJZ4LDFY3qYFASvDqVh83SEg7J1MWpaxfjH93j2AOYAZqHu43KArgtQcTwQM1HYoPRTUvSSZ/bExS4IckAK7f0qt1AKzSVt06ckGzUe9J39Mx5bauLxcxHkpeXKA47iQLz9VRnD+kVq8USeI62+sdM+Ms48u//3wwp4rsm29Fv/zkL8YpxNbjwV6nIH4LRKG8iomjr7a0NPzr159ZuCG5MkwrMvAO6osS00SWtjV+eAzhw25LQcy3gQXc8lAboLUJ4X9r4jlNBmBwf8x/j+NOjtoFyWWgmOM7237e0vvkYzWh4O6vV2+5wbJwumOebLzSXe0ugqJw7JkljI2ZYcOERnZWvPZMbeprHXeaVH7rGUhEeJ+LWP+jWbggFRQAsc+VH5IhqaM0VwcIZZ4JnZW5vNlBh/AsPPady5fsRcATDItU5uKBGCCNC2pLpxlo+g+mVlAl2qq4nDTfr+5pxjVF0PI8fzjwIKeZPbe3E6EbtDioQzYkfjutwCwaGuSXWSb4Ic50zdyB+BDHtRoW4BBINS8rIkrd/WQxo+UTGOtuFNg1alw3/aY3PK+0OzQI/PkDzdsidOrmH75NAw8Htg1Az4h78myrmzEWVA2HboGBrZvlwOXDRQqKqg==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
