---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgCrFxCBjgOZTa4MPwsFllXYch/Q+7QQqTeqtOv1cSLd9MuJsTcFnK/0JKiL2vlHTeoQ7k/tMxj+3tZvtRx3yohyK5W6u9y64OR78Ny/5cD+veIjyKVoRWFU1If2JxtphN1pxZvcFz5mBUFy0Cn9IwoOFSxbaTGwAwafcmR4NbNHfjjur5/hgnOJMOraXbV9YmpbQRMdkad60V7dAVea+jvURMEGpjtFdTiaGddmFtJzLeoE4V2tjjixJUeluLHynz9ccq3Vs3JG3VQ5pavvujweEOC1UVqTxyOsR7bmJSLHbFqu68JuktMkfuab2/ih6S2yjJJgmPTBKFyAkxiwl0vy5sJy9aY4LGK2yCN+0Qj0UHGhQW63yngCze3suysHfZuNG0Ql0ASfadPq1VjNHfM0t3WHEUrvU+Zz3l4HhOtUXNwKodLeAsa/+5P+1EiC+rTTq1ErS2wDqAu0x9LMmxvmdEty8fMgDWyR3vFAKcNU1oYnS5dk6fOlnnt8R225hMjOG0vjJt4qV/AxiET28AX+1qmfORQPO9Q/pcCYwk7+6koKxDdsZENjMUaEaNvhbgyXq0EUxgNeMjxL0YymYXC9jNlT5ufJKIZ7U2XrHq+5KkE+jf8KwEAbHxlfXz3o9NOxk4EyH2r9PNGE5n74m69/FXFsLzfQK9o5lUpWXA6NF4/3wWiIv0d4UYFaZPEDyNoDX6RuX1BapQ==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
