---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgBlERedXVi2EFtYu2xv4l2qmo7Tfn3V1RWf1xG2QBBOr/4syL5KeG2J3jd22TPtS5qesYC2gk2RsNebapVBuS1SRAsmDlXFmYoudaAsAuj6DnLCpxMsWgL83VrRfcfZkUpc77FoHKNzwVuC+JRRcmFP2Z0FxwvzMKMAudoyicUwqyW37MTdAEHDNElEIA6ZJCBXereD/TO/5Tt2nIAMWi1ZZxPExBwyiMKEEUlSNHz0ghaY1A4kN9+hwCoZXC2TTLdpAjqgN3tTHQhcCm+MDe3pGxkehiF0FZCMYeeMe5v7FZXgz1rkJDwn1utF7nMWMyNJQScU9zRqLXZycey1J8aoEWmAtROKnG8EaWxgDcLaxmb0Yxa/Zgq04xoga3Zfl2cLC6Sm+WcwUF416jLgwzKi1zzkHKOFkHrm/FJdMskYW/DHF/deeZoy8TVijRmiN3eXUkT2yTFNZmwAWLu4ifb2Th2bi231QSw1brTsYB2OZeUY5yvAs1BO4ChgNO8qrP7Jm1xv1LqaVHwdSv3GxlNCOQqWWU/m768TM+q8O71kd9pofZNF0gjx1VhoJuOZ3c14YAg8VtoBl3WKioKmEpiMGfTD7T8WSYZVZ8/PPvMJSAD3iLERgU3125kCFgL3DILap/OLb9qYtzbSkugRQFxCUfesPE+BDsd8EpCMAMElR/rzLY+pxuMG8A97RmEvhcqUmi5GiSNW3r6vUHmiKJrSGX/KRIzT1B+OS0t8g8EytpkGp1pxZt+B1zzGQg==
  template:
    metadata:
      name: redis-credentials
      namespace: prod
    type: Opaque
