---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgAm+x/wAxODAS6bJY6YARdAMXNN9ED+IkNdEOtmdxb58yjmALLtB69Ozcutl5VyrFh1ueHl0HjEiQi6CRgLwUjDDzffLnZYxGqZ2290426LyhHxMi1Xmdm6wrO4dahoDqyEZSBV/kWsNUBTJUA6KVHd75YFoEDjbz07v0bhflaTPRL210xn78PUBTPOIi+/yjSH+DupZgwA5GJ49NndSwV8SuyhYg3GqNjPPrZNNPKDg5YEhUNTc9ey93nYetBbuPca9T37g/NOU4CV1jrp3BVwec461jbl7y9MnH2zy8PGx/5maJe2uCYPsheUaqJ1GIfauQdDMiwjG4yEDVJZnIUkauBuMX/Qqy14oXaZ/jMCWev7P14TXl731TDIJzrJmiPi3xNtCQSwEyGgxSUS7Fs3MLdmtYAMACQtXSzMakxEuET+3mcn3TAOLjb1UryQabw7opO2afGUTtlmEPLQ79WW6h3llcFKowC59ioRYtZNIoduUCFI3p+6uo/XYJ61sDl1BpPYeo/KnxU53HG7QHb1Sy3r1Zacv8JXJ+93lkkYULj3Feb4Vslt5gUYF/bmw1J/B5z871RvPHn6/pTQ2Rq9E5VU2C93+LpxO3MRbAO+hSHB88MwaoaSnsmho/K02Gv4zcSidgEqWepy4UkEKAOsT9VU/zwSiZSW2hyTRW9BVFM/Nd8yzTz1pJnGswQjmRIgiYAqLpKJQezzNgC2Bic1Vh4Iv5iSxMfOaIPFxUplidjMkSTMesCSRZP3pQ==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
