---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: staging
spec:
  encryptedData:
    password: AgBxJq0KKNi/8uOHYixH1rRWvZ/zUpEDBwirIVXmI7xmMct0aN8/O5sVXzcldHwnUBJQXZ92l+jwL6ZB2aepwjBx9oyJ3drY5Kmg3n+WUbGrYJHXbxedop9R2+Rkh46jKRVIloxUcTHFevb3tNZe6XMD4eSTPN9yORLgaXhSeTAOhwZNDSJdmFrOHW7ytyiecn04Fz4yUVIwNKJQ2HGvHrTGZgoz9joauFbL+2V+Hfx1KxJw530YQlyHZLxGXAG3vD3kK6AhGLye2/5O+Uwdp0veOackqfLNUSyfSiIvlE+ENdRcE1+0SsDFvJt/Zu3PZopoQ8Qwa2Q5rB2g/HkDqS/K+BnwmM092OSFfpdnooOuTNY1xFvm5E3LnaibCHSGrHS7VWL4TtUBhVsYZgtSMicCieLY33IX7UciEVgk7WycDlbIZi3pPEzUJynb+mZqYwsvHXmYycrNEYdpER5osOsUtCPFhjlFevd97sKFeRYl0Euqy/0XxLnf9HiDwHaBkLzyI1cupFdJ2oTszAW+UE5Tj+RmSd2neDjbY5XheJRqL0OV/h+oGLasns96AhcnfXbutRADGllo+SW5VeRqKC7c7RK24AGmQy7q31JsXZH2RQn9MVPJQkuB6epS8NGVNc7UbuPczl5u+ne2+tH9cVcF7M1LCss8WVoN/o7nHM2YLpIHGm2V9/poabFfR1M7mmt9zEJetdSZ4WBl/9UTB8fpBg4NZj5d6TpDmfLD41CwMw40oymRoAqsErDU/w==
  template:
    metadata:
      name: redis-credentials
      namespace: staging
    type: Opaque
