apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scheduler.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scheduler.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: "{{ .Values.postgres.password }}"

