---
# Admin access for namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
  namespace: staging
rules:
  # All resources
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin
  namespace: prod
rules:
  # All resources
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

