{{- if .Values.discord.webhook_url }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-discord.fullname" . }}-secret
  labels:
    {{- include "alertmanager-discord.labels" . | nindent 4 }}
type: Opaque
data:
  webhook_url: {{ .Values.discord.webhook_url | b64enc | quote }}
{{- end }}
