
keycloak:
  instances: 1
  hostname: auth.duli.ai
  db:
    vendor: postgres
    host: postgres-db
    secretName: keycloak-db-secret
  tls:
    enabled: true
    issuerName: letsencrypt-prod
    issuerKind: ClusterIssuer
