$ANSIBLE_VAULT;1.1;AES256
64323765323362663239653530376530663066373463343961313934663139633239323138626537
3463326239653162643435316639633632383830646365630a393235663830653230343362313632
33633537373834303634646133386362326634383736643631376564333732373464333735306665
3134646663666134380a396166353131366236376633653436353430333138393532623365313765
36393863663066656561653563376539343361646630646664663338383938653130313233346132
64376162336363313734336563316634376131623538636437333438383034353438393666356635
63613532633838616135363962666465393330393133373962373232373064636430353164313763
63306161656132366630373231623537366236313938646665343866353133356437396464386661
31343763663032363164613032653665353939316366336235323430326161366235383161323834
61333164383935373161336630333762316563373034323861613338386139366236313636363430
64626563653261343933356235376132313031336434643031393061306263346164343932356533
34303563343664396631396239393066643961343937363934353130613861356531623831316663
30623432646130376137646366363739666138386233323663386131396165373937366339363537
35333433653431363137363231393066306133343434633331386130653139306264623865366665
61313436306639383035333236343034353238356162613233313863653964663966326634613533
34643033373566346439356639656263313261393033393264643538633530366532393563353735
62373761643036653333323866346537306133333266396163646533623834396131643966366463
62616135613561656531323433393565306465393637663331313231343263336431626336363230
34393564643732633964626531633536323562373932333838363534386338653436353938643836
38366365656237623963313138306464653039343638333537633431363834613864383832653037
62633631356465313835356363323031646633656231613935363962386634656237616533323766
61366439386337636339633764653431313338376531663763666239313938343464656566386132
65663161613434373461633064373763626533613738373232633637353337373630326632313639
36633461656362653466326638653863656234306434623365316531646236653261323632653738
65666161303331623731326130643130623564323965353365343432396639323630646633333132
38633863353737653730303339623166366535383834633665643931613463356539303531316339
33326465336438306535346264313239313564633434303363613436666663313335373538326166
33366237386133376631373331653437333666323338313062303930346365353131313532303634
31643439663039346664663564633663383166333135623532303332663732366562
