{{- if .Values.cluster.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak-db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
spec:
  description: "Dedicated PostgreSQL Cluster for Keycloak"
  imageName: {{ .Values.cluster.imageName }}
  instances: {{ .Values.cluster.instances }}
  
  superuserSecret:
    name: {{ .Values.cluster.credentials.secretName }}
  
  bootstrap:
    initdb:
      database: {{ .Values.cluster.bootstrap.initdb.database }}
      owner: {{ .Values.cluster.bootstrap.initdb.owner }}
      secret:
        name: {{ .Values.cluster.credentials.secretName }}
  
  postgresql:
    parameters:
{{- range $key, $value := .Values.cluster.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
{{- end }}
  
  primaryUpdateStrategy: unsupervised

  storage:
    size: {{ .Values.cluster.storage.size }}
    storageClass: {{ .Values.cluster.storage.storageClass }}
{{- end }}
